SELECT
      SPRIDEN.SPRIDEN_ID AS BANNER_ID,
      GORADID.GORADID_ADDITIONAL_ID AS SUID,
      SPRIDEN.SPRIDEN_LAST_NAME AS LNAME,
      SPRIDEN.SPRIDEN_FIRST_NAME AS FNAME,
      F_FORMAT_NAME(SPRIDEN.SPRIDEN_PIDM, 'LF30') AS FULL_NAME,
      SPRIDEN.SPRIDEN_MI AS MI,
      SPBPERS.SPBPERS_SEX AS GENDER,
      SPBPERS.SPBPERS_SSN AS SSN,
      SARADAP.SARADAP_TERM_CODE_ENTRY AS ENTRY_TERM,
      SARADAP.SARADAP_LEVL_CODE AS LEVL_CODE,
      F_GET_DESC_FNC('STVDEGC',SGBSTDN.SGBSTDN_DEGC_CODE_1, 30) AS DEG_SOUGHT,
      SARADAP.SARADAP_APPL_NO AS APPNO,
      SARAPPD1.SARAPPD_APDC_CODE AS PREVIOUS_ENTRY_CODE,
      SARAPPD1.SARAPPD_APDC_DATE AS PREVIOUS_ENTRY_DATE,
      SARAPPD.SARAPPD_APDC_CODE AS NEW_ENTRY_CODE,--PREVIOUS_APDC_CODE,
      SARAPPD.SARAPPD_APDC_DATE AS NEW_ENTRY_DATE

-- DATA SOURCES

FROM
      --ADMISSIONS DATA: (A)
      SARAPPD SARAPPD

      --APPLICATION
      LEFT OUTER JOIN SARADAP SARADAP ON SARADAP.SARADAP_PIDM = SARAPPD.SARAPPD_PIDM
          AND SARADAP.SARADAP_TERM_CODE_ENTRY = SARAPPD.SARAPPD_TERM_CODE_ENTRY
          AND SARADAP.SARADAP_APPL_NO = (SELECT MAX(SARADAP_APPL_NO)
                                        FROM SARADAP SARADAPX
                                        WHERE SARADAPX.SARADAP_PIDM = SARAPPD.SARAPPD_PIDM
                                        AND SARADAPX.SARADAP_TERM_CODE_ENTRY = SARAPPD.SARAPPD_TERM_CODE_ENTRY)

      --ADMISSIONS DATA: (B)
      LEFT OUTER JOIN SARAPPD SARAPPD1 ON SARAPPD1.SARAPPD_PIDM = SARAPPD.SARAPPD_PIDM
          AND SARAPPD1.SARAPPD_TERM_CODE_ENTRY = SARAPPD.SARAPPD_TERM_CODE_ENTRY
          AND SARAPPD1.SARAPPD_APPL_NO = SARAPPD.SARAPPD_APPL_NO

      --IDENTIFICATION
      LEFT OUTER JOIN SPRIDEN SPRIDEN ON SPRIDEN.SPRIDEN_PIDM = SARAPPD.SARAPPD_PIDM
           AND SPRIDEN.SPRIDEN_NTYP_CODE IS NULL
           AND SPRIDEN.SPRIDEN_CHANGE_IND IS NULL

      LEFT OUTER JOIN SPBPERS SPBPERS ON SPBPERS.SPBPERS_PIDM = SPRIDEN.SPRIDEN_PIDM

      LEFT OUTER JOIN GORADID GORADID ON GORADID.GORADID_PIDM = SPRIDEN.SPRIDEN_PIDM
           AND GORADID.GORADID_ADID_CODE = 'SUID'

     --STUDENT REGISTATIONS
     LEFT OUTER JOIN SGBSTDN SGBSTDN ON SGBSTDN.SGBSTDN_PIDM = SPRIDEN.SPRIDEN_PIDM
          AND SGBSTDN.SGBSTDN_TERM_CODE_EFF = fy_sgbstdn_eff_term(SGBSTDN.SGBSTDN_PIDM, SARAPPD.SARAPPD_TERM_CODE_ENTRY)

WHERE
     SARAPPD.SARAPPD_TERM_CODE_ENTRY = :parm_term_code_select.STVTERM_CODE
     AND SARAPPD1.SARAPPD_SEQ_NO IS NOT NULL
     AND SARAPPD1.SARAPPD_SEQ_NO = (SARAPPD.SARAPPD_SEQ_NO - 1)
     --AND SARAPPD.SARAPPD_APDC_CODE in ('AP', 'AC')
     --AND SARAPPD.SARAPPD_APDC_CODE IN ('PP', 'WL', 'AC', 'AP','DN','DR','MO','WD','QA','DF','UP','GT','CF')


--$addfilter

--$beginorder

-- GROUPING/ORDERING

ORDER BY SARAPPD.SARAPPD_APDC_DATE, FULL_NAME, SARAPPD.SARAPPD_SEQ_NO

--$endorder
