--Enrolled Students Contact Information

select
    SPRIDEN.SPRIDEN_ID as "Banner_ID",
    f_format_name(SPRIDEN.SPRIDEN_PIDM,'LF30') as "Student_Name",
    SPBPERS.SPBPERS_PREF_FIRST_NAME as "Pref_Name",
    -- SU EMAIL
    GORADID.GORADID_ADDITIONAL_ID as "SUID",
    GOREMAL.GOREMAL_EMAIL_ADDRESS as "Email",
    SGBSTDN.SGBSTDN_LEVL_CODE as Class_Levl,
    SGBSTDN.SGBSTDN_DEGC_CODE_1 as "Deg_Progam",
    -- CONTACT INFORMATION
    SPRTELE.SPRTELE_PHONE_AREA as "Area_Code",
    SPRTELE.SPRTELE_PHONE_NUMBER as "Phone_Number",
    F_GET_DESC_FNC('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_1, 30) as "Major_Program",
    F_GET_DESC_FNC('STVSTYP', SGBSTDN.SGBSTDN_STYP_CODE, 30) as "Reg_Type",

    -- ORDER
    STVLEVL.STVLEVL_SURROGATE_ID,
    SGBSTDN.SGBSTDN_DEGC_CODE_1,
    SPRIDEN.SPRIDEN_SEARCH_LAST_NAME,
    SPRIDEN.SPRIDEN_SEARCH_FIRST_NAME

--SRC
from
    STVTERM STVTERM

    left outer join SPRIDEN SPRIDEN on SPRIDEN.SPRIDEN_PIDM is not null

    -- SUID
    left outer join GORADID GORADID on GORADID.GORADID_PIDM = SPRIDEN.SPRIDEN_PIDM and GORADID.GORADID_ADID_CODE = 'SUID'

    -- PERSONAL INFORMATION
    left outer join SPBPERS SPBPERS on SPBPERS.SPBPERS_PIDM = SPRIDEN.SPRIDEN_PIDM

    --STUDENT EMAIL
    left outer join GOREMAL GOREMAL on GOREMAL.GOREMAL_PIDM = SPRIDEN.SPRIDEN_PIDM
         and GOREMAL.GOREMAL_EMAL_CODE = 'SU'
         and GOREMAL.GOREMAL_PREFERRED_IND = 'Y'

    -- HOME CONTACT INFORMATION
    left outer join SPRTELE SPRTELE on SPRTELE.SPRTELE_PIDM = SPRIDEN.SPRIDEN_PIDM
         and SPRTELE.SPRTELE_SURROGATE_ID = (select max(SPRTELE_SURROGATE_ID)
                                    from SPRTELE SPRTELEX
                                    where SPRTELEX.SPRTELE_PIDM = SPRTELE.SPRTELE_PIDM
                                    and SPRTELEX.SPRTELE_STATUS_IND is null)

    -- STUDENT PROGRAM DETAILS
    left outer join SGBSTDN SGBSTDN on SGBSTDN.SGBSTDN_PIDM = SPRIDEN.SPRIDEN_PIDM
        and SGBSTDN.SGBSTDN_TERM_CODE_EFF = fy_sgbstdn_eff_term(SGBSTDN.SGBSTDN_PIDM, STVTERM.STVTERM_CODE)
        and SGBSTDN.SGBSTDN_MAJR_CODE_1 not in ('SUS','EHS', '0000', 'UNDC')
        and SGBSTDN.SGBSTDN_STST_CODE in ('AS')

    -- ADDTIONAL INFORMATION
    left outer join STVLEVL STVLEVL on STVLEVL.STVLEVL_CODE = SGBSTDN.SGBSTDN_LEVL_CODE

where
    STVTERM.STVTERM_CODE = :ddSemester.STVTERM_CODE
    and SPRIDEN.SPRIDEN_NTYP_CODE IS NULL
    and SPRIDEN.SPRIDEN_CHANGE_IND IS NULL
    and 'Y' = f_registered_this_term(SPRIDEN.SPRIDEN_PIDM, STVTERM.STVTERM_CODE)

--$addfilter

--$beginorder

order by
    STVLEVL.STVLEVL_SURROGATE_ID,
    SGBSTDN.SGBSTDN_DEGC_CODE_1,
    SPRIDEN.SPRIDEN_SEARCH_LAST_NAME,
    SPRIDEN.SPRIDEN_SEARCH_FIRST_NAME
--$endorder