SFRSTCR_TERM_CODE <= :select_term_code.STVTERM_CODE
AND SFRSTCR_RSTS_CODE = 'RE'
AND SFRSTCR_GRDE_CODE IS NOT NULL
AND SHRTCKG_GRDE_CODE_FINAL IS NOT NULL

ORDER BY
    SPRIDEN_LAST_NAME,
    SPRIDEN_FIRST_NAME,
    SPRIDEN_MI