-- REPORT FORMAT
Select

    -- ESF/SU ID DETAILS
    SPRIDEN.SPRIDEN_ID BannerID,
    SPRIDEN.SPRIDEN_LAST_NAME LNAME,
    SPRIDEN.SPRIDEN_FIRST_NAME FNAME,

    -- FEDERAL AWARD DETAILS
    RPRAWRD.RPRAWRD_FUND_CODE,
    RCRAPP2.RCRAPP2_INFC_CODE,
    RCRAPP1.RCRAPP1_INFC_CODE,
    RCRAPP1.RCRAPP1_SEQ_NO,
    RCRAPP2_PELL_PGI,

    -- APPLICATION DETAILS
       (CASE
       WHEN STVAPDC_REJECT_IND = 'Y' THEN 'DN'
       WHEN STVAPDC_APPL_INACT = 'Y' THEN 'IN'
       WHEN STVAPDC_STDN_ACC_IND = 'Y' THEN 'SA'
       WHEN STVAPDC_INST_ACC_IND = 'Y' THEN 'IA'
       ELSE 'ND'
         END) as STAGE_CODE,
       (CASE
       WHEN STVAPDC_REJECT_IND = 'Y' THEN 'Applicant Denied'
       WHEN STVAPDC_APPL_INACT = 'Y' THEN 'Institution Acceptance'
       WHEN STVAPDC_STDN_ACC_IND = 'Y' THEN 'Student Acceptance'
       WHEN STVAPDC_INST_ACC_IND = 'Y' THEN 'Inactive'
       ELSE 'ND'
         END) as STAGE_DESC,

    -- STUDENT DETAILS
    SGBSTDN.SGBSTDN_STST_CODE,
    SGBSTDN.SGBSTDN_STYP_CODE,

    -- FEDERAL FUND DETAILS
    RPRAWRD.RPRAWRD_FUND_CODE,
    RPRAWRD.RPRAWRD_AWST_DATE,
    RPRAWRD.RPRAWRD_ACTIVITY_DATE,
    RPRAWRD.RPRAWRD_OFFER_EXP_DATE,
    RPRAWRD.RPRAWRD_ACCEPT_AMT,
    RPRAWRD.RPRAWRD_ACCEPT_DATE,
    RPRAWRD.RPRAWRD_PAID_AMT,
    RPRAWRD.RPRAWRD_ORIG_OFFER_AMT,
    RPRAWRD.RPRAWRD_ORIG_OFFER_DATE,
    RPRAWRD.RPRAWRD_OFFER_AMT,
    RPRAWRD.RPRAWRD_OFFER_DATE,
    RCRAPP1.RCRAPP1_CREATE_DATE,
    RCRAPP1.RCRAPP1_ACTIVITY_DATE,
    RCRAPP1.RCRAPP1_RCPT_DATE,
    RCRAPP1.RCRAPP1_ORIG_COMP_DATE,
    RCRAPP1.RCRAPP1_PAR_US_INC,
    RCRAPP1.RCRAPP1_COMPLETION_DATE,
    RCRAPP2.RCRAPP2_INFC_CODE,
    RCRAPP2.RCRAPP2_ACTIVITY_DATE

-- DARA SOURCES
from

-- IDENTIFICATION
    SPRIDEN SPRIDEN

    join GORADID GORADID on GORADID.GORADID_PIDM = SPRIDEN.SPRIDEN_PIDM
         and GORADID.GORADID_ADID_CODE = 'SUID'

-- TERM SELECTION
    join STVTERM STVTERM on STVTERM.STVTERM_CODE = :parm_term_code_select.STVTERM_CODE

-- STUDENT DATA
    left outer join SGBSTDN SGBSTDN on SGBSTDN.SGBSTDN_PIDM = SPRIDEN.SPRIDEN_PIDM
         and SGBSTDN.SGBSTDN_TERM_CODE_EFF = fy_sgbstdn_eff_term(SGBSTDN.SGBSTDN_PIDM, STVTERM.STVTERM_CODE)
         and SGBSTDN.SGBSTDN_MAJR_CODE_1 not in ('0000', 'EHS', 'SUS', 'VIS')
         and SGBSTDN.SGBSTDN_STST_CODE = 'AS'

    left outer join SHRTGPA SHRTGPA on SHRTGPA.SHRTGPA_PIDM = SPRIDEN.SPRIDEN_PIDM
         and SHRTGPA.SHRTGPA_TERM_CODE = STVTERM.STVTERM_CODE
         and SHRTGPA.SHRTGPA_GPA_TYPE_IND = 'I'

    left outer join SHRLGPA SHRLGPA on SHRLGPA.SHRLGPA_PIDM = SPRIDEN.SPRIDEN_PIDM
         and SHRLGPA.SHRLGPA_LEVL_CODE = SGBSTDN.SGBSTDN_LEVL_CODE
         and SHRLGPA.SHRLGPA_GPA_TYPE_IND = 'I'
         and SHRLGPA.SHRLGPA_GPA is not null

-- APPLICATION DATA
    left outer join SARAPPD SARAPPD on SARAPPD.SARAPPD_PIDM = SPRIDEN.SPRIDEN_PIDM
         and SARAPPD.SARAPPD_TERM_CODE_ENTRY = STVTERM.STVTERM_CODE
         and SARAPPD.SARAPPD_APPL_NO = (select max(SARAPPD_APPL_NO)
                                       from SARAPPD SARAPPDX
                                       where SARAPPDX.SARAPPD_PIDM = SARAPPD.SARAPPD_PIDM
                                       and SARAPPDX.SARAPPD_TERM_CODE_ENTRY = SARAPPD.SARAPPD_TERM_CODE_ENTRY)

    left outer join STVAPDC STVAPDC on STVAPDC.STVAPDC_CODE = SARAPPD.SARAPPD_APDC_CODE
/*
         --BELOW SECTION: OPTIONAL
    left outer join RRVYAPST RRVYAPST on RRVYAPST.RRVYAPST_pidm = SPRIDEN.SPRIDEN_PIDM
         and RRVYAPST.RRVYAPST_AIDY_CODE = STVTERM_FA_PROC_YR
*/

-- FEDERAL AID DATA
    left outer join RPRAWRD RPRAWRD on RPRAWRD.RPRAWRD_PIDM = SPRIDEN.SPRIDEN_PIDM
         and RPRAWRD.RPRAWRD_AIDY_CODE = STVTERM.STVTERM_FA_PROC_YR
         and RPRAWRD.RPRAWRD_FUND_CODE in ( 'FPELL', 'FSEOG')

    left outer join RCRAPP1 RCRAPP1 on RCRAPP1.RCRAPP1_PIDM = RPRAWRD.RPRAWRD_PIDM
         and RCRAPP1.RCRAPP1_AIDY_CODE = STVTERM.STVTERM_FA_PROC_YR
         and RCRAPP1.RCRAPP1_SEQ_NO = (select max(RCRAPP1_SEQ_NO)
                                      from RCRAPP1 RCRAPP1X
                                      where RCRAPP1X.RCRAPP1_PIDM = RPRAWRD.RPRAWRD_PIDM
                                      and RCRAPP1X.RCRAPP1_AIDY_CODE = STVTERM.STVTERM_FA_PROC_YR
                                          )
         and RCRAPP1.RCRAPP1_SURROGATE_ID = (select max(RCRAPP1_SURROGATE_ID)
                                            from RCRAPP1 RCRAPP1X
                                            where RCRAPP1X.RCRAPP1_PIDM = RPRAWRD.RPRAWRD_PIDM
                                            and RCRAPP1X.RCRAPP1_AIDY_CODE = STVTERM.STVTERM_FA_PROC_YR
                                                )

    left outer join RCRAPP2 RCRAPP2 on RCRAPP2.RCRAPP2_PIDM = RPRAWRD.RPRAWRD_PIDM
         and RCRAPP2.RCRAPP2_AIDY_CODE = RCRAPP1.RCRAPP1_AIDY_CODE
         and RCRAPP2.RCRAPP2_SEQ_NO = RCRAPP1.RCRAPP1_SEQ_NO
         and RCRAPP2.RCRAPP2_INFC_CODE = RCRAPP1.RCRAPP1_INFC_CODE
         and RCRAPP2.RCRAPP2_SURROGATE_ID = (select max(RCRAPP2_SURROGATE_ID)
                                            from RCRAPP2 RCRAPP2X
                                            where RCRAPP2X.RCRAPP2_PIDM = RPRAWRD.RPRAWRD_PIDM
                                            and RCRAPP2X.RCRAPP2_AIDY_CODE = RCRAPP2.RCRAPP2_AIDY_CODE
                                            and RCRAPP2X.RCRAPP2_INFC_CODE = RCRAPP2.RCRAPP2_INFC_CODE
                                                )

    -- ADDITIONAL DETAILS
    join STVCLAS STVCLAS on STVCLAS.STVCLAS_CODE = f_class_calc_fnc(SGBSTDN.SGBSTDN_PIDM,SGBSTDN.SGBSTDN_LEVL_CODE,STVTERM.STVTERM_CODE)

--CONDITIONS
where
    SPRIDEN.SPRIDEN_NTYP_CODE is null
    and SPRIDEN.SPRIDEN_CHANGE_IND is null

    -- TERM REGISTRATION CHECK
    and exists(
        select *
        from SFRSTCR SFRSTCR
        where SFRSTCR.SFRSTCR_PIDM = SPRIDEN.SPRIDEN_PIDM
        and SFRSTCR.SFRSTCR_TERM_CODE = STVTERM.STVTERM_CODE
        and SFRSTCR.SFRSTCR_RSTS_CODE like 'R%')

--$addfilter

--$beginorder

-- GROUPING/ORDERING
order by
    RPRAWRD.RPRAWRD_FUND_CODE, STVCLAS.STVCLAS_SURROGATE_ID, SPRIDEN.SPRIDEN_SEARCH_LAST_NAME

--$endorder