select STVMAJR.STVMAJR_CODE,
       STVMAJR.STVMAJR_DESC,
       STVMAJR.STVMAJR_CIPC_CODE,
       STVCIPC.STVCIPC_DESC,
       STVCIPC.STVCIPC_PUB_YEAR
  from SATURN.STVMAJR STVMAJR,
       SATURN.STVCIPC STVCIPC
 where ( STVCIPC.STVCIPC_CODE = STVMAJR.STVMAJR_CIPC_CODE )
   and ( STVMAJR.STVMAJR_VALID_MAJOR_IND = 'Y'
         and STVMAJR.STVMAJR_CODE not in ('EHS','SUS') )
 order by STVMAJR.STVMAJR_DESC
