NOT EXISTS(SELECT *
          FROM    SFRSTCR SFRSTCR
          LEFT OUTER JOIN SSBSECT SSBSECT ON SSBSECT_TERM_CODE = SFRSTCR_TERM_CODE
               AND SSBSECT_CRN = SFRSTCR_CRN
          WHERE   SFRSTCR_PIDM = SPRIDEN_PIDM
          AND     SFRSTCR_TERM_CODE <= :select_term_code.STVTERM_CODE
          AND     SFRSTCR_RSTS_CODE in ('RE', 'RW')
          AND     SSBSECT_SUBJ_CODE = 'EFB'
          AND     SSBSECT_CRSE_NUMB = '202')

AND SGBSTDN_MAJR_CODE_1 in ('AFSC', 'ENBI', 'CONB', 'EEIN', 'FOHE', 'WLSC')
AND EXISTS (SELECT * FROM SFAREGS WHERE SFRSTCR_PIDM = SPRIDEN_PIDM AND SFRSTCR_TERM_CODE = :select_term_code.STVTERM_CODE AND SFRSTCR_RSTS_CODE IN ('RE','RW'))
