-- min/max term selection
select STVTERM_CODE AS CODE, STVTERM_DESC AS DESCR
FROM STVTERM
WHERE STVTERM_START_DATE > SYSDATE -130 AND STVTERM_START_DATE < SYSDATE + 130
and substr(stvterm_code,5,1) in ('1','3')
ORDER BY STVTERM_CODE DESC

select STVTERM_CODE AS CODE, STVTERM_DESC AS DESCR
FROM STVTERM
WHERE STVTERM_START_DATE > SYSDATE -130 AND STVTERM_START_DATE < SYSDATE + 130
and substr(stvterm_code,5,1) in ('1','3')
ORDER BY STVTERM_CODE DESC

-- apdc selection
SELECT * FROM
(select STVAPDC_CODE AS APDC, STVAPDC_DESC AS DESCR from STVAPDC
UNION
SELECT 'AX' AS APDC, 'No Appl or Decision' as DESCR from DUAL
UNION
SELECT 'EN' AS APDC, 'Enrolled Continuing' AS DESCR from DUAL
)
WHERE
(CASE WHEN :chkNormalAPDC <> 1 THEN 1
      WHEN :chkNormalAPDC = 1 THEN CASE WHEN APDC IN ('AC','AP','CF','EN') THEN 1 ELSE 0 END
      ELSE 1 END) = 1
ORDER BY APDC