-- Term Selection
select STVTERM.STVTERM_CODE,
       STVTERM.STVTERM_DESC,
(STVTERM.STVTERM_CODE || ' - ' ||
       STVTERM.STVTERM_DESC) as TermDesc
        from SATURN.STVTERM STVTERM
        where stvterm_start_date < sysdate + 365
        and stvterm_start_date >= sysdate -9999
        and STVTERM.STVTERM_CODE not in (000000, 190001)
 order by STVTERM.STVTERM_CODE desc

-- Course Subject
SELECT DISTINCT SSBSECT.SSBSECT_SUBJ_CODE AS SUBJ_CODE
--SSBSECT.SSBSECT_SUBJ_CODE ||' - ' || f_get_Desc_fnc('STVSUBJ', SSBSECT.SSBSECT_SUBJ_CODE, 30) AS SUBJ_DESC

FROM
    SSBSECT SSBSECT

    LEFT OUTER JOIN SIRASGN SIRASGN ON SIRASGN.SIRASGN_TERM_CODE = SSBSECT.SSBSECT_TERM_CODE
         AND SIRASGN.SIRASGN_CRN = SSBSECT.SSBSECT_CRN
         AND SIRASGN.SIRASGN_CATEGORY = 01

WHERE
    SSBSECT.SSBSECT_TERM_CODE = :select_term_code.STVTERM_CODE

UNION
select
    '-All-'

from
    dual

order by 1
/*
ORDER BY
    SSBSECT.SSBSECT_SUBJ_CODE
    */

-- Course Number
SELECT
    SSBSECT.SSBSECT_CRSE_NUMB AS CRSE_NUMB

FROM SSBSECT SSBSECT

     JOIN SCBCRSE SCBCRSE ON SCBCRSE.SCBCRSE_SUBJ_CODE = SSBSECT.SSBSECT_SUBJ_CODE
          AND SCBCRSE.SCBCRSE_CRSE_NUMB = SSBSECT.SSBSECT_CRSE_NUMB
          AND SCBCRSE.SCBCRSE_EFF_TERM = (SELECT MAX(SCBCRSE.SCBCRSE_EFF_TERM)
                                         FROM SCBCRSE SCBCRSEX
                                         WHERE SCBCRSEX.SCBCRSE_SUBJ_CODE = SSBSECT.SSBSECT_SUBJ_CODE
                                         AND SCBCRSEX.SCBCRSE_CRSE_NUMB = SSBSECT.SSBSECT_CRSE_NUMB
                                         AND SCBCRSEX.SCBCRSE_EFF_TERM <= SSBSECT.SSBSECT_TERM_CODE
                                   )

     LEFT OUTER JOIN SIRASGN SIRASGN ON SIRASGN.SIRASGN_TERM_CODE = SSBSECT.SSBSECT_TERM_CODE
          AND SIRASGN.SIRASGN_CRN = SSBSECT.SSBSECT_CRN
          AND SIRASGN.SIRASGN_CATEGORY = 01

WHERE
SSBSECT.SSBSECT_TERM_CODE = :select_term_code.STVTERM_CODE

AND SSBSECT.SSBSECT_SUBJ_CODE = :select_subj_code.SUBJ_CODE
UNION
select
    '-All-'
from
    dual
order by 1