with SPAIDEN as (

    select
        SPRIDEN.SPRIDEN_ID,
        SPRIDEN.SPRIDEN_PIDM,
        SPRIDEN.SPRIDEN_LAST_NAME,
        SPRIDEN.SPRIDEN_FIRST_NAME,
        SPRIDEN.SPRIDEN_MI,
        SPRIDEN.SPRIDEN_NTYP_CODE,
        SPRIDEN.SPRIDEN_CHANGE_IND,
        SPRIDEN.SPRIDEN_SEARCH_LAST_NAME,
        SPRIDEN.SPRIDEN_SEARCH_FIRST_NAME,
        SPRIDEN.SPRIDEN_SEARCH_MI,
        GORADID.GORADID_PIDM,
        GORADID.GORADID_ADDITIONAL_ID as GORADID_SU_ID,
        GORADID.GORADID_ADID_CODE,
        f_format_name(SPRIDEN.SPRIDEN_PIDM, 'LFMI') as SPRIDEN_LEGAL_NAME

    from
        SPRIDEN SPRIDEN

        left outer join GORADID GORADID on GORADID.GORADID_PIDM = SPRIDEN.SPRIDEN_PIDM
            and GORADID.GORADID_ADID_CODE = 'SUID'

    where
        SPRIDEN.SPRIDEN_NTYP_CODE is null
        and SPRIDEN.SPRIDEN_CHANGE_IND is null
   ),

SOREMAL as (

    select
        GOREMAL.GOREMAL_PIDM as GOREMAL_PIDM,
        GOREMAL.GOREMAL_EMAL_CODE as GOREMAL_EMAL_CODE,
        GOREMAL.GOREMAL_EMAIL_ADDRESS as GOREMAL_EMAIL_ADDRESS,
        GOREMAL.GOREMAL_STATUS_IND as GOREMAL_STATUS_IND,
        GOREMAL.GOREMAL_PREFERRED_IND as GOREMAL_PREFFERED_IND,
        GOREMAL1.GOREMAL_EMAL_CODE as GOREMAL1_EMAL_CODE,
        GOREMAL1.GOREMAL_EMAIL_ADDRESS as PERS_EMAIL,
        GOREMAL1.GOREMAL_STATUS_IND as GOREMAL1_STATUS_IND,
        GOREMAL1.GOREMAL_PREFERRED_IND as GOREMAL_PREFFERED_IND

    from
        GOREMAL GOREMAL

        left outer join GOREMAL GOREMAL1 on GOREMAL1.GOREMAL_PIDM = GOREMAL.GOREMAL_PIDM
             and GOREMAL1.GOREMAL_EMAL_CODE = 'PERS'
             and GOREMAL1.GOREMAL_STATUS_IND = 'A'
             and GOREMAL1.GOREMAL_SURROGATE_ID = (select max(GOREMAL_SURROGATE_ID)
                                            from GOREMAL GOREMALX
                                            where GOREMALX.GOREMAL_PIDM = GOREMAL1.GOREMAL_PIDM)

    where
        GOREMAL.GOREMAL_EMAL_CODE = 'SU'
        and GOREMAL.GOREMAL_STATUS_IND = 'A'),

SPAPERS as (

    select
        SPBPERS.SPBPERS_PIDM as SPBPERS_PIDM,
        SPBPERS.SPBPERS_SSN as SPBPERS_SSN,
        SPBPERS.SPBPERS_BIRTH_DATE as SBPERS_BIRTH_DATE,
        SPBPERS.SPBPERS_SEX as SPBPERS_SEX,
        SPBPERS.SPBPERS_PREF_FIRST_NAME as SPBPERS_PREF_FIRST_NAME,
        SPBPERS.SPBPERS_CITZ_CODE as SPBPERS_CITZ_CODE,
        SPBPERS.SPBPERS_GNDR_CODE as SPBPERS_GNDR_CODE

   from
        SPBPERS SPBPERS
    ),

SGASTDN as (

    select
        SGBSTDN.SGBSTDN_PIDM,
        SGBSTDN.SGBSTDN_TERM_CODE_EFF,
        SGBSTDN.SGBSTDN_STST_CODE,
        SGBSTDN.SGBSTDN_LEVL_CODE,
        SGBSTDN.SGBSTDN_STYP_CODE,
        SGBSTDN.SGBSTDN_TERM_CODE_MATRIC,
        SGBSTDN.SGBSTDN_EXP_GRAD_DATE,
        SGBSTDN.SGBSTDN_DEGC_CODE_1,
        SGBSTDN.SGBSTDN_MAJR_CODE_1,
        SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1 as SGBSTDN_MINR_CODE_1,
        SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1_2 as SGBSTDN_MINR_CODE_2,
        SGBSTDN.SGBSTDN_MAJR_CODE_CONC_1 as SGBSTDN_CONC_CODE_1,
        SGBSTDN.SGBSTDN_RESD_CODE,
        SGBSTDN.SGBSTDN_ADMT_CODE,
        SGBSTDN.SGBSTDN_DEPT_CODE,
        SGBSTDN.SGBSTDN_PROGRAM_1,
        f_class_calc_fnc(SGBSTDN.SGBSTDN_PIDM,SGBSTDN.SGBSTDN_LEVL_CODE, :select_term_code.STVTERM_CODE) as SGBSTDN_CLASS_CODE,
        f_Get_desc_fnc('STVSTST',SGBSTDN.SGBSTDN_STST_CODE, 30) as SGBSTDN_STST_DESC,
        f_Get_desc_fnc('STVLEVL', SGBSTDN.SGBSTDN_LEVL_CODE, 30) as SGBSTDN_LEVL_DESC,
        f_Get_desc_fnc('STVSTYP', SGBSTDN.SGBSTDN_STYP_CODE, 30) as SGBSTDN_STYP_DESC,
        f_Get_desc_fnc('STVDEGC', SGBSTDN.SGBSTDN_DEGC_CODE_1, 30) as SGBSTDN_DEGC_DESC,
        f_Get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_1, 30) as SGBSTDN_MAJR_DESC,
        f_Get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1, 30) as SGBSTDN_MINR_1_DESC,
        f_Get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1_2, 30) as SGBSTDN_MINR_1_2_DESC,
        f_Get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_CONC_1, 30) as SGBSTDN_CONC_DESC,
        f_Get_desc_fnc('STVRESD', SGBSTDN.SGBSTDN_RESD_CODE, 30) as SGBSTDN_RESD_DESC,
        f_Get_desc_fnc('STVADMT', SGBSTDN.SGBSTDN_ADMT_CODE, 30) as SGBSTDN_ADMT_DESC,
        f_Get_desc_fnc('STVDEPT', SGBSTDN.SGBSTDN_DEPT_CODE, 30) as SGBSTDN_DEPT_DESC,
        f_Get_desc_fnc('STVCLAS', f_class_calc_fnc(SGBSTDN.SGBSTDN_PIDM,SGBSTDN.SGBSTDN_LEVL_CODE, :select_term_code.STVTERM_CODE), 30) as SGBSTDN_CLASS_DESC

   from
        SGBSTDN SGBSTDN
   ),

SFAREGS as (
    select
        SFRSTCR.SFRSTCR_PIDM,
        SFRSTCR.SFRSTCR_CRN,
        SFRSTCR.SFRSTCR_TERM_CODE,
        SFRSTCR.SFRSTCR_RSTS_CODE,
        SFRSTCR.SFRSTCR_CREDIT_HR,
        SSBSECT.SSBSECT_TERM_CODE,
        SSBSECT.SSBSECT_SUBJ_CODE,
        SSBSECT.SSBSECT_CRSE_NUMB,
        SSBSECT.SSBSECT_CRN,
        SSBSECT.SSBSECT_SICAS_CAMP_COURSE_ID,
        SSBSECT.SSBSECT_SEQ_NUMB,
        SSBSECT.SSBSECT_CAMP_CODE,
        SSBSECT.SSBSECT_GMOD_CODE,
        SCBCRSE.SCBCRSE_TITLE,
        SCBCRSE.SCBCRSE_EFF_TERM,
        SHRTCKN.SHRTCKN_ACTIVITY_DATE,
        SIRDPCL.SIRDPCL_PIDM,
/*        SIRASGN.SIRASGN_PIDM,
        SIRDPCL.SIRDPCL_PIDM,
        case
          when F_FORMAT_NAME(SIRASGN.SIRASGN_PIDM, 'LF30') = 'NAME NOT FOUND FOR PIDM: ' then 'INSTRUCTOR NOT FOUND'
            else F_FORMAT_NAME(SIRASGN.SIRASGN_PIDM, 'LF30') end as SIRASGN_INSTR_NAME
*/
        case
          when F_FORMAT_NAME(SIRDPCL.SIRDPCL_PIDM, 'LF30') = 'NAME NOT FOUND FOR PIDM: ' then 'INSTRUCTOR NOT FOUND'
            else F_FORMAT_NAME(SIRDPCL.SIRDPCL_PIDM, 'LF30') end as SIRDPCL_INSTR_NAME

    from
        SFRSTCR SFRSTCR

        inner join SSBSECT SSBSECT on SSBSECT.SSBSECT_CRN = SFRSTCR.SFRSTCR_CRN
            and SSBSECT.SSBSECT_TERM_CODE = SFRSTCR.SFRSTCR_TERM_CODE

        left outer join SCBCRSE SCBCRSE on  SSBSECT.SSBSECT_SUBJ_CODE = SCBCRSE.SCBCRSE_SUBJ_CODE
            and SCBCRSE.SCBCRSE_CRSE_NUMB = SSBSECT.SSBSECT_CRSE_NUMB

        left outer join SHRTCKN SHRTCKN on SHRTCKN.SHRTCKN_PIDM = SFRSTCR.SFRSTCR_PIDM
            and SHRTCKN.SHRTCKN_TERM_CODE = SFRSTCR.SFRSTCR_TERM_CODE
            and SHRTCKN.SHRTCKN_CRN = SFRSTCR.SFRSTCR_CRN

        left outer join SIRASGN SIRASGN ON SIRASGN.SIRASGN_TERM_CODE = SSBSECT.SSBSECT_TERM_CODE
            and SIRASGN.SIRASGN_CRN = SSBSECT.SSBSECT_CRN
            and SIRASGN.SIRASGN_CATEGORY = 01

        left outer join SIRDPCL SIRDPCL ON SIRDPCL.SIRDPCL_PIDM = SIRASGN.SIRASGN_PIDM

    where
        SFRSTCR.SFRSTCR_RSTS_CODE in ('RE')

    )

select
    STVTERM.STVTERM_DESC as TERM_DESC,
    SPRIDEN_ID as Banner_ID,
    SPRIDEN.SPRIDEN_LEGAL_NAME as Student_Name,
    SPBPERS.SPBPERS_PREF_FIRST_NAME Pref_Fname,
    SGBSTDN.SGBSTDN_CLASS_CODE as Class,
    SGBSTDN.SGBSTDN_DEPT_CODE as  Department,
    SGBSTDN.SGBSTDN_PROGRAM_1 as Program,
    SGBSTDN.SGBSTDN_MAJR_DESC as Program_Of_Study,
    SGBSTDN.SGBSTDN_DEGC_CODE_1 as Degree,
    SFRSTCR.SFRSTCR_RSTS_CODE as RSTS,
    SFRSTCR.SSBSECT_SICAS_CAMP_COURSE_ID as Course_Key,
    SFRSTCR.SSBSECT_CRN as CRN,
    SFRSTCR.SIRDPCL_INSTR_NAME as Primary_Instr,
    --SFRSTCR.SIRASGN_INSTR_NAME as Primary_Instr,
    SFRSTCR.SSBSECT_CAMP_CODE as Campus,
    SFRSTCR.SCBCRSE_TITLE as Title,
    SFRSTCR.SFRSTCR_CREDIT_HR as Credit_Hours,
    /*
    case
      when SSBSECT_GMOD_CODE = 'Y' then SSBSECT_GMOD_CODE
        else null
          end as SU_Course,
    */
    SFRSTCR.SSBSECT_SUBJ_CODE as Subj_Code,
    SFRSTCR.SSBSECT_CRSE_NUMB as Crse_Numb,
    SSBSECT_SEQ_NUMB as Seq_Numb,
    SPRIDEN.GORADID_SU_ID as SUID,
    GOREMAL.GOREMAL_EMAIL_ADDRESS as SU_EMAIL,
    SPRIDEN_SEARCH_FIRST_NAME,
    SPRIDEN_SEARCH_LAST_NAME,
    SPRIDEN_SEARCH_MI

from
    STVTERM STVTERM

    left outer join SPAIDEN SPRIDEN on f_registered_this_term(SPRIDEN.SPRIDEN_PIDM, STVTERM.STVTERM_CODE) = 'Y'
    left outer join SOREMAL GOREMAL on GOREMAL.GOREMAL_PIDM = SPRIDEN.SPRIDEN_PIDM
    left outer join SGASTDN SGBSTDN on SGBSTDN.SGBSTDN_PIDM = SPRIDEN.SPRIDEN_PIDM
    left outer join SPAPERS SPBPERS on SPBPERS.SPBPERS_PIDM = SPRIDEN.SPRIDEN_PIDM
    left outer join SFAREGS SFRSTCR on SFRSTCR.SFRSTCR_PIDM = SPRIDEN.SPRIDEN_PIDM

where
    STVTERM.STVTERM_CODE = :select_term_code.STVTERM_CODE
    and SGBSTDN.SGBSTDN_TERM_CODE_EFF = fy_sgbstdn_eff_term(SGBSTDN.SGBSTDN_PIDM, STVTERM.STVTERM_CODE)
    and SGBSTDN.SGBSTDN_STST_CODE = 'AS'
    and SFRSTCR.SFRSTCR_TERM_CODE = STVTERM.STVTERM_CODE
    and SFRSTCR.SFRSTCR_RSTS_CODE = 'RE'
    and SCBCRSE_EFF_TERM = (select max(SCBCRSE_EFF_TERM)
                           from   SCBCRSE SCBCRSEX
                           where  SCBCRSEX.SCBCRSE_SUBJ_CODE = SFRSTCR.SSBSECT_SUBJ_CODE
                           and    SCBCRSEX.SCBCRSE_CRSE_NUMB = SFRSTCR.SSBSECT_CRSE_NUMB
                           and    SCBCRSEX.SCBCRSE_EFF_TERM <= STVTERM.STVTERM_CODE)

--$addfilter

--$beginorder

order by
    /*
    SFRSTCR.SSBSECT_SUBJ_CODE,
    SFRSTCR.SSBSECT_SICAS_CAMP_COURSE_ID,
    */
    SPRIDEN.SPRIDEN_SEARCH_LAST_NAME,
    SPRIDEN.SPRIDEN_SEARCH_FIRST_NAME

--$endorder

--select unique sfrstcr_crn from sfrstcr where sfrstcr_term_code = 202340
