with SOREMAL as
(
    select
        GOREMAL.GOREMAL_PIDM as GOREMAL_PIDM,
        GOREMAL.GOREMAL_EMAL_CODE as GOREMAL_EMAL_CODE,
        GOREMAL.GOREMAL_EMAIL_ADDRESS as GOREMAL_EMAIL_ADDRESS,
        GOREMAL.GOREMAL_STATUS_IND as GOREMAL_STATUS_IND,
        GOREMAL.GOREMAL_PREFERRED_IND as GOREMAL_PREFFERED_IND,
        GORADID.GORADID_PIDM as GORADID_PIDM,
        GORADID.GORADID_ADDITIONAL_ID as GORADID_ADDITIONAL_ID,
        GORADID.GORADID_ADID_CODE as GORADID_ADID_CODE,
        GOBTPAC_EXTERNAL_USER as GOBTPAC_EXTERNAL_USER --esfid

    from
        GOREMAL GOREMAL

        left outer join GORADID GORADID on GORADID.GORADID_PIDM = GOREMAL.GOREMAL_PIDM
             and GORADID.GORADID_ADID_CODE = 'SUID'
        left outer join GOBUMAP GOBUMAP on GOBUMAP.GOBUMAP_PIDM = GOREMAL.GOREMAL_PIDM
        left outer join GOBTPAC GOBTPAC on GOBTPAC.GOBTPAC_PIDM = GOREMAL.GOREMAL_PIDM

    where
        GOREMAL.GOREMAL_EMAL_CODE = 'SU'
        and GOREMAL.GOREMAL_STATUS_IND = 'A'
        and GOREMAL.GOREMAL_PREFERRED_IND = 'Y'
        and GORADID.GORADID_ADID_CODE = 'SUID'
    ),

SIRASGQ as
(
    select
        SIRASGN_TERM_CODE,
        SIRASGN_CRN,
        SIRASGN_PIDM,
        SIRDPCL.SIRDPCL_PIDM,
        SIRDPCL.SIRDPCL_TERM_CODE_EFF,
        SIRDPCL.SIRDPCL_COLL_CODE,
        SIRDPCL.SIRDPCL_DEPT_CODE,
        SIRASGN_PRIMARY_IND,
        SSBSECT_TERM_CODE,
        SSBSECT_SICAS_CAMP_COURSE_ID,
        SSBSECT_CRN,
        SSBSECT_PTRM_CODE,
        SSBSECT_SUBJ_CODE,
        SSBSECT_CRSE_NUMB,
        SSBSECT_SEQ_NUMB,
        SSBSECT_ENRL,
        SSBSECT_SEATS_AVAIL,
        SSBSECT_TOT_CREDIT_HRS,
        GOREMAL_EMAIL_ADDRESS,
        f_format_name(SIRDPCL_PIDM, 'LF30') as SIRDPCL_NAME,
        case
          when SIRDPCL_DEPT_CODE is null then f_get_desc_fnc('STVDEPT', SCBCRSE_DEPT_CODE, 30)
            else f_get_desc_fnc('STVDEPT', SIRDPCL_DEPT_CODE, 30)
              end as SIRDPCL_DEPT_DESC

    FROM
        SSBSECT SSBSECT
        LEFT OUTER JOIN SIRASGN SIRASGN ON SIRASGN_TERM_CODE = SSBSECT_TERM_CODE
             AND SIRASGN.SIRASGN_CRN = SSBSECT.SSBSECT_CRN
             AND SIRASGN_PRIMARY_IND = 'Y'
        LEFT OUTER JOIN SIRDPCL SIRDPCL ON SIRDPCL_PIDM = SIRASGN_PIDM
             AND SIRDPCL_SURROGATE_ID = (SELECT MAX(SIRDPCL_SURROGATE_ID)
                                        FROM SIRDPCL X
                                        WHERE X.SIRDPCL_PIDM = SIRDPCL.SIRDPCL_PIDM)
        LEFT OUTER JOIN GOREMAL GOREMAL ON GOREMAL.GOREMAL_PIDM = SIRDPCL_PIDM
             AND GOREMAL.GOREMAL_EMAL_CODE = 'ESF'
             AND GOREMAL.GOREMAL_STATUS_IND = 'A'
             AND GOREMAL.GOREMAL_PREFERRED_IND = 'Y'
        LEFT OUTER JOIN SCBCRSE SCBCRSE ON SSBSECT_SUBJ_CODE = SCBCRSE.SCBCRSE_SUBJ_CODE
            and SCBCRSE.SCBCRSE_CRSE_NUMB = SSBSECT_CRSE_NUMB

    WHERE
        SSBSECT_TERM_CODE = :select_term_code.STVTERM_CODE
        AND SIRDPCL_DEPT_CODE <> 'SU'

    ),

SFAREGS AS
(
    select
        SFRSTCR_PIDM,
        SFRSTCR_CRN,
        SFRSTCR_TERM_CODE,
        SSBSECT_TERM_CODE,
        SSBSECT_SICAS_CAMP_COURSE_ID,
        SSBSECT_CRN,
        SSBSECT_PTRM_CODE,
        SSBSECT_SUBJ_CODE,
        SSBSECT_CRSE_NUMB,
        SSBSECT_SEQ_NUMB,
        SSBSECT_ENRL,
        SSBSECT_SEATS_AVAIL,
        SSBSECT_TOT_CREDIT_HRS

    FROM
        SFRSTCR SFRSTCR
        LEFT OUTER JOIN SSBSECT SSBSECT ON SSBSECT.SSBSECT_TERM_CODE = SFRSTCR.SFRSTCR_TERM_CODE
             AND SSBSECT.SSBSECT_CRN = SFRSTCR.SFRSTCR_CRN

        LEFT OUTER JOIN SCBCRSE SCBCRSE ON SSBSECT_SUBJ_CODE = SCBCRSE.SCBCRSE_SUBJ_CODE
             AND SCBCRSE.SCBCRSE_CRSE_NUMB = SSBSECT_CRSE_NUMB

    WHERE
        SFRSTCR.SFRSTCR_RSTS_CODE IN ('RE', 'RW')
    ),

VIEW_3 AS
(
    select
        SIRASGN.SIRASGN_PIDM,
        --SIRDPCL.SIRDPCL_PIDM,
        SIRDPCL_NAME,
        SIRDPCL_DEPT_DESC,
        SIRASGN_PRIMARY_IND as Primary_Instr,
        GOREMAL.GOREMAL_EMAIL_ADDRESS as Instr_Email,
        SSBSECT.SSBSECT_TERM_CODE as Term_Code,
        SSBSECT.SSBSECT_SICAS_CAMP_COURSE_ID as COURSE_ID,
        SSBSECT.SSBSECT_CRN,
        SSBSECT.SSBSECT_PTRM_CODE,
        SSBSECT.SSBSECT_SUBJ_CODE,
        SSBSECT.SSBSECT_CRSE_NUMB,
        SSBSECT.SSBSECT_SEQ_NUMB,
        SSBSECT.SSBSECT_ENRL,
        SSBSECT.SSBSECT_SEATS_AVAIL,
        SSBSECT.SSBSECT_TOT_CREDIT_HRS,
        SSRMEET_TERM_CODE,
        SSRMEET_CRN,
        SSRMEET_BEGIN_TIME,
        SSRMEET_END_TIME,
        SSRMEET_BLDG_CODE,
        SSRMEET_ROOM_CODE,
        SSRMEET_START_DATE,
        SSRMEET_END_DATE,
        SSRMEET_MON_DAY,
        SSRMEET_TUE_DAY,
        SSRMEET_WED_DAY,
        SSRMEET_THU_DAY,
        SSRMEET_FRI_DAY,
        SSRMEET_SAT_DAY,
        SSRMEET_CREDIT_HR_SESS,
        SSRMEET_MEET_NO,
        SSRMEET_HRS_WEEK

    FROM
        STVTERM STVTERM
        LEFT OUTER JOIN SSBSECT SSBSECT ON SSBSECT_TERM_CODE = STVTERM.STVTERM_CODE
        LEFT OUTER JOIN SIRASGQ SIRASGN ON SIRASGN_TERM_CODE = STVTERM.STVTERM_CODE
             AND SIRASGN.SIRASGN_CRN = SSBSECT.SSBSECT_CRN
/*
        LEFT OUTER JOIN SIRDPCL SIRDPCL ON SIRDPCL_PIDM = SIRASGN_PIDM
             AND SIRDPCL_SURROGATE_ID = (SELECT MAX(SIRDPCL_SURROGATE_ID)
                                        FROM SIRDPCL X
                                        WHERE X.SIRDPCL_PIDM = SIRDPCL.SIRDPCL_PIDM)
                                        */
        LEFT OUTER JOIN GOREMAL GOREMAL ON GOREMAL.GOREMAL_PIDM = SIRDPCL_PIDM
             AND GOREMAL.GOREMAL_EMAL_CODE = 'ESF'
             AND GOREMAL.GOREMAL_STATUS_IND = 'A'
             AND GOREMAL.GOREMAL_PREFERRED_IND = 'Y'

        LEFT OUTER JOIN SCBCRSE SCBCRSE ON SSBSECT.SSBSECT_SUBJ_CODE = SCBCRSE.SCBCRSE_SUBJ_CODE
            and SCBCRSE.SCBCRSE_CRSE_NUMB = SSBSECT.SSBSECT_CRSE_NUMB
        LEFT OUTER JOIN SSRMEET SSRMEET ON SSRMEET.SSRMEET_TERM_CODE = SSBSECT.SSBSECT_TERM_CODE
             AND SSRMEET.SSRMEET_CRN = SSBSECT.SSBSECT_CRN

    WHERE
        STVTERM_CODE = :select_term_code.STVTERM_CODE
        --STVTERM.STVTERM_ACYR_CODE = :select_term_code.AIDY_CODE
        AND SIRDPCL_DEPT_CODE <> 'SU'
        AND SSBSECT.SSBSECT_TERM_CODE = STVTERM_CODE
        --$addfilter
        --$beginorder
    ORDER BY
        SIRDPCL_NAME,
        COURSE_ID,
        SSBSECT_CRN
        --$endorder
    )

select
        V3.*
from
        VIEW_3 V3
where
NULL IS NULL
        /*
        AND STVTERM_SURROGATE_ID = (SELECT min(STVTERM_SURROGATE_ID)
                                   FROM STVTERM S
                                   WHERE S.STVTERM_ACYR_CODE = STVTERM.STVTERM_ACYR_CODE)
        */

--$addfilter