-- Min Term Selection
select TRIM(STVTERM_CODE) AS CODE, STVTERM_DESC AS DESCR
FROM STVTERM
WHERE STVTERM_START_DATE > SYSDATE -230 AND STVTERM_START_DATE < SYSDATE + 230
--and substr(stvterm_code,5,1) in ('1','3','5')
ORDER BY STVTERM_CODE DESC

-- Max Term Selection
select TRIM(STVTERM_CODE) AS CODE, STVTERM_DESC AS DESCR
FROM STVTERM
WHERE STVTERM_START_DATE > SYSDATE - 230 AND STVTERM_START_DATE < SYSDATE + 230
--and substr(stvterm_code,5,1) in ('1','3','5')
ORDER BY STVTERM_CODE DESC

-- Student Type
SELECT STVSTYP_CODE AS STYP, STVSTYP_DESC AS DESCR FROM STVSTYP
WHERE
(CASE WHEN :chkNormalSTYP <> 1 THEN 1
      WHEN :chkNormalSTYP = 1 THEN CASE WHEN STVSTYP_CODE IN ('F','T','N','X') THEN 1 ELSE 0 END
      ELSE 1 END) = 1
ORDER BY STVSTYP_CODE

--Decision Code
SELECT * FROM
(select STVAPDC_CODE AS APDC, STVAPDC_DESC AS DESCR from STVAPDC
UNION
SELECT 'AX' AS APDC, 'No Appl or Decision' as DESCR from DUAL
)
WHERE
(CASE WHEN :chkNormalAPDC <> 1 THEN 1
      WHEN :chkNormalAPDC = 1 THEN CASE WHEN APDC IN ('AC','AP','AX','CF','QA') THEN 1 ELSE 0 END
      ELSE 1 END) = 1
ORDER BY APDC