-- term selection
select TRIM(STVTERM_CODE) AS CODE, STVTERM_DESC AS TERM_DESCRIPTION
FROM STVTERM
WHERE STVTERM_CODE >= '202110' AND STVTERM_START_DATE < SYSDATE + 180
and substr(stvterm_code,5,1) in ('1','2','3','4')
ORDER BY STVTERM_CODE DESC

-- dept selection
select STVDEPT_CODE AS DEPT, STVDEPT_DESC AS DEPT_DESCRIPTION
from stvdept
WHERE STVDEPT_CODE NOT IN ('0000','BIOC','CHEM','ENSC','LIB','SU')
AND STVDEPT_DESC <> 'DO NOT USE'
ORDER BY STVDEPT_CODE