WITH qMain AS (select distinct nvl(SHBTATC.SHBTATC_SBGI_CODE, '0') AS "SHBTATC_SBGI_CODE",
                        nvl(SHBTATC.SHBTATC_TLVL_CODE, '0')AS "SHBTATC_TLVL_CODE",
                        nvl(SHBTATC.SHBTATC_SUBJ_CODE_TRNS, '0')AS "SHBTATC_SUBJ_CODE_TRNS",
                        nvl(SHBTATC.SHBTATC_CRSE_NUMB_TRNS, '0')AS "SHBTATC_CRSE_NUMB_TRNS",
                        SHRTCAT.SHRTCAT_ATTR_CDE || ' - ' || SHRTCAT.SHRTCAT_ATTR_DESC AS "SHRTCAT_ATTR",
                        SHRTRAT.SHRTRAT_ATTR_CODE || ' - ' || STVATTR.STVATTR_DESC "SHRTRAT_ATTR",
                        nvl(SHBTATC.SHBTATC_TERM_CODE_EFF_TRNS, '0')AS "SHBTATC_TERM_CODE_EFF_TRNS",
                        nvl(SHBTATC.SHBTATC_ACTIVITY_DATE, null)AS "SHBTATC_ACTIVITY_DATE",
                        nvl(SHBTATC.SHBTATC_TRNS_TITLE, '0')AS "SHBTATC_TRNS_TITLE",
                        nvl(SHBTATC.SHBTATC_TRNS_LOW_HRS, '0')AS "SHBTATC_TRNS_LOW_HRS",
                        nvl(SHBTATC.SHBTATC_TRNS_HIGH_HRS, '0')AS "SHBTATC_TRNS_HIGH_HRS",
                        nvl(SHBTATC.SHBTATC_TRNS_REVIEW_IND, '0')AS "SHBTATC_TRNS_REVIEW_IND",
                        nvl(SHBTATC.SHBTATC_TAST_CODE, '0')AS "SHBTATC_TAST_CODE",
                        nvl(SHBTATC.SHBTATC_TRNS_CATALOG, '0')AS "SHBTATC_TRNS_CATALOG",
                        nvl(SHBTATC.SHBTATC_TGRD_CODE_MIN, '0')AS "SHBTATC_TGRD_CODE_MIN",
                        nvl(SHBTATC.SHBTATC_GROUP, '0')AS "SHBTATC_GROUP",
                        nvl(SHBTATC.SHBTATC_GROUP_PRIMARY_IND, '0')AS "SHBTATC_GROUP_PRIMARY_IND",
                        nvl(SHBTATC.SHBTATC_USER_ID, '0')AS "SHBTATC_USER_ID",
                        nvl(SHBTATC.SHBTATC_DATA_ORIGIN, '0')AS "SHBTATC_DATA_ORIGIN",
                        nvl(SHBTATC.SHBTATC_PROTECT_IND, '0')AS "SHBTATC_PROTECT_IND",
                        nvl(SHRTATC.SHRTATC_CONNECTOR, '0')AS "SHRTATC_CONNECTOR",
                        nvl(SHRTATC.SHRTATC_INST_LPAREN_CONN, 'EMPTY')AS "SHRTATC_INST_LPAREN_CONN",
                        nvl(SHRTATC.SHRTATC_SUBJ_CODE_INST,0) AS "SHRTATC_SUBJ_CODE_INST",
                        nvl(SHRTATC.SHRTATC_CRSE_NUMB_INST,0) AS "SHRTATC_CRSE_NUMB_INST",
                        nvl(SHRTATC.SHRTATC_INST_TITLE, '0')AS "SHRTATC_INST_TITLE",
                        nvl(SHRTATC.SHRTATC_INST_CREDITS_USED, '0')AS "SHRTATC_INST_CREDITS_USED",
                        nvl(SHRTATC.SHRTATC_INST_RPAREN, '0')AS "SHRTATC_INST_RPAREN",
                        nvl(SHRICMT.SHRICMT_TEXT, '0')AS "SHRICMT_TEXT",
                        nvl(SHRTATC.SHRTATC_SEQNO, '0')AS "SHRTATC_SEQNO"
          from SATURN.SHBTATC SHBTATC,
               SATURN.SHRTATC SHRTATC,
               SATURN.SHRTRAT SHRTRAT,
               SATURN.STVATTR STVATTR,
               SATURN.SHRTCAT SHRTCAT,
               SATURN.SHRICMT SHRICMT
         where SHBTATC.SHBTATC_SBGI_CODE = SHRTATC.SHRTATC_SBGI_CODE (+)
           and SHBTATC.SHBTATC_SUBJ_CODE_TRNS = SHRTATC.SHRTATC_SUBJ_CODE_TRNS (+)
           and SHBTATC.SHBTATC_CRSE_NUMB_TRNS = SHRTATC.SHRTATC_CRSE_NUMB_TRNS (+)
           and SHBTATC.SHBTATC_SBGI_CODE = SHRTRAT.SHRTRAT_SBGI_CODE(+)
           and SHBTATC.SHBTATC_SUBJ_CODE_TRNS = SHRTRAT.SHRTRAT_SUBJ_CODE_TRNS(+)
           and SHBTATC.SHBTATC_CRSE_NUMB_TRNS = SHRTRAT.SHRTRAT_CRSE_NUMB_TRNS(+)
           and SHRTATC.SHRTATC_SUBJ_CODE_INST = SHRTRAT.SHRTRAT_SUBJ_CODE_INST(+)
           and SHRTATC.SHRTATC_CRSE_NUMB_INST = SHRTRAT.SHRTRAT_CRSE_NUMB_INST(+)
           and SHRTRAT.SHRTRAT_ATTR_CODE = STVATTR.STVATTR_CODE
           --and SHRTATC.SHRTATC_SEQNO = SHRTRAT.SHRTRAT_SHRTATC_SEQNO(+)
           and SHRTATC.SHRTATC_SEQNO = SHRICMT.SHRICMT_SHRTATC_SEQNO(+)
           and SHBTATC.SHBTATC_SBGI_CODE = SHRICMT.SHRICMT_SBGI_CODE(+)
           and SHBTATC.SHBTATC_SUBJ_CODE_TRNS = SHRICMT.SHRICMT_SUBJ_CODE_TRNS(+)
           and SHBTATC.SHBTATC_CRSE_NUMB_TRNS = SHRICMT.SHRICMT_CRSE_NUMB_TRNS(+)
           and SHRTATC.SHRTATC_SUBJ_CODE_INST = SHRICMT.SHRICMT_SUBJ_CODE_INST(+)
           and SHRTATC.SHRTATC_CRSE_NUMB_INST = SHRICMT.SHRICMT_CRSE_NUMB_INST(+)
           and SHBTATC.SHBTATC_SBGI_CODE = SHRTCAT.SHRTCAT_SBGI_CODE(+)
           and SHBTATC.SHBTATC_SUBJ_CODE_TRNS = SHRTCAT.SHRTCAT_SUBJ_CDE_TRNS(+)
           and SHBTATC.SHBTATC_CRSE_NUMB_TRNS = SHRTCAT.SHRTCAT_CRSE_NUMB_TRNS(+)
           and SHBTATC.SHBTATC_TERM_CODE_EFF_TRNS = (select max(a.SHBTATC_TERM_CODE_EFF_TRNS)
                                                       from shbtatc a
                                                      where SHBTATC.SHBTATC_SBGI_CODE = a.SHBTATC_SBGI_CODE (+)
                                                        and SHBTATC.SHBTATC_SUBJ_CODE_TRNS = a.SHBTATC_SUBJ_CODE_TRNS (+)
                                                        and SHBTATC.SHBTATC_CRSE_NUMB_TRNS = a.SHBTATC_CRSE_NUMB_TRNS (+))

           and SHBTATC.SHBTATC_SBGI_CODE = :main_MC_sbgi.STVSBGI_CODE),

qSecond AS ((select SHBTATC_SBGI_CODE,
       SHBTATC_TLVL_CODE,
       SHBTATC_SUBJ_CODE_TRNS,
       SHBTATC_CRSE_NUMB_TRNS,
      --LISTAGG(((SHRTCAT.SHRTCAT_ATTR_CDE || ' - ' || SHRTCAT.SHRTCAT_ATTR_DESC)), ' ,') WITHIN GROUP(ORDER BY SHRTCAT.SHRTCAT_ATTR_CDE) "SHRTCAT_ATTR",
       --SHRTCAT_ATTR,
       LISTAGG(SHRTCAT_ATTR, ' ,') WITHIN GROUP (ORDER BY SHRTCAT_ATTR) AS shrtcat_listagg,
       SHRTRAT_ATTR,
       SHBTATC_TERM_CODE_EFF_TRNS,
       SHBTATC_ACTIVITY_DATE,
       SHBTATC_TRNS_TITLE,
       SHBTATC_TRNS_LOW_HRS,
       SHBTATC_TRNS_HIGH_HRS,
       SHBTATC_TRNS_REVIEW_IND,
       SHBTATC_TAST_CODE,
       SHBTATC_TRNS_CATALOG,
       SHBTATC_TGRD_CODE_MIN,
       SHBTATC_GROUP,
       SHBTATC_GROUP_PRIMARY_IND,
       SHBTATC_USER_ID,
       SHBTATC_DATA_ORIGIN,
       SHBTATC_PROTECT_IND,
       SHRTATC_CONNECTOR,
       SHRTATC_INST_LPAREN_CONN,
       SHRTATC_SUBJ_CODE_INST,
       SHRTATC_CRSE_NUMB_INST,
       SHRTATC_INST_TITLE,
       SHRTATC_INST_CREDITS_USED,
       SHRTATC_INST_RPAREN,
       SHRICMT_TEXT,
       SHRTATC_SEQNO
from qMain

group by SHBTATC_SBGI_CODE,
       SHBTATC_TLVL_CODE,
       SHBTATC_SUBJ_CODE_TRNS,
       SHBTATC_CRSE_NUMB_TRNS,
       --SHRTCAT_ATTR,
       --LISTAGG(SHRTCAT_ATTR, ' ,') WITHIN GROUP (ORDER BY SHRTCAT_ATTR) AS shrtcat_listagg,
       SHRTRAT_ATTR,
       SHBTATC_TERM_CODE_EFF_TRNS,
       SHBTATC_ACTIVITY_DATE,
       SHBTATC_TRNS_TITLE,
       SHBTATC_TRNS_LOW_HRS,
       SHBTATC_TRNS_HIGH_HRS,
       SHBTATC_TRNS_REVIEW_IND,
       SHBTATC_TAST_CODE,
       SHBTATC_TRNS_CATALOG,
       SHBTATC_TGRD_CODE_MIN,
       SHBTATC_GROUP,
       SHBTATC_GROUP_PRIMARY_IND,
       SHBTATC_USER_ID,
       SHBTATC_DATA_ORIGIN,
       SHBTATC_PROTECT_IND,
       SHRTATC_CONNECTOR,
       SHRTATC_INST_LPAREN_CONN,
       SHRTATC_SUBJ_CODE_INST,
       SHRTATC_CRSE_NUMB_INST,
       SHRTATC_INST_TITLE,
       SHRTATC_INST_CREDITS_USED,
       SHRTATC_INST_RPAREN,
       SHRICMT_TEXT,
       SHRTATC_SEQNO)),

qThird AS
(select qSecond.SHBTATC_SBGI_CODE,
       qSecond.SHBTATC_TLVL_CODE,
       qSecond.SHBTATC_SUBJ_CODE_TRNS,
       qSecond.SHBTATC_CRSE_NUMB_TRNS,
       qSecond.shrtcat_listagg,
       LISTAGG(qSecond.SHRTRAT_ATTR, ' ,') WITHIN GROUP (ORDER BY qSecond.SHRTRAT_ATTR) AS shrtrat_listagg,
       SHBTATC_TERM_CODE_EFF_TRNS,
       SHBTATC_ACTIVITY_DATE,
       SHBTATC_TRNS_TITLE,
       SHBTATC_TRNS_LOW_HRS,
       SHBTATC_TRNS_HIGH_HRS,
       SHBTATC_TRNS_REVIEW_IND,
       SHBTATC_TAST_CODE,
       SHBTATC_TRNS_CATALOG,
       SHBTATC_TGRD_CODE_MIN,
       SHBTATC_GROUP,
       SHBTATC_GROUP_PRIMARY_IND,
       SHBTATC_USER_ID,
       SHBTATC_DATA_ORIGIN,
       SHBTATC_PROTECT_IND,
       decode(SHRTATC_CONNECTOR,'A','AND','O','OR','0','NONE') AS "SHRTATC_CONNECTOR",
       SHRTATC_INST_LPAREN_CONN,
       SHRTATC_SUBJ_CODE_INST,
       SHRTATC_CRSE_NUMB_INST,
       SHRTATC_INST_TITLE,
       SHRTATC_INST_CREDITS_USED,
       SHRTATC_INST_RPAREN,
       SHRICMT_TEXT,
       SHRTATC_SEQNO

from   qSecond
where  SHBTATC_TRNS_REVIEW_IND <> CASE WHEN :main_CB_NoCourseEquivalents = 'Y' THEN 'Y'
       ELSE 'NOTHING' end
and    SHBTATC_TERM_CODE_EFF_TRNS <= :main_MC_TermCode.Code
and    :main_BT_RunResults is not null

group by qSecond.SHBTATC_SBGI_CODE,
       qSecond.SHBTATC_TLVL_CODE,
       qSecond.SHBTATC_SUBJ_CODE_TRNS,
       qSecond.SHBTATC_CRSE_NUMB_TRNS,
       qSecond.shrtcat_listagg,
       SHBTATC_TERM_CODE_EFF_TRNS,
       SHBTATC_ACTIVITY_DATE,
       SHBTATC_TRNS_TITLE,
       SHBTATC_TRNS_LOW_HRS,
       SHBTATC_TRNS_HIGH_HRS,
       SHBTATC_TRNS_REVIEW_IND,
       SHBTATC_TAST_CODE,
       SHBTATC_TRNS_CATALOG,
       SHBTATC_TGRD_CODE_MIN,
       SHBTATC_GROUP,
       SHBTATC_GROUP_PRIMARY_IND,
       SHBTATC_USER_ID,
       SHBTATC_DATA_ORIGIN,
       SHBTATC_PROTECT_IND,
       SHRTATC_CONNECTOR,
       SHRTATC_INST_LPAREN_CONN,
       SHRTATC_SUBJ_CODE_INST,
       SHRTATC_CRSE_NUMB_INST,
       SHRTATC_INST_TITLE,
       SHRTATC_INST_CREDITS_USED,
       SHRTATC_INST_RPAREN,
       SHRICMT_TEXT,
       SHRTATC_SEQNO)

select * from qThird