/*
program notes:
SFAREGS = sfrstcr_term_code is not defined.
SSASECT = ssbsect_term_code is not defined.
SSRMEET = ssrmeet_term_code is not defined.
*/
WITH SPAIDEN as
(
  SELECT
      SPRIDEN.SPRIDEN_PIDM,
      SPRIDEN.SPRIDEN_ID,
      SPRIDEN.SPRIDEN_LAST_NAME,
      SPRIDEN.SPRIDEN_FIRST_NAME,
      SPRIDEN.SPRIDEN_MI,
      SPRIDEN.SPRIDEN_CHANGE_IND,
      SPRIDEN.SPRIDEN_ENTITY_IND,
      SPRIDEN.SPRIDEN_SEARCH_LAST_NAME,
      SPRIDEN.SPRIDEN_SEARCH_FIRST_NAME,
      SPRIDEN.SPRIDEN_SEARCH_MI,
      SPRIDEN.SPRIDEN_SURROGATE_ID,
      SPRIDEN.SPRIDEN_VERSION,
      f_format_name(SPRIDEN.SPRIDEN_PIDM, 'LFMI') as SPRIDEN_LEGAL_NAME

  FROM
      SPRIDEN SPRIDEN

  WHERE
      SPRIDEN.SPRIDEN_NTYP_CODE is NULL
      AND SPRIDEN.SPRIDEN_CHANGE_IND is NULL
  ),

TUIADDR as
(
  SELECT
      SPRADDR.SPRADDR_PIDM,
      SPRADDR.SPRADDR_ATYP_CODE,
      SPRADDR.SPRADDR_SEQNO,
      SPRADDR.SPRADDR_FROM_DATE,
      SPRADDR.SPRADDR_TO_DATE,
      SPRADDR.SPRADDR_STREET_LINE1,
      SPRADDR.SPRADDR_STREET_LINE2,
      SPRADDR.SPRADDR_STREET_LINE3,
      SPRADDR.SPRADDR_CITY,
      SPRADDR.SPRADDR_STAT_CODE,
      SPRADDR.SPRADDR_ZIP,
      SPRADDR.SPRADDR_CNTY_CODE,
      SPRADDR.SPRADDR_SURROGATE_ID,
      f_get_desc_fnc('STVATYP', SPRADDR.SPRADDR_ATYP_CODE, 30) as SPRADDR_ATYP_DESC,
      f_get_desc_fnc('STVCNTY', SPRADDR.SPRADDR_CNTY_CODE, 30) as SPRADDR_CNTY_DESC

  FROM
      SPRADDR SPRADDR

  WHERE
      SPRADDR.SPRADDR_ATYP_CODE IN ('MA','PA','PR')
      AND SPRADDR.SPRADDR_STATUS_IND IS NULL
      AND SPRADDR.SPRADDR_VERSION = (SELECT MAX(SPRADDR_VERSION)
                                    FROM   SPRADDR ADDR
                                    WHERE  ADDR.SPRADDR_PIDM = SPRADDR.SPRADDR_PIDM
                                    AND    ADDR.SPRADDR_ATYP_CODE IN ('MA','PA','PR')
                                    AND    ADDR.SPRADDR_STATUS_IND IS NULL)
/*
      AND SPRADDR.SPRADDR_SURROGATE_ID = (SELECT MAX(SPRADDR_SURROGATE_ID)
                                         FROM    SPRADDR ADDR
                                         WHERE   ADDR.SPRADDR_PIDM = SPRADDR.SPRADDR_PIDM
                                         AND     ADDR.SPRADDR_ATYP_CODE IN ('MA','PA','PR')
                                         AND     ADDR.SPRADDR_STATUS_IND IS NULL)
*/
  ),

SPATELE as
(
  SELECT
      SPRTELE.SPRTELE_PIDM,
      SPRTELE.SPRTELE_TELE_CODE,
      SPRTELE.SPRTELE_PHONE_AREA,
      SPRTELE.SPRTELE_PHONE_NUMBER,
      SPRTELE.SPRTELE_SURROGATE_ID,
      SPRTELE.SPRTELE_VERSION,
      f_get_desc_fnc('STVTELE', SPRTELE.SPRTELE_TELE_CODE, 30) as SPRTELE_TELE_DESC

  FROM
      SPRTELE SPRTELE

  WHERE
      SPRTELE.SPRTELE_SURROGATE_ID = (SELECT MAX(SPRTELE_SURROGATE_ID)
                                     FROM    SPRTELE TELE
                                     WHERE   TELE.SPRTELE_PIDM = SPRTELE.SPRTELE_PIDM
                                     AND     TELE.SPRTELE_STATUS_IND IS NULL)
  ),

SPAEMRG AS
(
  SELECT
      SPREMRG.SPREMRG_PIDM,
      SPREMRG.SPREMRG_PRIORITY,
      SPREMRG.SPREMRG_LAST_NAME,
      SPREMRG.SPREMRG_FIRST_NAME,
      SPREMRG.SPREMRG_MI,
      SPREMRG.SPREMRG_STREET_LINE1,
      SPREMRG.SPREMRG_STREET_LINE2,
      SPREMRG.SPREMRG_STREET_LINE3,
      SPREMRG.SPREMRG_CITY,
      SPREMRG.SPREMRG_STAT_CODE,
      SPREMRG.SPREMRG_NATN_CODE,
      SPREMRG.SPREMRG_ZIP,
      SPREMRG.SPREMRG_PHONE_AREA,
      SPREMRG.SPREMRG_PHONE_NUMBER,
      SPREMRG.SPREMRG_PHONE_EXT,
      SPREMRG.SPREMRG_RELT_CODE,
      SPREMRG.SPREMRG_ACTIVITY_DATE,
      SPREMRG.SPREMRG_ATYP_CODE,
      SPREMRG.SPREMRG_HOUSE_NUMBER,
      SPREMRG.SPREMRG_STREET_LINE4,
      SPREMRG.SPREMRG_SURROGATE_ID,
      SPREMRG.SPREMRG_VERSION,
      f_get_desc_fnc('STVRELT', SPREMRG.SPREMRG_RELT_CODE, 30) as SPREMRG_RELT_DESC

  FROM
      SPREMRG SPREMRG
  ),

SPAPERS as
(
  SELECT
      SPBPERS.SPBPERS_PIDM,
      SPBPERS.SPBPERS_SSN,
      SPBPERS.SPBPERS_BIRTH_DATE,
      SPBPERS.SPBPERS_SEX,
      SPBPERS.SPBPERS_CONFID_IND,
      SPBPERS.SPBPERS_PREF_FIRST_NAME,
      SPBPERS.SPBPERS_CITZ_CODE,
      SPBPERS.SPBPERS_ETHN_CDE,
      SPBPERS.SPBPERS_SURROGATE_ID,
      SPBPERS.SPBPERS_VERSION,
      SPBPERS.SPBPERS_GNDR_CODE,
      GOBINTL.GOBINTL_PIDM,
      GOBINTL.GOBINTL_SPOUSE_IND,
      GOBINTL.GOBINTL_SIGNATURE_IND,
      GOBINTL.GOBINTL_NATN_CODE_BIRTH,
      GOBINTL.GOBINTL_SURROGATE_ID,
      GOBINTL.GOBINTL_VERSION,
      CASE
        WHEN SPBPERS_ETHN_CDE IN (2,3,4,5,6,7,9,10) THEN 'Y'
          ELSE 'N'
            END AS SPBPERS_SICAS_HISP_ORIGIN,
      CASE
        WHEN SPBPERS.SPBPERS_CITZ_CODE = 'Y' THEN 'United States'
          ELSE (SELECT STVNATN_NATION
               FROM    STVNATN
               WHERE   STVNATN_CODE = NVL(GOBINTL.GOBINTL_NATN_CODE_LEGAL, GOBINTL.GOBINTL_NATN_CODE_BIRTH))
                 END AS SPBPERS_CITZ_COUNTRY,
      F_GET_DESC_FNC('STVETHN', SPBPERS_ETHN_CDE, 30) as SPBPERS_ETHN_DESC,
      F_GET_DESC_FNC('STVNATN', GOBINTL_NATN_CODE_BIRTH, 30) as GOBINTL_BIRTH_NATN,
      ROUND(((SYSDATE - SPBPERS_BIRTH_DATE)/365), 0) as SPBPERS_AGE

    FROM
        SPBPERS SPBPERS
        LEFT OUTER JOIN GOBINTL GOBINTL ON GOBINTL.GOBINTL_PIDM = SPBPERS.SPBPERS_PIDM
    ),

GOARACE as
(
  SELECT
      GORPRAC.GORPRAC_PIDM AS GORPRAC_PIDM,
      (LISTAGG(GORPRAC.GORPRAC_RACE_CDE,', ') WITHIN GROUP (ORDER BY GORPRAC.GORPRAC_RACE_CDE)) AS GORRACE_RACE_CDE,
      (LISTAGG(GORRACE.GORRACE_DESC,', ') WITHIN GROUP (ORDER BY GORRACE.GORRACE_DESC)) AS GORRACE_DESC

  FROM
      GORPRAC GORPRAC
      LEFT OUTER JOIN GORRACE GORRACE ON GORRACE.GORRACE_RACE_CDE = GORPRAC.GORPRAC_RACE_CDE

  GROUP BY
      GORPRAC.GORPRAC_PIDM
  ),

SOREMAL as
(
  SELECT
      GOREMAL.GOREMAL_PIDM,
      GOREMAL.GOREMAL_EMAL_CODE,
      GOREMAL.GOREMAL_EMAIL_ADDRESS,
      GOREMAL.GOREMAL_STATUS_IND,
      GOREMAL.GOREMAL_PREFERRED_IND,
      GOREMAL.GOREMAL_ACTIVITY_DATE,
      GOREMAL.GOREMAL_SURROGATE_ID,
      GOREMAL.GOREMAL_VERSION,
      GORADID.GORADID_PIDM,
      GORADID.GORADID_ADDITIONAL_ID,
      GORADID.GORADID_ADID_CODE,
      GORADID.GORADID_SURROGATE_ID,
      GORADID.GORADID_VERSION,
      GOBTPAC.GOBTPAC_PIDM,
      GOBTPAC.GOBTPAC_PIN_DISABLED_IND,
      GOBTPAC.GOBTPAC_USAGE_ACCEPT_IND,
      GOBTPAC.GOBTPAC_PIN,
      GOBTPAC.GOBTPAC_PIN_EXP_DATE,
      GOBTPAC.GOBTPAC_SURROGATE_ID,
      GOBTPAC.GOBTPAC_VERSION,
      GOBTPAC.GOBTPAC_EXTERNAL_USER --esfid

  FROM
      GOREMAL GOREMAL
      LEFT OUTER JOIN GORADID GORADID ON GORADID.GORADID_PIDM = GOREMAL.GOREMAL_PIDM
           AND GORADID.GORADID_ADID_CODE = 'SUID'
      LEFT OUTER JOIN GOBUMAP GOBUMAP ON GOBUMAP.GOBUMAP_PIDM = GOREMAL.GOREMAL_PIDM
      LEFT OUTER JOIN GOBTPAC GOBTPAC ON GOBTPAC.GOBTPAC_PIDM = GOREMAL.GOREMAL_PIDM

  WHERE
      GOREMAL.GOREMAL_STATUS_IND = 'A'
      AND GOREMAL.GOREMAL_PREFERRED_IND = 'Y'
      AND GOREMAL.GOREMAL_EMAL_CODE IN ('ESF', 'SU', 'AD', 'PERS')
  ),

SGASTDN as
(
  SELECT
      SGBSTDN.SGBSTDN_PIDM,
      SGBSTDN.SGBSTDN_TERM_CODE_EFF,
      SGBSTDN.SGBSTDN_STST_CODE,
      SGBSTDN.SGBSTDN_LEVL_CODE,
      SGBSTDN.SGBSTDN_STYP_CODE,
      SGBSTDN.SGBSTDN_TERM_CODE_MATRIC,
      SGBSTDN.SGBSTDN_TERM_CODE_ADMIT,
      SGBSTDN.SGBSTDN_EXP_GRAD_DATE,
      SGBSTDN.SGBSTDN_CAMP_CODE,
      SGBSTDN.SGBSTDN_COLL_CODE_1,
      SGBSTDN.SGBSTDN_DEGC_CODE_1,
      SGBSTDN.SGBSTDN_MAJR_CODE_1,
      SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1,
      SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1_2,
      SGBSTDN.SGBSTDN_MAJR_CODE_CONC_1,
      SGBSTDN.SGBSTDN_RESD_CODE,
      SGBSTDN.SGBSTDN_ADMT_CODE,
      SGBSTDN.SGBSTDN_DEPT_CODE,
      SGBSTDN.SGBSTDN_PROGRAM_1,
      SGBSTDN.SGBSTDN_TERM_CODE_GRAD,
      SGBSTDN.SGBSTDN_ACTIVITY_DATE,
      SFRTHST.SFRTHST_PIDM,
      SFRTHST.SFRTHST_TERM_CODE,
      SFRTHST.SFRTHST_TMST_CODE,
      SFRTHST.SFRTHST_TMST_DATE,
      SFRTHST.SFRTHST_SURROGATE_ID,
      SFRTHST.SFRTHST_VERSION,
      CASE
        WHEN SFRTHST_TMST_CODE IS NULL THEN NULL
          ELSE f_Get_desc_fnc('STVTMST', SFRTHST.SFRTHST_TMST_CODE, 30)
            END as SFRTHST_TMST_DESC,
      f_class_calc_fnc(SGBSTDN.SGBSTDN_PIDM, SGBSTDN.SGBSTDN_LEVL_CODE, :select_term_code.STVTERM_CODE) as SGBSTDN_CLAS_CODE,
      f_get_desc_fnc('STVTERM',SGBSTDN.SGBSTDN_TERM_CODE_EFF, 30) as SGBSTDN_EFF_TERM_DESC,
      f_get_desc_fnc('STVSTST',SGBSTDN.SGBSTDN_STST_CODE, 30) as SGBSTDN_STST_DESC,
      f_get_desc_fnc('STVLEVL', SGBSTDN.SGBSTDN_LEVL_CODE, 30) as SGBSTDN_LEVL_DESC,
      f_get_desc_fnc('STVSTYP', SGBSTDN.SGBSTDN_STYP_CODE, 30) as SGBSTDN_STYP_DESC,
      f_get_desc_fnc('STVDEGC', SGBSTDN.SGBSTDN_DEGC_CODE_1, 30) as SGBSTDN_DEGC_DESC,
      f_get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_1, 30) as SGBSTDN_MAJR_DESC,
      f_get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1, 30) as SGBSTDN_MINR_1_DESC,
      f_get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1_2, 30) as SGBSTDN_MINR_1_2_DESC,
      f_get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_CONC_1, 30) as SGBSTDN_CONC_DESC,
      f_get_desc_fnc('STVRESD', SGBSTDN.SGBSTDN_RESD_CODE, 30) as SGBSTDN_RESD_DESC,
      f_get_desc_fnc('STVADMT', SGBSTDN.SGBSTDN_ADMT_CODE, 30) as SGBSTDN_ADMT_DESC,
      f_get_desc_fnc('STVDEPT', SGBSTDN.SGBSTDN_DEPT_CODE, 30) as SGBSTDN_DEPT_DESC,
      f_get_desc_fnc('STVTERM', SGBSTDN.SGBSTDN_TERM_CODE_MATRIC, 30) as SGBSTDN_MATRIC_TERM_DESC,
      f_get_desc_fnc('STVTERM', SGBSTDN.SGBSTDN_TERM_CODE_GRAD, 30) as SGBSTDN_GRAD_TERM_DESC,
      f_get_desc_fnc('STVCLAS', f_class_calc_fnc(SGBSTDN.SGBSTDN_PIDM,SGBSTDN.SGBSTDN_LEVL_CODE, :select_term_code.STVTERM_CODE), 30) as SGBSTDN_CLAS_DESC

  FROM
      SGBSTDN SGBSTDN
      LEFT OUTER JOIN SFRTHST SFRTHST ON SFRTHST.SFRTHST_PIDM = SGBSTDN.SGBSTDN_PIDM
           AND SFRTHST_SURROGATE_ID = (SELECT MAX(SFRTHST_SURROGATE_ID)
                                      FROM   SFRTHST TMST
                                      WHERE  TMST.SFRTHST_PIDM = SGBSTDN.SGBSTDN_PIDM
                                      AND    TMST.SFRTHST_TERM_CODE = SGBSTDN.SGBSTDN_TERM_CODE_EFF)
  ),

SGAADVR as
(
  SELECT
      SGRADVR.SGRADVR_PIDM,
      SGRADVR.SGRADVR_TERM_CODE_EFF,
      SGRADVR.SGRADVR_ADVR_PIDM,
      SGRADVR.SGRADVR_ADVR_CODE,
      SGRADVR.SGRADVR_PRIM_IND,
      SGRADVR.SGRADVR_ACTIVITY_DATE,
      SGRADVR.SGRADVR_SURROGATE_ID,
      (SELECT GOREMAL_EMAIL_ADDRESS
      FROM    GOREMAL
      WHERE   GOREMAL_PIDM = SGRADVR.SGRADVR_ADVR_PIDM
      AND     GOREMAL_EMAL_CODE = 'SU') as SGRADVR_ADVR_EMAIL,
      CASE
        WHEN SGRADVR_ADVR_PIDM IS NULL THEN NULL
          ELSE f_format_name(SGRADVR.SGRADVR_ADVR_PIDM, 'LF30')
            END as SGRADVR_ADVR_NAME,
      CASE
        WHEN SGRADVR.SGRADVR_PIDM IS NULL THEN NULL
          ELSE f_format_name(SGRADVR.SGRADVR_PIDM, 'LF30')
            END as SGRADVR_NAME,
      CASE
        WHEN SGRADVR_ADVR_CODE IS NULL THEN NULL
          ELSE f_get_desc_fnc('STVADVR', SGRADVR_ADVR_CODE, 30)
            END as SGRADVR_ADVR_DESC

  FROM
      SGRADVR SGRADVR

  WHERE
      SGRADVR.SGRADVR_PRIM_IND = 'Y'
      AND SGRADVR.SGRADVR_TERM_CODE_EFF = (SELECT MAX(SGRADVR_TERM_CODE_EFF)
                                          FROM    SGRADVR ADVR
                                          WHERE   ADVR.SGRADVR_PIDM = SGRADVR.SGRADVR_PIDM
                                          AND     ADVR.SGRADVR_PRIM_IND = 'Y'
                                          AND     ADVR.SGRADVR_TERM_CODE_EFF <= 202420)
      AND SGRADVR.SGRADVR_SURROGATE_ID = (SELECT MAX(SGRADVR_SURROGATE_ID)
                                         FROM    SGRADVR ADVR
                                         WHERE   ADVR.SGRADVR_PIDM = SGRADVR.SGRADVR_PIDM
                                         AND     ADVR.SGRADVR_TERM_CODE_EFF = SGRADVR.SGRADVR_TERM_CODE_EFF
                                         AND     ADVR.SGRADVR_PRIM_IND = 'Y')
  ),

SFAREGS as
(
  SELECT
      SFRSTCR.SFRSTCR_TERM_CODE,
      SFRSTCR.SFRSTCR_PIDM,
      SFRSTCR.SFRSTCR_CRN,
      SFRSTCR.SFRSTCR_CLASS_SORT_KEY,
      SFRSTCR.SFRSTCR_REG_SEQ,
      SFRSTCR.SFRSTCR_PTRM_CODE,
      SFRSTCR.SFRSTCR_RSTS_CODE,
      SFRSTCR.SFRSTCR_BILL_HR,
      SFRSTCR.SFRSTCR_WAIV_HR,
      SFRSTCR.SFRSTCR_CREDIT_HR,
      SFRSTCR.SFRSTCR_BILL_HR_HOLD,
      SFRSTCR.SFRSTCR_CREDIT_HR_HOLD,
      SFRSTCR.SFRSTCR_GMOD_CODE,
      SFRSTCR.SFRSTCR_GRDE_CODE,
      SFRSTCR.SFRSTCR_GRDE_CODE_MID,
      SFRSTCR.SFRSTCR_GRDE_DATE,
      SFRSTCR.SFRSTCR_ADD_DATE,
      SFRSTCR.SFRSTCR_ACTIVITY_DATE,
      SFRSTCR.SFRSTCR_LEVL_CODE,
      SFRSTCR.SFRSTCR_CAMP_CODE,
      SFRSTCA.SFRSTCA_TERM_CODE,
      SFRSTCA.SFRSTCA_PIDM,
      SFRSTCA.SFRSTCA_CRN,
      SFRSTCA.SFRSTCA_SEQ_NUMBER,
      SFRSTCA.SFRSTCA_LEVL_CODE,
      SFRSTCA.SFRSTCA_CAMP_CODE,
      SFRSTCA.SFRSTCA_ADD_DATE,
      SFRSTCA.SFRSTCA_ACTIVITY_DATE,
      SFRSTCA.SFRSTCA_RSTS_CODE,
      SFRSTCA.SFRSTCA_RSTS_DATE,
      SFRSTCA.SFRSTCA_ERROR_FLAG,
      SFRSTCA.SFRSTCA_MESSAGE,
      SFRSTCA.SFRSTCA_BILL_HR,
      SFRSTCA.SFRSTCA_CREDIT_HR,
      SFRSTCA.SFRSTCA_GMOD_CODE,
      SFRSTCA.SFRSTCA_USER,
      SFRSTCA.SFRSTCA_GCMT_CODE,
      SFRSTCA.SFRSTCA_SOURCE_CDE,
      SFRSTCA.SFRSTCA_DATA_ORIGIN,
      SFRSTCA.SFRSTCA_ATTEMPT_HR,
      SFRSTCA.SFRSTCA_RMSG_CDE,
      SFRSTCA.SFRSTCA_STSP_KEY_SEQUENCE,
      SFRSTCA.SFRSTCA_BRDH_SEQ_NUM,
      SFRSTCA.SFRSTCA_BLCK_CODE,
      SFRSTCA.SFRSTCA_STRH_SEQNO,
      SFRSTCA.SFRSTCA_STRD_SEQNO,
      SFRSTCA.SFRSTCA_SURROGATE_ID,
      SFRSTCA.SFRSTCA_VERSION,
      SFRSTCA.SFRSTCA_USER_ID,
      SFRSTCA.SFRSTCA_VPDI_CODE,
      SFRSTCA.SFRSTCA_SESSIONID,
      SFRSTCA.SFRSTCA_CURRENT_TIME,
      SFRSTCA.SFRSTCA_ENRL,
      SFRSTCA.SFRSTCA_SEATS_AVAIL

  FROM
      SFRSTCR SFRSTCR

      LEFT OUTER JOIN SFRSTCA SFRSTCA ON SFRSTCA.SFRSTCA_PIDM = SFRSTCR.SFRSTCR_PIDM
           AND SFRSTCA.SFRSTCA_TERM_CODE = SFRSTCR.SFRSTCR_TERM_CODE
           AND SFRSTCA.SFRSTCA_CRN = SFRSTCR.SFRSTCR_CRN
           AND SFRSTCA.SFRSTCA_SEQ_NUMBER = (SELECT MAX(SFRSTCA_SEQ_NUMBER)
                                            FROM    SFRSTCA STCA
                                            WHERE   STCA.SFRSTCA_PIDM = SFRSTCR.SFRSTCR_PIDM
                                            AND     STCA.SFRSTCA_TERM_CODE = SFRSTCR.SFRSTCR_TERM_CODE
                                            AND     STCA.SFRSTCA_CRN = SFRSTCR.SFRSTCR_CRN)
/*
  WHERE
      SFRSTCR.SFRSTCR_TERM_CODE = :select_term_code.STVTERM_CODE
*/
  ),

SHATCKN as
(
  SELECT
      SFRSTCR_TERM_CODE,
      SFRSTCR_PIDM,
      SFRSTCR_CRN,
      SFRSTCR_CLASS_SORT_KEY,
      SFRSTCR_REG_SEQ,
      SFRSTCR_PTRM_CODE,
      SFRSTCR_RSTS_CODE,
      SFRSTCR_BILL_HR,
      SFRSTCR_WAIV_HR,
      SFRSTCR_CREDIT_HR,
      SFRSTCR_BILL_HR_HOLD,
      SFRSTCR_CREDIT_HR_HOLD,
      SFRSTCR_GMOD_CODE,
      SFRSTCR_GRDE_CODE,
      SFRSTCR_GRDE_CODE_MID,
      SFRSTCR_GRDE_DATE,
      SFRSTCR_ADD_DATE,
      SFRSTCR_ACTIVITY_DATE,
      SFRSTCR_LEVL_CODE,
      SFRSTCR_CAMP_CODE,
      SFRSTCA_TERM_CODE,
      SFRSTCA_PIDM,
      SFRSTCA_CRN,
      SFRSTCA_SEQ_NUMBER,
      SFRSTCA_LEVL_CODE,
      SFRSTCA_CAMP_CODE,
      SFRSTCA_ADD_DATE,
      SFRSTCA_ACTIVITY_DATE,
      SFRSTCA_RSTS_CODE,
      SFRSTCA_RSTS_DATE,
      SFRSTCA_ERROR_FLAG,
      SFRSTCA_MESSAGE,
      SFRSTCA_BILL_HR,
      SFRSTCA_CREDIT_HR,
      SFRSTCA_GMOD_CODE,
      SFRSTCA_USER,
      SFRSTCA_GCMT_CODE,
      SFRSTCA_SOURCE_CDE,
      SFRSTCA_DATA_ORIGIN,
      SFRSTCA_ATTEMPT_HR,
      SFRSTCA_RMSG_CDE,
      SFRSTCA_STSP_KEY_SEQUENCE,
      SFRSTCA_BRDH_SEQ_NUM,
      SFRSTCA_BLCK_CODE,
      SFRSTCA_STRH_SEQNO,
      SFRSTCA_STRD_SEQNO,
      SFRSTCA_SURROGATE_ID,
      SFRSTCA_VERSION,
      SFRSTCA_USER_ID,
      SFRSTCA_VPDI_CODE,
      SFRSTCA_SESSIONID,
      SFRSTCA_CURRENT_TIME,
      SFRSTCA_ENRL,
      SFRSTCA_SEATS_AVAIL,
      SHRTCKN.SHRTCKN_PIDM,
      SHRTCKN.SHRTCKN_TERM_CODE,
      SHRTCKN.SHRTCKN_SEQ_NO,
      SHRTCKN.SHRTCKN_CRN,
      SHRTCKN.SHRTCKN_SUBJ_CODE,
      SHRTCKN.SHRTCKN_CRSE_NUMB,
      SHRTCKN.SHRTCKN_COLL_CODE,
      SHRTCKN.SHRTCKN_CAMP_CODE,
      SHRTCKN.SHRTCKN_ACTIVITY_DATE,
      SHRTCKN.SHRTCKN_SEQ_NUMB,
      SHRTCKN.SHRTCKN_SURROGATE_ID,
      SHRTCKN.SHRTCKN_VERSION,
      SHRTCKL.SHRTCKL_PIDM,
      SHRTCKL.SHRTCKL_TERM_CODE,
      SHRTCKL.SHRTCKL_TCKN_SEQ_NO,
      SHRTCKL.SHRTCKL_LEVL_CODE,
      SHRTCKL.SHRTCKL_ACTIVITY_DATE,
      SHRTCKL.SHRTCKL_PRIMARY_LEVL_IND,
      SHRTCKL.SHRTCKL_SURROGATE_ID,
      SHRTCKL.SHRTCKL_VERSION,
      SHRTCKG.SHRTCKG_PIDM,
      SHRTCKG.SHRTCKG_TERM_CODE,
      SHRTCKG.SHRTCKG_TCKN_SEQ_NO,
      SHRTCKG.SHRTCKG_SEQ_NO,
      SHRTCKG.SHRTCKG_FINAL_GRDE_SEQ_NO,
      SHRTCKG.SHRTCKG_GRDE_CODE_FINAL,
      SHRTCKG.SHRTCKG_GMOD_CODE,
      SHRTCKG.SHRTCKG_CREDIT_HOURS,
      SHRTCKG.SHRTCKG_GCHG_CODE,
      SHRTCKG.SHRTCKG_FINAL_GRDE_CHG_DATE,
      SHRTCKG.SHRTCKG_HOURS_ATTEMPTED,
      SHRTCKG.SHRTCKG_GRDE_CODE_INCMP_FINAL,
      SHRTCKG.SHRTCKG_SURROGATE_ID,
      SHRTCKG.SHRTCKG_VERSION,
      SHRGRDE.SHRGRDE_CODE,
      SHRGRDE.SHRGRDE_LEVL_CODE,
      SHRGRDE.SHRGRDE_QUALITY_POINTS,
      SHRGRDE.SHRGRDE_ATTEMPTED_IND,
      SHRGRDE.SHRGRDE_COMPLETED_IND,
      SHRGRDE.SHRGRDE_PASSED_IND,
      SHRGRDE.SHRGRDE_GPA_IND,
      SHRGRDE.SHRGRDE_SURROGATE_ID,
      SHRGRDE.SHRGRDE_VERSION,
      SHRGRDE.SHRGRDE_NUMERIC_VALUE,
      CASE
        WHEN SHRTCKG.SHRTCKG_GCHG_CODE IS NULL THEN NULL
          ELSE f_get_desc_fnc('STVGCHG', SHRTCKG.SHRTCKG_GCHG_CODE, 30)
            END as SHRTCKG_GCHG_DESC,
      decode(SHRGRDE.SHRGRDE_COMPLETED_IND,'Y',1,0) as COURSE_COMPLETE_IND,
      decode(SHRGRDE.SHRGRDE_PASSED_IND,'Y',1,0) as COURSE_PASSED_IND,
      decode(SHRGRDE.SHRGRDE_GPA_IND,'Y',1,0) as COURSE_GPA_IND,
      f_format_name(SFRSTCR_PIDM, 'LF30') as SFRSTCR_STUDENT_NAME

  FROM
      SFAREGS SFRSTCR

      LEFT OUTER JOIN SHRTCKN SHRTCKN ON SHRTCKN.SHRTCKN_PIDM = SFRSTCR_PIDM
           AND SHRTCKN.SHRTCKN_TERM_CODE = SFRSTCR_TERM_CODE
           AND SHRTCKN.SHRTCKN_CRN = SFRSTCR_CRN

      LEFT OUTER JOIN SHRTCKG SHRTCKG ON SHRTCKG.SHRTCKG_PIDM = SFRSTCR_PIDM
           AND SHRTCKG.SHRTCKG_TERM_CODE = SFRSTCR_TERM_CODE
           AND SHRTCKG.SHRTCKG_TCKN_SEQ_NO = SFRSTCR_REG_SEQ
           AND SHRTCKG.SHRTCKG_SEQ_NO = (SELECT MAX(SHRTCKG_SEQ_NO)
                                        FROM    SHRTCKG TCKG
                                        WHERE   TCKG.SHRTCKG_PIDM = SHRTCKG.SHRTCKG_PIDM
                                        AND     TCKG.SHRTCKG_TERM_CODE = SHRTCKG.SHRTCKG_TERM_CODE
                                        AND     TCKG.SHRTCKG_TCKN_SEQ_NO = SHRTCKG.SHRTCKG_TCKN_SEQ_NO)

      LEFT OUTER JOIN SHRTCKL SHRTCKL ON SHRTCKL.SHRTCKL_PIDM = SFRSTCR_PIDM
           AND SHRTCKL.SHRTCKL_TERM_CODE = SFRSTCR_TERM_CODE
           AND SHRTCKL.SHRTCKL_SURROGATE_ID = (SELECT MAX(SHRTCKL_SURROGATE_ID)
                                              FROM    SHRTCKL TCKL
                                              WHERE   TCKL.SHRTCKL_PIDM = SHRTCKL.SHRTCKL_PIDM
                                              AND     TCKL.SHRTCKL_TERM_CODE = SHRTCKL.SHRTCKL_TERM_CODE)

      LEFT OUTER JOIN SHRGRDE SHRGRDE ON SHRGRDE.SHRGRDE_CODE = SFRSTCR.SFRSTCR_GRDE_CODE
           AND SHRGRDE.SHRGRDE_LEVL_CODE = SHRTCKL.SHRTCKL_LEVL_CODE
           AND SHRGRDE.SHRGRDE_TERM_CODE_EFFECTIVE = (SELECT MAX(SHRGRDE_TERM_CODE_EFFECTIVE)
                                                     FROM    SHRGRDE GRDE
                                                     WHERE   GRDE.SHRGRDE_CODE = SHRGRDE.SHRGRDE_CODE
                                                     AND     GRDE.SHRGRDE_LEVL_CODE = SHRTCKL.SHRTCKL_LEVL_CODE
                                                     AND     GRDE.SHRGRDE_TERM_CODE_EFFECTIVE <= SFRSTCR_TERM_CODE)
  ),

SSASECT as
(
    SELECT
      SSBSECT.SSBSECT_TERM_CODE,
      SSBSECT.SSBSECT_CRN,
      SSBSECT.SSBSECT_PTRM_CODE,
      SSBSECT.SSBSECT_SUBJ_CODE,
      SSBSECT.SSBSECT_CRSE_NUMB,
      SSBSECT.SSBSECT_SEQ_NUMB,
      SSBSECT.SSBSECT_SSTS_CODE,
      SSBSECT.SSBSECT_SCHD_CODE,
      SSBSECT.SSBSECT_CAMP_CODE,
      SSBSECT.SSBSECT_CREDIT_HRS,
      SSBSECT.SSBSECT_BILL_HRS,
      SSBSECT.SSBSECT_GMOD_CODE,
      SSBSECT.SSBSECT_REG_ONEUP,
      SSBSECT.SSBSECT_PRIOR_ENRL,
      SSBSECT.SSBSECT_PROJ_ENRL,
      SSBSECT.SSBSECT_MAX_ENRL,
      SSBSECT.SSBSECT_ENRL,
      SSBSECT.SSBSECT_SEATS_AVAIL,
      SSBSECT.SSBSECT_TOT_CREDIT_HRS,
      SSBSECT.SSBSECT_CENSUS_ENRL,
      SSBSECT.SSBSECT_CENSUS_ENRL_DATE,
      SSBSECT.SSBSECT_ACTIVITY_DATE,
      SSBSECT.SSBSECT_PTRM_START_DATE,
      SSBSECT.SSBSECT_PTRM_END_DATE,
      SSBSECT.SSBSECT_PTRM_WEEKS,
      SSBSECT.SSBSECT_WAIT_CAPACITY,
      SSBSECT.SSBSECT_WAIT_COUNT,
      SSBSECT.SSBSECT_WAIT_AVAIL,
      SSBSECT.SSBSECT_INSM_CODE,
      SSBSECT.SSBSECT_SURROGATE_ID,
      SSBSECT.SSBSECT_VERSION,
      SSBSECT.SSBSECT_SICAS_CAMP_COURSE_ID,
      SSBSECT.SSBSECT_SICAS_CAMP_SECTION_ID,
      SCBCRSE.SCBCRSE_SUBJ_CODE,
      SCBCRSE.SCBCRSE_CRSE_NUMB,
      SCBCRSE.SCBCRSE_EFF_TERM,
      SCBCRSE.SCBCRSE_COLL_CODE,
      SCBCRSE.SCBCRSE_DIVS_CODE,
      SCBCRSE.SCBCRSE_DEPT_CODE,
      SCBCRSE.SCBCRSE_CSTA_CODE,
      SCBCRSE.SCBCRSE_TITLE,
      SCBCRSE.SCBCRSE_CIPC_CODE,
      SCBCRSE.SCBCRSE_CREDIT_HR_IND,
      SCBCRSE.SCBCRSE_CREDIT_HR_LOW,
      SCBCRSE.SCBCRSE_CREDIT_HR_HIGH,
      SCBCRSE.SCBCRSE_LEC_HR_IND,
      SCBCRSE.SCBCRSE_LEC_HR_LOW,
      SCBCRSE.SCBCRSE_LEC_HR_HIGH,
      SCBCRSE.SCBCRSE_BILL_HR_IND,
      SCBCRSE.SCBCRSE_BILL_HR_LOW,
      SCBCRSE.SCBCRSE_BILL_HR_HIGH,
      SCBCRSE.SCBCRSE_ACTIVITY_DATE,
      SCBCRSE.SCBCRSE_CONT_HR_LOW,
      SCBCRSE.SCBCRSE_CONT_HR_IND,
      SCBCRSE.SCBCRSE_CONT_HR_HIGH,
      SCBCRSE.SCBCRSE_REPS_CODE,
      SCBCRSE.SCBCRSE_MAX_RPT_UNITS,
      SCBCRSE.SCBCRSE_SURROGATE_ID,
      SCBCRSE.SCBCRSE_VERSION,
      SCBCRSE.SCBCRSE_VPDI_CODE,
      SCBCRSE.SCBCRSE_SICAS_SUNY_ID,
      F_GET_DESC_FNC('STVSSTS', SSBSECT.SSBSECT_SSTS_CODE, 30) as SSBSECT_SSTS_DESC,
      F_GET_DESC_FNC('STVSCHD', SSBSECT.SSBSECT_SCHD_CODE, 30) as SSBSECT_SCHD_DESC,
      F_GET_DESC_FNC('STVCSTA', SCBCRSE.SCBCRSE_CSTA_CODE, 30) as SCBCRSE_CSTA_DESC,
      F_GET_DESC_FNC('STVREPS', SCBCRSE.SCBCRSE_REPS_CODE, 30) as SCBCRSE_REPS_DESC

  FROM
      SSBSECT SSBSECT

      LEFT OUTER JOIN SCBCRSE SCBCRSE ON SSBSECT.SSBSECT_SUBJ_CODE = SCBCRSE.SCBCRSE_SUBJ_CODE
           AND SCBCRSE.SCBCRSE_CRSE_NUMB = SSBSECT.SSBSECT_CRSE_NUMB

  WHERE
      --SSBSECT.SSBSECT_TERM_CODE = :select_term_code.STVTERM_CODE
      --AND
      SCBCRSE.SCBCRSE_EFF_TERM = (SELECT MAX(SCBCRSE_EFF_TERM)
                                 FROM     SCBCRSE CRSE
                                 WHERE    CRSE.SCBCRSE_SUBJ_CODE = SSBSECT.SSBSECT_SUBJ_CODE
                                 AND      CRSE.SCBCRSE_CRSE_NUMB = SSBSECT.SSBSECT_CRSE_NUMB
                                 AND      CRSE.SCBCRSE_EFF_TERM <= SSBSECT.SSBSECT_TERM_CODE)
  ORDER BY
      SSBSECT.SSBSECT_SICAS_CAMP_SECTION_ID
  ),

SIRASGQ as
(
 SELECT
      SIRASGN.SIRASGN_TERM_CODE,
      SIRASGN.SIRASGN_CRN,
      SIRASGN.SIRASGN_PIDM,
      SIRASGN.SIRASGN_CATEGORY,
      SIRASGN.SIRASGN_PRIMARY_IND,
      SIRASGN.SIRASGN_ACTIVITY_DATE,
      SIRASGN.SIRASGN_SURROGATE_ID,
      SIRASGN.SIRASGN_VERSION,
      SIRDPCL.SIRDPCL_PIDM,
      SIRDPCL.SIRDPCL_TERM_CODE_EFF,
      SIRDPCL.SIRDPCL_COLL_CODE,
      SIRDPCL.SIRDPCL_DEPT_CODE,
      SIRDPCL.SIRDPCL_ACTIVITY_DATE,
      SIRDPCL.SIRDPCL_SURROGATE_ID,
      SIRDPCL.SIRDPCL_VERSION,
      f_format_name(SIRDPCL.SIRDPCL_PIDM, 'LF30') as SIRDPCL_INSTR_NAME,
      CASE
        WHEN SIRDPCL_DEPT_CODE IS NULL THEN 'DEPT UNAVAILABLE'
          ELSE F_GET_DESC_FNC('STVDEPT', SIRDPCL.SIRDPCL_DEPT_CODE, 30)
            END as SIRDPCL_DEPT_DESC,
      (SELECT GOREMAL_EMAIL_ADDRESS
      FROM    GOREMAL
      WHERE   GOREMAL_PIDM = SIRDPCL_PIDM
      AND     GOREMAL_EMAL_CODE = 'ESF'
      AND     GOREMAL_STATUS_IND = 'A'
      AND     GOREMAL_PREFERRED_IND = 'Y'
      AND     SIRASGN_PRIMARY_IND = 'Y') as SIRDPCL_INSTR_EMAIL

  FROM
      SIRASGN SIRASGN
      LEFT OUTER JOIN SIRDPCL SIRDPCL ON SIRDPCL.SIRDPCL_PIDM = SIRASGN.SIRASGN_PIDM

  WHERE
      SIRASGN.SIRASGN_PRIMARY_IND = 'Y'
      AND SIRASGN.SIRASGN_TERM_CODE = (SELECT MAX(SIRASGN_TERM_CODE)
                                      FROM    SIRASGN ASGN
                                      WHERE   ASGN.SIRASGN_PIDM = SIRASGN.SIRASGN_PIDM
                                      AND     ASGN.SIRASGN_TERM_CODE <= :select_term_code.STVTERM_CODE)
      AND SIRDPCL.SIRDPCL_TERM_CODE_EFF = (SELECT MAX(SIRDPCL_TERM_CODE_EFF)
                                          FROM    SIRDPCL DPCL
                                          WHERE   DPCL.SIRDPCL_PIDM = SIRDPCL.SIRDPCL_PIDM
                                          AND     DPCL.SIRDPCL_TERM_CODE_EFF <= :select_term_code.STVTERM_CODE)
      AND SIRDPCL.SIRDPCL_SURROGATE_ID = (SELECT MAX(SIRDPCL_SURROGATE_ID)
                                         FROM    SIRDPCL DPCL
                                         WHERE   DPCL.SIRDPCL_PIDM = SIRDPCL.SIRDPCL_PIDM
                                         AND     DPCL.SIRDPCL_TERM_CODE_EFF <= :select_term_code.STVTERM_CODE)
  ),

SSAMEET as
(
  SELECT
      SSRMEET.SSRMEET_TERM_CODE,
      SSRMEET.SSRMEET_CRN,
      SSRMEET.SSRMEET_DAYS_CODE,
      SSRMEET.SSRMEET_DAY_NUMBER,
      SSRMEET.SSRMEET_BEGIN_TIME,
      SSRMEET.SSRMEET_END_TIME,
      SSRMEET.SSRMEET_BLDG_CODE,
      SSRMEET.SSRMEET_ROOM_CODE,
      SSRMEET.SSRMEET_ACTIVITY_DATE,
      SSRMEET.SSRMEET_START_DATE,
      SSRMEET.SSRMEET_END_DATE,
      SSRMEET.SSRMEET_SUN_DAY,
      SSRMEET.SSRMEET_MON_DAY,
      SSRMEET.SSRMEET_TUE_DAY,
      SSRMEET.SSRMEET_WED_DAY,
      SSRMEET.SSRMEET_THU_DAY,
      SSRMEET.SSRMEET_FRI_DAY,
      SSRMEET.SSRMEET_SAT_DAY,
      SSRMEET.SSRMEET_SCHD_CODE,
      SSRMEET.SSRMEET_CREDIT_HR_SESS,
      SSRMEET.SSRMEET_MEET_NO,
      SSRMEET.SSRMEET_HRS_WEEK,
      SSRMEET.SSRMEET_MTYP_CODE,
      SSRMEET.SSRMEET_SURROGATE_ID,
      SSRMEET.SSRMEET_VERSION

  FROM
      SSRMEET SSRMEET
/*
  WHERE
      SSRMEET.SSRMEET_TERM_CODE = :select_term_code.STVTERM_CODE
*/
  ORDER BY
      SSRMEET_CRN
  ),

PERSONS_LIST_DEMO as
(
  SELECT
      CASE
        WHEN SPBPERS_SEX IS NULL THEN 0
          ELSE 1
            END as SEX_Measure,
      CASE
        WHEN GORRACE_RACE_CDE IS NULL THEN 0
          ELSE 1
            END as RACE_Measure,
      CASE
        WHEN SPBPERS_ETHN_CDE IS NULL THEN 0
          ELSE 1
            END as ETHN_Measure,
      SPRIDEN_PIDM,
      SPRIDEN_ID,
      SPRIDEN_LAST_NAME,
      SPRIDEN_FIRST_NAME,
      SPRIDEN_MI,
      SPRIDEN_LEGAL_NAME,
      SPRIDEN_SEARCH_LAST_NAME,
      SPRIDEN_SEARCH_FIRST_NAME,
      SPRIDEN_SEARCH_MI,
      SPBPERS_PREF_FIRST_NAME,
      SPBPERS_AGE,
      SPBPERS_SEX,
      GORRACE_RACE_CDE,
      GORRACE_DESC,
      SPBPERS_ETHN_CDE,
      SPBPERS_ETHN_DESC,
      SPBPERS_SICAS_HISP_ORIGIN,
      SPBPERS_CITZ_CODE,
      SPBPERS_CITZ_COUNTRY,
      GOBINTL_NATN_CODE_BIRTH,
      GOBINTL_BIRTH_NATN,
      GOBTPAC_EXTERNAL_USER,
      GORADID_ADDITIONAL_ID,
      GOREMAL_EMAIL_ADDRESS,
      GOREMAL_EMAL_CODE

  FROM
      SPAIDEN SPRIDEN

      LEFT OUTER JOIN SPAPERS SPBPERS ON SPBPERS.SPBPERS_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN GOARACE GORPRAC ON GORPRAC.GORPRAC_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN SOREMAL GOREMAL ON GOREMAL.GOREMAL_PIDM = SPRIDEN_PIDM
  ),

PERSONS_ADRTELE as
(
  SELECT
      SPRIDEN_PIDM,
      SPRIDEN_ID,
      SPRIDEN_LAST_NAME,
      SPRIDEN_FIRST_NAME,
      SPRIDEN_MI,
      SPRIDEN_LEGAL_NAME,
      SPRIDEN_SEARCH_LAST_NAME,
      SPRIDEN_SEARCH_FIRST_NAME,
      SPRIDEN_SEARCH_MI,
      SPBPERS_PREF_FIRST_NAME,
      SPBPERS_AGE,
      SPBPERS_SEX,
      GORRACE_RACE_CDE,
      GORRACE_DESC,
      SPBPERS_ETHN_CDE,
      SPBPERS_ETHN_DESC,
      SPBPERS_SICAS_HISP_ORIGIN,
      SPBPERS_CITZ_CODE,
      SPBPERS_CITZ_COUNTRY,
      GOBINTL_NATN_CODE_BIRTH,
      GOBINTL_BIRTH_NATN,
      GOBTPAC_EXTERNAL_USER,
      GORADID_ADDITIONAL_ID,
      GOREMAL_EMAIL_ADDRESS,
      GOREMAL_EMAL_CODE,
      SPRADDR_PIDM,
      SPRADDR_ATYP_CODE,
      SPRADDR_ATYP_DESC,
      SPRADDR_FROM_DATE,
      SPRADDR_TO_DATE,
      SPRADDR_STREET_LINE1,
      SPRADDR_STREET_LINE2,
      SPRADDR_STREET_LINE3,
      SPRADDR_CITY,
      SPRADDR_STAT_CODE,
      SPRADDR_ZIP,
      SPRTELE_PIDM,
      SPRTELE_TELE_CODE,
      SPRTELE_TELE_DESC,
      SPRTELE_PHONE_AREA,
      SPRTELE_PHONE_NUMBER,
      SPREMRG_PIDM,
      SPREMRG_LAST_NAME,
      SPREMRG_FIRST_NAME,
      SPREMRG_MI,
      SPREMRG_RELT_CODE,
      SPREMRG_RELT_DESC,
      SPREMRG_PRIORITY,
      SPREMRG_STREET_LINE1,
      SPREMRG_STREET_LINE2,
      SPREMRG_STREET_LINE3,
      SPREMRG_CITY,
      SPREMRG_STAT_CODE,
      SPREMRG_NATN_CODE,
      SPREMRG_ZIP,
      SPREMRG_PHONE_AREA,
      SPREMRG_PHONE_NUMBER,
      SPREMRG_PHONE_EXT,
      SPREMRG_ACTIVITY_DATE,
      SPREMRG_ATYP_CODE,
      SPREMRG_HOUSE_NUMBER

  FROM
      PERSONS_LIST_DEMO A

      LEFT OUTER JOIN TUIADDR SPRADDR ON SPRADDR.SPRADDR_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN SPATELE SPRTELE ON SPRTELE.SPRTELE_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN SPAEMRG SPREMRG ON SPREMRG.SPREMRG_PIDM = SPRIDEN_PIDM


  WHERE
      (SPREMRG_PRIORITY <= 1 OR SPREMRG_PRIORITY IS NULL)
  ),

STUDENT_LIST_DEMO as
(
  SELECT
      CASE
        WHEN SPBPERS_SEX IS NULL THEN 0
          ELSE 1
            END as SEX_Measure,
      CASE
        WHEN GORRACE_RACE_CDE IS NULL THEN 0
          ELSE 1
            END as RACE_Measure,
      CASE
        WHEN SPBPERS_ETHN_CDE IS NULL THEN 0
          ELSE 1
            END as ETHN_Measure,
      CASE
        WHEN SGBSTDN_MAJR_CODE_1 IS NULL THEN 0
          ELSE 1
            END as POS_Measure,
      CASE
        WHEN SGBSTDN_DEGC_CODE_1 IS NULL THEN 0
          ELSE 1
            END as DEGC_Measure,
      CASE
        WHEN SGBSTDN_STYP_CODE IS NULL THEN 0
          ELSE 1
            END as STYP_Measure,
      CASE
        WHEN SGBSTDN_LEVL_CODE IS NULL THEN 0
          ELSE 1
            END as LEVL_Measure,
      CASE
        WHEN SGBSTDN_CLAS_CODE IS NULL THEN 0
          ELSE 1
            END as CLAS_Measure,
      SPRIDEN_PIDM,
      SPRIDEN_ID,
      SPRIDEN_LAST_NAME,
      SPRIDEN_FIRST_NAME,
      SPRIDEN_MI,
      SPRIDEN_LEGAL_NAME,
      SPRIDEN_SEARCH_LAST_NAME,
      SPRIDEN_SEARCH_FIRST_NAME,
      SPRIDEN_SEARCH_MI,
      SPBPERS_PREF_FIRST_NAME,
      SPBPERS_AGE,
      SPBPERS_SEX,
      GORRACE_RACE_CDE,
      GORRACE_DESC,
      SPBPERS_ETHN_CDE,
      SPBPERS_ETHN_DESC,
      SPBPERS_SICAS_HISP_ORIGIN,
      SPBPERS_CITZ_CODE,
      SPBPERS_CITZ_COUNTRY,
      GOBINTL_NATN_CODE_BIRTH,
      GOBINTL_BIRTH_NATN,
      GOBTPAC_EXTERNAL_USER,
      GORADID_ADDITIONAL_ID,
      GOREMAL_EMAIL_ADDRESS,
      GOREMAL_EMAL_CODE,
      SFRTHST_TMST_CODE,
      SFRTHST_TMST_DESC,
      SGBSTDN_TERM_CODE_EFF,
      SGBSTDN_STST_CODE,
      SGBSTDN_STYP_CODE,
      SGBSTDN_LEVL_CODE,
      SGBSTDN_CLAS_CODE,
      SGBSTDN_DEPT_CODE,
      SGBSTDN_PROGRAM_1,
      SGBSTDN_MAJR_CODE_1,
      SGBSTDN_MAJR_CODE_MINR_1,
      SGBSTDN_MAJR_CODE_MINR_1_2,
      SGBSTDN_MAJR_CODE_CONC_1,
      SGBSTDN_DEGC_CODE_1,
      SGBSTDN_RESD_CODE,
      SGBSTDN_EXP_GRAD_DATE,
      SGBSTDN_EFF_TERM_DESC,
      SGBSTDN_STYP_DESC,
      SGBSTDN_LEVL_DESC,
      SGBSTDN_CLAS_DESC,
      SGBSTDN_DEPT_DESC,
      SGBSTDN_MAJR_DESC,
      SGBSTDN_MINR_1_DESC,
      SGBSTDN_MINR_1_2_DESC,
      SGBSTDN_CONC_DESC,
      SGBSTDN_DEGC_DESC,
      SGBSTDN_RESD_DESC,
      STVCLAS_SURROGATE_ID

  FROM
      SPAIDEN SPRIDEN

      LEFT OUTER JOIN SPAPERS SPBPERS ON SPBPERS.SPBPERS_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN GOARACE GORPRAC ON GORPRAC.GORPRAC_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN SOREMAL GOREMAL ON GOREMAL.GOREMAL_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN SGASTDN SGBSTDN ON SGBSTDN.SGBSTDN_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN STVCLAS STVCLAS ON STVCLAS.STVCLAS_CODE = SGBSTDN_CLAS_CODE

  WHERE
      SGBSTDN_TERM_CODE_EFF = FY_SGBSTDN_EFF_TERM(SPRIDEN_PIDM, :select_term_code.STVTERM_CODE)
  ),

STUDENT_ADRTELE as
(
  SELECT
      SPRIDEN_PIDM,
      SPRIDEN_ID,
      SPRIDEN_LAST_NAME,
      SPRIDEN_FIRST_NAME,
      SPRIDEN_MI,
      SPRIDEN_LEGAL_NAME,
      SPRIDEN_SEARCH_LAST_NAME,
      SPRIDEN_SEARCH_FIRST_NAME,
      SPRIDEN_SEARCH_MI,
      SPBPERS_PREF_FIRST_NAME,
      SPBPERS_AGE,
      SPBPERS_SEX,
      GORRACE_RACE_CDE,
      GORRACE_DESC,
      SPBPERS_ETHN_CDE,
      SPBPERS_ETHN_DESC,
      SPBPERS_SICAS_HISP_ORIGIN,
      SPBPERS_CITZ_CODE,
      SPBPERS_CITZ_COUNTRY,
      GOBINTL_NATN_CODE_BIRTH,
      GOBINTL_BIRTH_NATN,
      GOBTPAC_EXTERNAL_USER,
      GORADID_ADDITIONAL_ID,
      GOREMAL_EMAIL_ADDRESS,
      GOREMAL_EMAL_CODE,
      SPRADDR_PIDM,
      SPRADDR_ATYP_CODE,
      SPRADDR_ATYP_DESC,
      SPRADDR_FROM_DATE,
      SPRADDR_TO_DATE,
      SPRADDR_STREET_LINE1,
      SPRADDR_STREET_LINE2,
      SPRADDR_STREET_LINE3,
      SPRADDR_CITY,
      SPRADDR_STAT_CODE,
      SPRADDR_ZIP,
      SPRTELE_PIDM,
      SPRTELE_TELE_CODE,
      SPRTELE_TELE_DESC,
      SPRTELE_PHONE_AREA,
      SPRTELE_PHONE_NUMBER,
      SPREMRG_PIDM,
      SPREMRG_LAST_NAME,
      SPREMRG_FIRST_NAME,
      SPREMRG_MI,
      SPREMRG_RELT_CODE,
      SPREMRG_RELT_DESC,
      SPREMRG_PRIORITY,
      SPREMRG_STREET_LINE1,
      SPREMRG_STREET_LINE2,
      SPREMRG_STREET_LINE3,
      SPREMRG_CITY,
      SPREMRG_STAT_CODE,
      SPREMRG_NATN_CODE,
      SPREMRG_ZIP,
      SPREMRG_PHONE_AREA,
      SPREMRG_PHONE_NUMBER,
      SPREMRG_PHONE_EXT,
      SPREMRG_ACTIVITY_DATE,
      SPREMRG_ATYP_CODE,
      SPREMRG_HOUSE_NUMBER

  FROM
      STUDENT_LIST_DEMO A

      LEFT OUTER JOIN TUIADDR SPRADDR ON SPRADDR.SPRADDR_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN SPATELE SPRTELE ON SPRTELE.SPRTELE_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN SPAEMRG SPREMRG ON SPREMRG.SPREMRG_PIDM = SPRIDEN_PIDM

  WHERE
      (SPREMRG_PRIORITY <= 1 OR SPREMRG_PRIORITY IS NULL)
  ),

STUDENT_GRADE_LIST as
(
  SELECT
      SPRIDEN_PIDM,
      SPRIDEN_ID,
      SPRIDEN_LAST_NAME,
      SPRIDEN_FIRST_NAME,
      SPRIDEN_MI,
      SPRIDEN_LEGAL_NAME,
      SPRIDEN_SEARCH_LAST_NAME,
      SPRIDEN_SEARCH_FIRST_NAME,
      SPRIDEN_SEARCH_MI,
      SPBPERS_PREF_FIRST_NAME,
      SPBPERS_AGE,
      SPBPERS_SEX,
      GORRACE_RACE_CDE,
      GORRACE_DESC,
      SPBPERS_ETHN_CDE,
      SPBPERS_ETHN_DESC,
      SPBPERS_SICAS_HISP_ORIGIN,
      SPBPERS_CITZ_CODE,
      SPBPERS_CITZ_COUNTRY,
      GOBINTL_NATN_CODE_BIRTH,
      GOBINTL_BIRTH_NATN,
      GOBTPAC_EXTERNAL_USER,
      GORADID_ADDITIONAL_ID,
      GOREMAL_EMAIL_ADDRESS,
      GOREMAL_EMAL_CODE,
      SFRTHST_TMST_CODE,
      SFRTHST_TMST_DESC,
      SGBSTDN_TERM_CODE_EFF,
      SGBSTDN_STST_CODE,
      SGBSTDN_STYP_CODE,
      SGBSTDN_LEVL_CODE,
      SGBSTDN_CLAS_CODE,
      SGBSTDN_DEPT_CODE,
      SGBSTDN_PROGRAM_1,
      SGBSTDN_MAJR_CODE_1,
      SGBSTDN_MAJR_CODE_MINR_1,
      SGBSTDN_MAJR_CODE_MINR_1_2,
      SGBSTDN_MAJR_CODE_CONC_1,
      SGBSTDN_DEGC_CODE_1,
      SGBSTDN_RESD_CODE,
      SGBSTDN_EXP_GRAD_DATE,
      SGBSTDN_STYP_DESC,
      SGBSTDN_LEVL_DESC,
      SGBSTDN_CLAS_DESC,
      SGBSTDN_DEPT_DESC,
      SGBSTDN_MAJR_DESC,
      SGBSTDN_MINR_1_DESC,
      SGBSTDN_MINR_1_2_DESC,
      SGBSTDN_CONC_DESC,
      SGBSTDN_DEGC_DESC,
      SGBSTDN_RESD_DESC,
      STVCLAS_SURROGATE_ID,
      SFRSTCR_TERM_CODE,
      SFRSTCR_PIDM,
      SFRSTCR_CRN,
      SFRSTCR_CLASS_SORT_KEY,
      SFRSTCR_REG_SEQ,
      SFRSTCR_PTRM_CODE,
      SFRSTCR_RSTS_CODE,
      SFRSTCR_BILL_HR,
      SFRSTCR_WAIV_HR,
      SFRSTCR_CREDIT_HR,
      SFRSTCR_BILL_HR_HOLD,
      SFRSTCR_CREDIT_HR_HOLD,
      SFRSTCR_GMOD_CODE,
      SFRSTCR_GRDE_CODE,
      SFRSTCR_GRDE_CODE_MID,
      SFRSTCR_GRDE_DATE,
      SFRSTCR_ADD_DATE,
      SFRSTCR_ACTIVITY_DATE,
      SFRSTCR_LEVL_CODE,
      SFRSTCR_CAMP_CODE,
      SFRSTCA_TERM_CODE,
      SFRSTCA_PIDM,
      SFRSTCA_CRN,
      SFRSTCA_SEQ_NUMBER,
      SFRSTCA_LEVL_CODE,
      SFRSTCA_CAMP_CODE,
      SFRSTCA_ADD_DATE,
      SFRSTCA_ACTIVITY_DATE,
      SFRSTCA_RSTS_CODE,
      SFRSTCA_RSTS_DATE,
      SFRSTCA_ERROR_FLAG,
      SFRSTCA_MESSAGE,
      SFRSTCA_BILL_HR,
      SFRSTCA_CREDIT_HR,
      SFRSTCA_GMOD_CODE,
      SFRSTCA_USER,
      SFRSTCA_GCMT_CODE,
      SFRSTCA_SOURCE_CDE,
      SFRSTCA_DATA_ORIGIN,
      SFRSTCA_ATTEMPT_HR,
      SFRSTCA_RMSG_CDE,
      SFRSTCA_STSP_KEY_SEQUENCE,
      SFRSTCA_BRDH_SEQ_NUM,
      SFRSTCA_BLCK_CODE,
      SFRSTCA_STRH_SEQNO,
      SFRSTCA_STRD_SEQNO,
      SFRSTCA_SURROGATE_ID,
      SFRSTCA_VERSION,
      SFRSTCA_USER_ID,
      SFRSTCA_VPDI_CODE,
      SFRSTCA_SESSIONID,
      SFRSTCA_CURRENT_TIME,
      SFRSTCA_ENRL,
      SFRSTCA_SEATS_AVAIL,
      SHRTCKN_PIDM,
      SHRTCKN_TERM_CODE,
      SHRTCKN_SEQ_NO,
      SHRTCKN_CRN,
      SHRTCKN_SUBJ_CODE,
      SHRTCKN_CRSE_NUMB,
      SHRTCKN_COLL_CODE,
      SHRTCKN_CAMP_CODE,
      SHRTCKN_ACTIVITY_DATE,
      SHRTCKN_SEQ_NUMB,
      SHRTCKN_SURROGATE_ID,
      SHRTCKG_PIDM,
      SHRTCKG_TERM_CODE,
      SHRTCKG_TCKN_SEQ_NO,
      SHRTCKG_SEQ_NO,
      SHRTCKG_FINAL_GRDE_SEQ_NO,
      SHRTCKG_GRDE_CODE_FINAL,
      SHRTCKG_GMOD_CODE,
      SHRTCKG_CREDIT_HOURS,
      SHRTCKG_GCHG_CODE,
      SHRTCKG_FINAL_GRDE_CHG_DATE,
      SHRTCKG_HOURS_ATTEMPTED,
      SHRTCKG_GRDE_CODE_INCMP_FINAL,
      SHRTCKG_SURROGATE_ID,
      SHRTCKG_VERSION,
      SHRTCKG_GCHG_DESC,
      SHRTCKL_PRIMARY_LEVL_IND,
      SHRGRDE_CODE,
      SHRGRDE_LEVL_CODE,
      SHRGRDE_QUALITY_POINTS,
      SHRGRDE_ATTEMPTED_IND,
      SHRGRDE_COMPLETED_IND,
      SHRGRDE_PASSED_IND,
      SHRGRDE_GPA_IND,
      SSBSECT_TERM_CODE,
      SSBSECT_CRN,
      SSBSECT_PTRM_CODE,
      SSBSECT_SUBJ_CODE,
      SSBSECT_CRSE_NUMB,
      SSBSECT_SEQ_NUMB,
      SSBSECT_SSTS_CODE,
      SSBSECT_SCHD_CODE,
      SSBSECT_CAMP_CODE,
      SSBSECT_CREDIT_HRS,
      SSBSECT_BILL_HRS,
      SSBSECT_GMOD_CODE,
      SSBSECT_REG_ONEUP,
      SSBSECT_PRIOR_ENRL,
      SSBSECT_PROJ_ENRL,
      SSBSECT_MAX_ENRL,
      SSBSECT_ENRL,
      SSBSECT_SEATS_AVAIL,
      SSBSECT_TOT_CREDIT_HRS,
      SSBSECT_CENSUS_ENRL,
      SSBSECT_CENSUS_ENRL_DATE,
      SSBSECT_ACTIVITY_DATE,
      SSBSECT_PTRM_START_DATE,
      SSBSECT_PTRM_END_DATE,
      SSBSECT_PTRM_WEEKS,
      SSBSECT_WAIT_CAPACITY,
      SSBSECT_WAIT_COUNT,
      SSBSECT_WAIT_AVAIL,
      SSBSECT_INSM_CODE,
      SSBSECT_SURROGATE_ID,
      SSBSECT_VERSION,
      SSBSECT_SICAS_CAMP_COURSE_ID,
      SSBSECT_SICAS_CAMP_SECTION_ID,
      SCBCRSE_SUBJ_CODE,
      SCBCRSE_CRSE_NUMB,
      SCBCRSE_EFF_TERM,
      SCBCRSE_COLL_CODE,
      SCBCRSE_DIVS_CODE,
      SCBCRSE_DEPT_CODE,
      SCBCRSE_CSTA_CODE,
      SCBCRSE_TITLE,
      SCBCRSE_CIPC_CODE,
      SCBCRSE_CREDIT_HR_IND,
      SCBCRSE_CREDIT_HR_LOW,
      SCBCRSE_CREDIT_HR_HIGH,
      SCBCRSE_LEC_HR_IND,
      SCBCRSE_LEC_HR_LOW,
      SCBCRSE_LEC_HR_HIGH,
      SCBCRSE_BILL_HR_IND,
      SCBCRSE_BILL_HR_LOW,
      SCBCRSE_BILL_HR_HIGH,
      SCBCRSE_ACTIVITY_DATE,
      SCBCRSE_CONT_HR_LOW,
      SCBCRSE_CONT_HR_IND,
      SCBCRSE_CONT_HR_HIGH,
      SCBCRSE_REPS_CODE,
      SCBCRSE_MAX_RPT_UNITS,
      SCBCRSE_SURROGATE_ID,
      SCBCRSE_VERSION,
      SCBCRSE_VPDI_CODE,
      SCBCRSE_SICAS_SUNY_ID,
      SSBSECT_SSTS_DESC,
      SSBSECT_SCHD_DESC,
      SCBCRSE_CSTA_DESC,
      SCBCRSE_REPS_DESC,
      SIRASGN_TERM_CODE,
      SIRASGN_CRN,
      SIRASGN_PIDM,
      SIRDPCL_PIDM,
      SIRDPCL_TERM_CODE_EFF,
      SIRDPCL_COLL_CODE,
      SIRDPCL_DEPT_CODE,
      SIRASGN_PRIMARY_IND,
      SIRDPCL_INSTR_EMAIL,
      SIRDPCL_DEPT_DESC,
      SIRDPCL_INSTR_NAME

  FROM
      STUDENT_LIST_DEMO A

      LEFT OUTER JOIN SHATCKN S1 ON SFRSTCR_PIDM = SPRIDEN_PIDM

      LEFT OUTER JOIN SSASECT SSBSECT ON SSBSECT.SSBSECT_TERM_CODE = S1.SFRSTCR_TERM_CODE
           AND SSBSECT.SSBSECT_CRN = S1.SFRSTCR_CRN

      LEFT OUTER JOIN SIRASGQ SIRASGN ON SIRASGN.SIRASGN_TERM_CODE = SSBSECT.SSBSECT_TERM_CODE
           AND SSBSECT.SSBSECT_CRN = SIRASGN.SIRASGN_CRN
           AND SIRASGN_PRIMARY_IND = 'Y'
  )

SELECT
-- Reporting Use Only
    SPRIDEN_PIDM as Remove_Label_From_Dashboard,
    STVTERM.STVTERM_DESC as TERM_DESC,

-- Systems Info/PII
    SPRIDEN_ID as Banner_ID,
    SPBPERS_PREF_FIRST_NAME Pref_Fname,
    SPRIDEN_LEGAL_NAME as Student_Name,
    SPRIDEN_LAST_NAME as Last_Name,
    SPRIDEN_FIRST_NAME as First_Name,
    SPRIDEN_MI as MI,

-- ID, SUID, EMail
    GORADID_ADDITIONAL_ID as SUID,
    GOREMAL_EMAIL_ADDRESS as Email_Address,

-- Matriculation
    SFRTHST_TMST_CODE as TMST_Code,
    SFRTHST_TMST_DESC as TMST_Desc,
    SGBSTDN_TERM_CODE_EFF as Stdn_Eff_Term,
    SGBSTDN_STST_CODE as Stdn_STST,
    SGBSTDN_STYP_CODE as Stdn_STYP,
    SGBSTDN_LEVL_CODE as Stdn_Level,
    SGBSTDN_CLAS_CODE as Stdn_Class,
    SGBSTDN_DEPT_CODE as Stdn_Dept,
    SGBSTDN_PROGRAM_1 as Stdn_Program,
    SGBSTDN_MAJR_CODE_1 as Stdn_Major,
    SGBSTDN_MAJR_CODE_MINR_1 as Stdn_Minor,
    SGBSTDN_MAJR_CODE_MINR_1_2 as Stdn_Minor_2,
    SGBSTDN_MAJR_CODE_CONC_1 as Stdn_Conc,
    SGBSTDN_DEGC_CODE_1 as Stdn_Degree,
    SGBSTDN_RESD_CODE as Stdn_Residency,
    SGBSTDN_EXP_GRAD_DATE as Stdn_Exp_Grad_Date,
    SGBSTDN_STYP_DESC as Stdn_STYP_Desc,
    SGBSTDN_LEVL_DESC as Stdn_Levl_Desc,
    SGBSTDN_CLAS_DESC as Stdn_Class_Desc,
    SGBSTDN_DEPT_DESC as Stdn_Dept_Desc,
    SGBSTDN_MAJR_DESC as Stdn_Major_Desc,
    SGBSTDN_MINR_1_DESC as Stdn_Minor_Desc,
    SGBSTDN_MINR_1_2_DESC as Stdn_Minor_2_Desc,
    SGBSTDN_CONC_DESC as Stdn_Conc_Desc,
    SGBSTDN_DEGC_DESC as Stdn_Degree_Desc,
    SGBSTDN_RESD_DESC as Stdn_Resd_Desc,

-- Course Enrollment
    SFRSTCR_CRN as Reg_CRN,
    SFRSTCR_REG_SEQ as Reg_Seq_No,
    SFRSTCR_PTRM_CODE as Reg_PTRM,
    SFRSTCR_RSTS_CODE as Reg_RSTS,
    SFRSTCR_BILL_HR as Reg_Bill_Hr,
    SFRSTCR_WAIV_HR as Reg_Waiv_Hr,
    SFRSTCR_CREDIT_HR as Reg_Credit_Hr,
    SFRSTCR_BILL_HR_HOLD as Reg_Bill_Hr_Hold,
    SFRSTCR_CREDIT_HR_HOLD as Reg_Credit_Hr_Hold,
    SFRSTCR_GMOD_CODE as Reg_GMOD_Code,
    SFRSTCR_GRDE_CODE as Reg_Grade_Code,
    SFRSTCR_GRDE_CODE_MID as Reg_Grade_Code_Mid,
    SFRSTCR_GRDE_DATE as Reg_Grade_Date,
    SFRSTCR_ADD_DATE as Reg_Add_Date,
    SFRSTCR_ACTIVITY_DATE as Reg_Activity,
    SFRSTCR_LEVL_CODE as Reg_Levl_Code,
    SFRSTCR_CAMP_CODE as Reg_Camp_Code,

-- Registration Audit
    SFRSTCA_TERM_CODE as Audit_Term,
    SFRSTCA_CRN as Audit_CRN,
    SFRSTCA_SEQ_NUMBER as Audit_Seq_No,
    SFRSTCA_LEVL_CODE as Audit_Levl_Code,
    SFRSTCA_CAMP_CODE as Audit_Camp_Code,
    SFRSTCA_ADD_DATE as Add_Date,
    SFRSTCA_ACTIVITY_DATE as Audit_Activity,
    SFRSTCA_RSTS_CODE as Audit_RSTS,
    SFRSTCA_RSTS_DATE as Audit_RSTS_Date,
    SFRSTCA_ERROR_FLAG as Error_Flag,
    SFRSTCA_MESSAGE as Message,
    SFRSTCA_CREDIT_HR as Audit_Credit_Hr,
    SFRSTCA_GMOD_CODE as Audit_GMOD_Code,
    SFRSTCA_ATTEMPT_HR as Audit_Attempt_Hr,
    SFRSTCA_RMSG_CDE as Audit_RMSG,
    SFRSTCA_ENRL as Audit_Enrolled,
    SFRSTCA_SEATS_AVAIL as Audit_Seat_Avail,

-- Class Details
    SHRTCKN_TERM_CODE as Class_Term_Code,
    SHRTCKN_SEQ_NO as Class_Seq_No,
    SHRTCKN_CRN as Class_CRN,
    SHRTCKN_SUBJ_CODE as Class_Subj,
    SHRTCKN_CRSE_NUMB as Class_Numb,
    SHRTCKN_COLL_CODE as Class_Coll_Code,
    SHRTCKN_CAMP_CODE as Class_Camp_Code,
    SHRTCKN_ACTIVITY_DATE as Class_Activity,
    SHRTCKN_SEQ_NUMB as Class_Seq_No,

-- Recorded Course Grades
    SHRTCKG_TERM_CODE as Grade_Term_Code,
    SHRTCKG_TCKN_SEQ_NO as Final_Grade_TCKN_Seq_No,
    SHRTCKG_SEQ_NO as Final_Grade_Seq_No,
    SHRTCKG_FINAL_GRDE_SEQ_NO as Final_Grade_Final_Grade_Seq_No,
    SHRTCKG_GRDE_CODE_FINAL as Final_Grade_Code_Final,
    SHRTCKG_GMOD_CODE as Final_Grade_GMOD_Code,
    SHRTCKG_CREDIT_HOURS as Final_Grade_Credit_Hr,
    SHRTCKG_GCHG_CODE as Final_Grade_GCHG_Code,
    SHRTCKG_FINAL_GRDE_CHG_DATE as Final_Grade_Change_Date,
    SHRTCKG_HOURS_ATTEMPTED as Final_Grade_Credit_Hr,
    SHRTCKL_PRIMARY_LEVL_IND as Primary_Levl_Ind,

-- Grade Codes Valuation
    SHRGRDE_CODE as Grade_Code,
    SHRGRDE_LEVL_CODE as Grade_Levl_Code,
    SHRGRDE_QUALITY_POINTS as Grade_Quality_Points,
    SHRGRDE_ATTEMPTED_IND as Attempted_Ind,
    SHRGRDE_COMPLETED_IND as Competed_Ind,
    SHRGRDE_PASSED_IND as Passed_Ind,
    SHRGRDE_GPA_IND as GPA_Ind,

-- Departmental Instructor Info
    SIRASGN_TERM_CODE as Instructor_Term_Code,
    SIRASGN_CRN as Instructor_CRN,
    SIRDPCL_TERM_CODE_EFF as Dept_Eff_Term,
    SIRDPCL_COLL_CODE as Dept_Coll_Code,
    SIRDPCL_DEPT_CODE as Dept_Code,
    SIRASGN_PRIMARY_IND as Dept_Prim_Ind,
    SIRDPCL_DEPT_DESC as Dept_Desc,
    SIRDPCL_INSTR_NAME as Dept_Instr_Name,
    SIRDPCL_INSTR_EMAIL as Dept_Instr_Email,

-- Course Section Info
    SSBSECT_TERM_CODE as Section_Term_Code,
    SSBSECT_CRN as Section_CRN,
    SSBSECT_PTRM_CODE as Section_PTRM,
    SSBSECT_SUBJ_CODE as Section_Subj,
    SSBSECT_CRSE_NUMB as Section_Numb,
    SSBSECT_SEQ_NUMB as Section_Seq_No,
    SSBSECT_SSTS_CODE as Section_SSTS_Code,
    SSBSECT_SCHD_CODE as Section_SCHD_Code,
    SSBSECT_CAMP_CODE as Section_Camp_Code,
    SSBSECT_CREDIT_HRS as Section_Credit_Hr,
    SSBSECT_BILL_HRS as Section_Bill_Hr,
    SSBSECT_GMOD_CODE as Section_GMOD_Code,
    SSBSECT_REG_ONEUP as Section_Reg_Oneup,
    SSBSECT_PRIOR_ENRL as Section_Prior_Enrl,
    SSBSECT_PROJ_ENRL as Section_Proj_Enrl,
    SSBSECT_MAX_ENRL as Section_Max_Enrl,
    SSBSECT_ENRL as Section_Enrl,
    SSBSECT_SEATS_AVAIL as Section_Seats_Avail,
    SSBSECT_TOT_CREDIT_HRS as Section_Tot_Credit_Hr,
    SSBSECT_CENSUS_ENRL as Section_Census_Enrl,
    SSBSECT_CENSUS_ENRL_DATE as Section_Census_Enrl_Date,
    SSBSECT_ACTIVITY_DATE as Section_Activity,
    SSBSECT_PTRM_START_DATE as Section_PTRM_Start_Date,
    SSBSECT_PTRM_END_DATE as Section_PTRM_End_Date,
    SSBSECT_PTRM_WEEKS as Section_PTRM_Weeks,
    SSBSECT_WAIT_CAPACITY as Section_Wait_Capactiy,
    SSBSECT_WAIT_COUNT as Section_Wait_Count,
    SSBSECT_WAIT_AVAIL as Section_Wait_Avail,
    SSBSECT_INSM_CODE as Section_INSM_Code,
    SSBSECT_SICAS_CAMP_COURSE_ID as SICAS_Course_ID,
    SSBSECT_SICAS_CAMP_SECTION_ID as SICAS_Section_ID,
    SCBCRSE_SUBJ_CODE as Course_Subj,
    SCBCRSE_CRSE_NUMB as Course_Numb,
    SCBCRSE_EFF_TERM as Course_Eff_Term,
    SCBCRSE_COLL_CODE as Course_Coll_Code,
    SCBCRSE_DIVS_CODE as Course_DIVS_Code,
    SCBCRSE_DEPT_CODE as Course_Dept,
    SCBCRSE_CSTA_CODE as Course_Active,
    SCBCRSE_TITLE as Course_Title,
    SCBCRSE_CIPC_CODE as Course_CIPC_Code,
    SCBCRSE_CREDIT_HR_IND as Course_Credit_Hr_Ind,
    SCBCRSE_CREDIT_HR_LOW as Course_Credit_Hr_Low,
    SCBCRSE_CREDIT_HR_HIGH as Course_Credit_Hr_Low,
    SCBCRSE_LEC_HR_IND as Course_LEC_HR_Ind,
    SCBCRSE_LEC_HR_LOW as Course_LEC_HR_Low,
    SCBCRSE_LEC_HR_HIGH as Course_LEC_HR_High,
    SCBCRSE_BILL_HR_IND as Course_BILL_HR_Ind,
    SCBCRSE_BILL_HR_LOW as Course_BILL_HR_Low,
    SCBCRSE_BILL_HR_HIGH as Course_BILL_HR_High,
    SCBCRSE_ACTIVITY_DATE as Course_Activity,
    SCBCRSE_CONT_HR_LOW as Course_Cont_HR_Low,
    SCBCRSE_CONT_HR_IND as Course_Cont_HR_Ind,
    SCBCRSE_CONT_HR_HIGH as Course_Cont_HR_High,
    SCBCRSE_REPS_CODE as Course_Reps_Code,
    SCBCRSE_MAX_RPT_UNITS as Course_Max_Repeat_Units,
    SCBCRSE_VPDI_CODE as Course_VPDI_Code,
    SCBCRSE_SICAS_SUNY_ID as Course_SICAS_SUNY_ID,
    SSBSECT_SSTS_DESC as Section_SSTS_Desc,
    SSBSECT_SCHD_DESC as Section_SCHD_Desc,
    SCBCRSE_CSTA_DESC as Course_CSTA_Desc,
    SCBCRSE_REPS_DESC as Course_REPS_Desc,

-- Sorting
    STVCLAS_SURROGATE_ID

FROM
    STUDENT_GRADE_LIST B
    LEFT OUTER JOIN STVTERM STVTERM ON STVTERM.STVTERM_CODE = :select_term_code.STVTERM_CODE

WHERE
    NULL IS NULL

      -- STUDENT CONDITIONS

    AND SGBSTDN_STST_CODE = 'AS'

      -- ENROLLMENT CONDITIONS

    AND 'Y' = F_REGISTERED_THIS_TERM(SPRIDEN_PIDM, :select_term_code.STVTERM_CODE)

    -- general use

    AND SSBSECT_TERM_CODE = SFRSTCR_TERM_CODE

    -- grade roster(001)
    /*
    AND SFRSTCR_TERM_CODE = :select_term_code.STVTERM_CODE
    --AND SFRSTCR_GRDE_CODE is NOT NULL
    --AND SFRSTCR_GRDE_CODE_MID is NOT NULL
    --AND SHRTCKG_GRDE_CODE_FINAL is NOT NULL
    */

    -- missing grade (004)
    /*
    AND SFRSTCR_TERM_CODE = :select_term_code.STVTERM_CODE
    --AND SFRSTCR_GRDE_CODE IS NULL
    --AND SFRSTCR_GRDE_CODE_MID is NULL
    --AND SHRTCKG_GRDE_CODE_FINAL is NULL
    */

    -- unsatisfactory grade (005)
    /*
    AND SFRSTCR_TERM_CODE = :select_term_code.STVTERM_CODE
    --AND SFRSTCR_GRDE_CODE in ('U', 'IU')
    --AND SFRSTCR_GRDE_CODE_MID in ('U', 'IU')
    --AND SHRTCKG_GRDE_CODE_FINAL in ('U', 'IU')
    */

    -- failing grade (006)
    /*
    AND SFRSTCR_TERM_CODE = :select_term_code.STVTERM_CODE
    --AND SFRSTCR_GRDE_CODE in ('WF','F')
    --AND SFRSTCR_GRDE_CODE_MID in ('WF','F')
    --AND SHRTCKG_GRDE_CODE_FINAL in ('WF','F')
    */

    -- grade of 'I' (007)
    /*
    AND SFRSTCR_TERM_CODE = :select_term_code.STVTERM_CODE
    --AND SFRSTCR_GRDE_CODE in ('IF','I')
    --AND SFRSTCR_GRDE_CODE_MID in ('IF','I')
    --AND SHRTCKG_GRDE_CODE_FINAL in ('IF','I')
    */

    -- graduate student grade of 'D' (013)
    /*
    AND SGBSTDN_LEVL_CODE = 'GR'
    AND SFRSTCR_TERM_CODE = :select_term_code.STVTERM_CODE
    --AND SFRSTCR_GRDE_CODE in ('D')
    --AND SFRSTCR_GRDE_CODE_MID in ('D')
    --AND SHRTCKG_GRDE_CODE_FINAL in ('D')
    */

    -- compete grade history (016)
    /*
    AND SFRSTCR_TERM_CODE <= :select_term_code.STVTERM_CODE
    --AND SFRSTCR_GRDE_CODE IS NOT NULL
    --AND SFRSTCR_GRDE_CODE_MID IS NOT NULL
    --AND SHRTCKG_GRDE_CODE_FINAL IS NOT NULL
    */

/*
   STVTERM.STVTERM_CODE = :select_term_code.STVTERM_CODE
   and SHRTCKN.SHRTCKN_TERM_CODE = STVTERM.STVTERM_CODE
   and SHRTCKN.SHRTCKN_CRN = SFRSTCR.SFRSTCR_CRN
   and SGBSTDN_TERM_CODE_EFF = fy_sgbstdn_eff_term(SGBSTDN_PIDM, STVTERM_CODE)
   and f_registered_this_term(SPRIDEN.SPRIDEN_PIDM, STVTERM.STVTERM_CODE) = 'Y'
   and SGBSTDN_STST_CODE = 'AS'
        and
        (
            not exists
            (
                       select *
                       from SFRWDRL SFRWDRL
                       where SFRWDRL.SFRWDRL_PIDM = SPRIDEN.SPRIDEN_PIDM
                       and SFRWDRL.SFRWDRL_TERM_CODE = SGBSTDN.SGBSTDN_TERM_CODE_EFF
                           )
                )

/*
passed - 01
SFRSTCR_TERM_CODE = STVTERM.STVTERM_CODE
and SHRTCKG_GRDE_CODE_FINAL = :select_grade_code.GRADECODE
*/
/*
04
SFRSTCR.SFRSTCR_TERM_CODE <= STVTERM.STVTERM_CODE

and(
    SFRSTCR_GRDE_CODE is null
    or SFRSTCR_GRDE_CODE in ('NR')
    or SHRTCKG_GRDE_CODE_FINAL is null
)
*/
/*
05
SFRSTCR.SFRSTCR_TERM_CODE <= STVTERM.STVTERM_CODE
and(
        SFRSTCR.SHRTCKG_GRDE_CODE_FINAL in(
            select SHRTCKG.SHRTCKG_GRDE_CODE_FINAL
            from SHRTCKG SHRTCKG
            where SHRTCKG.SHRTCKG_PIDM = SPRIDEN.SPRIDEN_PIDM
            and SHRTCKG.SHRTCKG_TERM_CODE = SFRSTCR.SHRTCKN_TERM_CODE
            and SHRTCKG.SHRTCKG_GRDE_CODE_FINAL in ('U', 'I', 'IF', 'IU')
            group by SHRTCKG.SHRTCKG_GRDE_CODE_FINAL
            having count(*)> 1
        )
    )
    and STVCLAS.STVCLAS_CODE in ('AG','BG') -- grads only!

*/
/*
06
SFRSTCR.SFRSTCR_TERM_CODE <= STVTERM.STVTERM_CODE
and (
    SFRSTCR.SFRSTCR_GRDE_CODE in ('WF','F')
    or SFRSTCR.SHRTCKG_GRDE_CODE_FINAL in ('WF','F')
       )
*/
/*
07
SFRSTCR.SFRSTCR_TERM_CODE <= STVTERM.STVTERM_CODE
and SFRSTCR.SHRTCKG_GRDE_CODE_FINAL in ('I')
and SFRSTCR.SFRSTCR_RSTS_CODE = 'RE'
--SFRSTCR.SFRSTCR_TERM_CODE = STVTERM.STVTERM_CODE
--and SFRSTCR.SHRTCKG_GRDE_CODE_FINAL in ('IF','I')
and SFRSTCR.SIRDPCL_SURROGATE_ID = (select max(SIRDPCL_SURROGATE_ID)
                                   from SIRDPCL SIRDPCLX
                                   where SIRDPCLX.SIRDPCL_PIDM = SFRSTCR.SIRDPCL_PIDM)
*/
/*
08
SFRSTCR.PREV_TERM_CODE != SFRSTCR.SFRSTCR_TERM_CODE
and SFRSTCR.SUBJ_CODE = SFRSTCR.SSBSECT_SUBJ_CODE
and SFRSTCR.CRSE_NUMB = SFRSTCR.SSBSECT_CRSE_NUMB
and SFRSTCR.PASSED_IND = 0
and SFRSTCR.COMPLETE_IND = 0

*/
/*
012
SFRSTCR.PREV_TERM_CODE != SFRSTCR.SFRSTCR_TERM_CODE
and SFRSTCR.SUBJ_CODE = SFRSTCR.SSBSECT_SUBJ_CODE
and SFRSTCR.CRSE_NUMB = SFRSTCR.SSBSECT_CRSE_NUMB
and SFRSTCR.PREV_GRDE_CODE not in ( 'F', 'I', 'IF', 'IU', 'NR', 'U', 'UAU', 'V', 'W', 'WF')
*/
/*
013
SFRSTCR.SFRSTCR_TERM_CODE <= STVTERM.STVTERM_CODE
and SGBSTDN.SGBSTDN_LEVL_CODE = 'GR'
and (
    SFRSTCR.SFRSTCR_GRDE_CODE = 'D'
    or SHRTCKG_GRDE_CODE_FINAL = 'D'
       )
*/
/*
SFRSTCR.SFRSTCR_GRDE_CODE is not null
and SFRSTCR.SHRTCKG_GRDE_CODE_FINAL is not null
*/
/*
repeat as
 (select a.shrtckg_pidm pidm,
         shrtckn_subj_code subj,
         shrtckn_crse_numb crse,
         shrtckn_subj_code || shrtckn_crse_numb clas
    from shrtckg a, shrtckn
   where a.shrtckg_pidm = shrtckn_pidm
     and a.shrtckg_term_code = shrtckn_term_code
     and a.shrtckg_tckn_seq_no = shrtckn_seq_no
     and a.shrtckg_seq_no =
         (select max(b.shrtckg_seq_no)
            from shrtckg b
           where b.shrtckg_pidm = a.shrtckg_pidm
             and b.shrtckg_term_code = a.shrtckg_term_code
             and b.shrtckg_tckn_seq_no = a.shrtckg_tckn_seq_no)
     and shrtckn_term_code >= '202120'
   group by shrtckg_pidm,
            shrtckn_subj_code,
            shrtckn_crse_Numb,
            shrtckn_subj_code || shrtckn_crse_numb
  having count(shrtckn_subj_code || shrtckn_crse_numb) > 1
   order by shrtckg_pidm, shrtckn_subj_code || shrtckn_crse_numb)
*/

/*
life try this:
exists(select * from sfrstcr, ssbsect where sfrstcr_pidm = spriden_pidm
and sfrstcr_term_code < :select_term_code.STVTERM_CODE
and ssbsect_crn = )
*/
--$addfilter

--$beginorder

ORDER BY
    1

--$endorder
