SSBSECT_SICAS_CAMP_COURSE_ID = :select_course_key.course_key
and SGBSTDN_MAJR_CODE_1 = 'SUS'

ORDER BY
    SSBSECT_TERM_CODE,
    SSBSECT_SUBJ_CODE,
    SSBSECT_CRSE_NUMB,
    SPRIDEN_SEARCHH_LAST_NAME,
    SPRIDEN_FIRST_NAME