-- aidy selection
select DISTINCT RPRAWRD_AIDY_CODE AS CODE FROM RPRAWRD
ORDER BY RPRAWRD_AIDY_CODE DESC

-- registration status
SELECT STVSTST_CODE AS CODE,
       STVSTST_DESC AS DESCR,
       STVSTST_REG_IND AS ALLOW_REG,
       STVSTST_CSTS_CODE AS CSTS,
       STVSTST_ACTIVITY_DATE AS ACTIVITY
FROM STVSTST
ORDER BY STVSTST_CODE

-- fund code
select DISTINCT RFRBASE_FUND_CODE AS CODE, RFRBASE_FUND_TITLE AS TITLE
FROM RFRBASE
ORDER BY RFRBASE_FUND_CODE