SELECT SPRIDEN_ID AS BannerID,
       SPRIDEN_LAST_NAME AS LastName,
       SPRIDEN_FIRST_NAME AS FirstName,
       RPRAWRD_OFFER_AMT AS OFFER_AMT,
       RPRAWRD_ACCEPT_AMT AS ACCEPT_AMT,
       RPRAWRD_DECLINE_AMT AS DECLINE_AMT,
       RPRAWRD_CANCEL_AMT AS CANCEL_AMT,
       RPRAWRD_AUTHORIZE_AMT AS AUTHORIZE_AMT,
       RPRAWRD_MEMO_AMT AS MEMO_AMT,
       RPRAWRD_PAID_AMT AS PAID_AMT,
       e.goremal_email_address AS SU_EMAIL,
       pe.goremal_email_address as PERS_EMAIL
FROM   RPRAWRD
INNER JOIN SPRIDEN ON (RPRAWRD_PIDM=SPRIDEN_PIDM)
--INNER JOIN RPRATRM ON (RPRAWRD_PIDM=RPRATRM_PIDM)
INNER JOIN SGBSTDN ON (RPRAWRD_PIDM=SGBSTDN_PIDM)
LEFT OUTER JOIN GOREMAL e on (spriden.spriden_pidm=e.goremal_pidm and e.goremal_emal_code='SU' and e.goremal_preferred_ind='Y')
LEFT OUTER JOIN GOREMAL pe on (spriden.spriden_pidm=pe.goremal_pidm and pe.goremal_emal_code='PERS' and pe.goremal_status_ind='A')
WHERE SPRIDEN_CHANGE_IND IS NULL
and RPRAWRD_AIDY_CODE=:selAidY.CODE
and RPRAWRD_FUND_CODE=:selFund.CODE
and SGBSTDN_STST_CODE=:selStudentStatus.CODE
and SGBSTDN_TERM_CODE_EFF IN (SELECT MAX(b.SGBSTDN_TERM_CODE_EFF) FROM SGBSTDN b where RPRAWRD_PIDM=b.SGBSTDN_PIDM and b.SGBSTDN_STST_CODE=:selStudentStatus.CODE)