EXISTS(
SELECT *
FROM SHRDGMR
WHERE SHRDGMR_PIDM = SPRIDEN_PIDM
AND SHRDGMR_ACYR_CODE = :select_term_code.STVTERM_ACYR_CODE
AND SHRDGMR_DEGS_CODE IN (SELECT STVDEGS_CODE FROM STVDEGS))
AND SGBSTDN_STYP_CODE <> 'X'

ORDER BY
    SPRIDEN_LAST_NAME,
    SPRIDEN_FIRST_NAME,
    SPRIDEN_MI