-- aidy selection
select DISTINCT RPRAWRD_AIDY_CODE AS CODE FROM RPRAWRD
ORDER BY RPRAWRD_AIDY_CODE DESC

-- category
SELECT DISTINCT RFRFCAT_FCAT_CODE as FCAT FROM RFRFCAT
ORDER BY RFRFCAT_FCAT_CODE

-- registered status
SELECT STVSTST_CODE AS CODE,
       STVSTST_DESC AS DESCR,
       STVSTST_REG_IND AS ALLOW_REG,
       STVSTST_CSTS_CODE AS CSTS,
       STVSTST_ACTIVITY_DATE AS ACTIVITY
FROM STVSTST
ORDER BY STVSTST_CODE

-- fund codes
select DISTINCT RFRBASE_FUND_CODE AS CODE, RFRBASE_FUND_TITLE AS TITLE
FROM RFRBASE
INNER JOIN RFRFCAT ON (RFRBASE_FUND_CODE=RFRFCAT_FUND_CODE)
WHERE RFRFCAT_FCAT_CODE = :selCategory.FCAT
ORDER BY RFRBASE_FUND_CODE

-- validation
SELECT * FROM RPRAWRD WHERE RPRAWRD_PIDM=:selList.PIDM

-- validation results
SELECT * FROM RPRATRM WHERE RPRATRM_PIDM=:selList.PIDM