-- min term selection
select STVTERM_CODE AS CODE, STVTERM_DESC AS DESCR
FROM STVTERM
WHERE STVTERM_START_DATE > SYSDATE -130 AND STVTERM_START_DATE < SYSDATE + 130
--and substr(stvterm_code,5,1) in ('2','4')
ORDER BY STVTERM_CODE DESC

-- max term selection
select STVTERM_CODE AS CODE, STVTERM_DESC AS DESCR
FROM STVTERM
WHERE STVTERM_START_DATE > SYSDATE -130 AND STVTERM_START_DATE < SYSDATE + 130
--and substr(stvterm_code,5,1) in ('2','4')
ORDER BY STVTERM_CODE DESC

-- dept selection
select STVDEPT_CODE AS DEPT, STVDEPT_DESC AS DEPT_DESCRIPTION
from stvdept
WHERE STVDEPT_CODE NOT IN ('0000','BIOC','CHEM','ENSC','LIB','SU')
AND STVDEPT_DESC <> 'DO NOT USE'
ORDER BY STVDEPT_CODE

--apdc seelctino
SELECT * FROM
(select STVAPDC_CODE AS APDC, STVAPDC_DESC AS DESCR from STVAPDC
UNION
SELECT 'AX' AS APDC, 'No Appl or Decision' as DESCR from DUAL
UNION
SELECT 'EN' AS APDC, 'Enrolled Continuing' AS DESCR from DUAL
)
WHERE
(CASE WHEN :chkNormalAPDC <> 1 THEN 1
      WHEN :chkNormalAPDC = 1 THEN CASE WHEN APDC IN ('AC','AP','CF','EN') THEN 1 ELSE 0 END
      ELSE 1 END) = 1
ORDER BY APDC