-- Term Selection
select STVTERM.STVTERM_CODE,
       STVTERM.STVTERM_DESC,
(STVTERM.STVTERM_CODE || ' - ' ||
       STVTERM.STVTERM_DESC) as TermDesc
        from SATURN.STVTERM STVTERM
        where stvterm_start_date < sysdate + 365

 order by STVTERM.STVTERM_CODE desc

 -- instructor selection
   SELECT
      SIRASGN.SIRASGN_TERM_CODE,
      SIRASGN.SIRASGN_CRN,
      SIRASGN.SIRASGN_PIDM,
      SIRDPCL.SIRDPCL_PIDM,
      SIRDPCL.SIRDPCL_TERM_CODE_EFF,
      SIRDPCL.SIRDPCL_COLL_CODE,
      SIRDPCL.SIRDPCL_DEPT_CODE,
      SIRASGN.SIRASGN_PRIMARY_IND,
      GOREMAL.GOREMAL_EMAIL_ADDRESS as SIRDPCL_INSTR_EMAIL,
      f_format_name(SIRDPCL.SIRDPCL_PIDM, 'LF30') as SIRDPCL_INSTR_NAME,
      (SELECT SPRIDEN_ID FROM SPRIDEN WHERE SPRIDEN_PIDM = SIRASGN_PIDM AND SPRIDEN_CHANGE_IND IS NULL AND SPRIDEN_NTYP_CODE IS NULL) as BANNER_ID_INSTR,
      sirasgn.*

  FROM
      SIRASGN SIRASGN
      LEFT OUTER JOIN SIRDPCL SIRDPCL ON SIRDPCL.SIRDPCL_PIDM = SIRASGN.SIRASGN_PIDM
           AND SIRDPCL.SIRDPCL_SURROGATE_ID = (SELECT MAX(SIRDPCL_SURROGATE_ID)
                                              FROM    SIRDPCL SIRDPCL1
                                              WHERE   SIRDPCL1.SIRDPCL_PIDM = SIRDPCL.SIRDPCL_PIDM)

      LEFT OUTER JOIN GOREMAL GOREMAL ON GOREMAL.GOREMAL_PIDM = SIRDPCL_PIDM
           AND GOREMAL.GOREMAL_EMAL_CODE = 'ESF'
           AND GOREMAL.GOREMAL_STATUS_IND = 'A'
           AND GOREMAL.GOREMAL_PREFERRED_IND = 'Y'

  WHERE
      SIRASGN_PRIMARY_IND = 'Y'
      AND SIRASGN_TERM_CODE = :ddSemester.STVTERM_CODE

  ORDER BY
      SIRDPCL_INSTR_NAME