SELECT
      SSBSECT.SSBSECT_SUBJ_CODE as subj_code,
      SSBSECT.SSBSECT_CRSE_NUMB as crse_numb,
      SSBSECT.SSBSECT_CRN as crn,
      SSBSECT.SSBSECT_SICAS_CAMP_COURSE_ID as CourseKey,
      SSBSECT.SSBSECT_SEQ_NUMB as seq_numb,
      SCBCRSE.SCBCRSE_TITLE as crse_title,
      F_FORMAT_NAME(SIRDPCL.SIRDPCL_PIDM, 'LF30') AS PrimaryInstrName,
      SPRIDEN.SPRIDEN_ID as id,
      SPRIDEN.SPRIDEN_LAST_NAME || ', ' || coalesce(SPBPERS.SPBPERS_PREF_FIRST_NAME, SPRIDEN.SPRIDEN_FIRST_NAME) || ' ' || SPRIDEN.SPRIDEN_MI as StudentName,
      GORADID.GORADID_ADDITIONAL_ID as SUID,
      f_get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_1, 30) as ProgramOfStudy,
      f_get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_1, 30) ||' ('||SGBSTDN.SGBSTDN_MAJR_CODE_1 || ')' as MajorProgDesc,
      SGBSTDN_PROGRAM_1 as Stdn_Program,
      GOREMAL.GOREMAL_EMAIL_ADDRESS as email,
      SPBPERS.SPBPERS_PREF_FIRST_NAME pref_fname,
      SPRIDEN.SPRIDEN_FIRST_NAME fname,
      SPRIDEN.SPRIDEN_MI mname,
      SPRIDEN.SPRIDEN_LAST_NAME lname,
      SFRSTCR.SFRSTCR_RSTS_CODE as sfrstcr_rsts_code,
      SFRSTCR.SFRSTCR_CREDIT_HR as sfrstcr_credit_hr

FROM SSBSECT SSBSECT

     JOIN STVTERM STVTERM ON STVTERM.STVTERM_CODE = :ddSemester.STVTERM_CODE
/*
Current_term_code_fnc
     JOIN STVTERM STVTERM ON STVTERM.STVTERM_CODE = (SELECT MAX(STVTERM_CODE)
                                FROM STVTERM STVTERMX
                                WHERE STVTERMX.STVTERM_CODE IS NOT NULL
                                AND STVTERMX.STVTERM_END_DATE <= SYSDATE)
*/
     JOIN SCBCRSE SCBCRSE ON SCBCRSE.SCBCRSE_SUBJ_CODE = SSBSECT.SSBSECT_SUBJ_CODE
          AND SCBCRSE.SCBCRSE_CRSE_NUMB = SSBSECT.SSBSECT_CRSE_NUMB
          AND SCBCRSE.SCBCRSE_EFF_TERM = (SELECT MAX(SCBCRSE.SCBCRSE_EFF_TERM)
                                         FROM SCBCRSE SCBCRSEX
                                         WHERE SCBCRSEX.SCBCRSE_SUBJ_CODE = SSBSECT.SSBSECT_SUBJ_CODE
                                         AND SCBCRSEX.SCBCRSE_CRSE_NUMB = SSBSECT.SSBSECT_CRSE_NUMB
                                         AND SCBCRSEX.SCBCRSE_EFF_TERM <= SSBSECT.SSBSECT_TERM_CODE
                                   )

     LEFT OUTER JOIN SIRASGN SIRASGN ON SIRASGN.SIRASGN_TERM_CODE = SSBSECT.SSBSECT_TERM_CODE
          AND SIRASGN.SIRASGN_CRN = SSBSECT.SSBSECT_CRN
          AND SIRASGN.SIRASGN_CATEGORY = 01

     LEFT OUTER JOIN SIRDPCL SIRDPCL ON SIRDPCL.SIRDPCL_PIDM = SIRASGN.SIRASGN_PIDM

     LEFT OUTER JOIN SFRSTCR SFRSTCR ON SFRSTCR.SFRSTCR_TERM_CODE = SSBSECT.SSBSECT_TERM_CODE
          AND SFRSTCR.SFRSTCR_CRN = SSBSECT.SSBSECT_CRN

     JOIN SPRIDEN SPRIDEN ON SPRIDEN.SPRIDEN_PIDM = SFRSTCR.SFRSTCR_PIDM
          AND SPRIDEN.SPRIDEN_NTYP_CODE IS NULL
          AND SPRIDEN.SPRIDEN_CHANGE_IND IS NULL

     JOIN SPBPERS SPBPERS ON SPBPERS.SPBPERS_PIDM = SPRIDEN.SPRIDEN_PIDM

     LEFT OUTER JOIN GOREMAL GOREMAL ON GOREMAL.GOREMAL_PIDM = SPRIDEN.SPRIDEN_PIDM
          AND GOREMAL.GOREMAL_EMAL_CODE = 'SU'

     LEFT OUTER JOIN GORADID GORADID ON GORADID.GORADID_PIDM = SPRIDEN.SPRIDEN_PIDM
          AND GORADID.GORADID_ADID_CODE = 'SUID'

     INNER JOIN SGBSTDN SGBSTDN ON SGBSTDN.SGBSTDN_PIDM = SPRIDEN.SPRIDEN_PIDM
           AND SGBSTDN.SGBSTDN_TERM_CODE_EFF = FY_SGBSTDN_EFF_TERM(SPRIDEN.SPRIDEN_PIDM, STVTERM.STVTERM_CODE)

WHERE
     SSBSECT.SSBSECT_TERM_CODE = STVTERM.STVTERM_CODE
     AND SIRDPCL.SIRDPCL_PIDM <> 0
     AND SIRDPCL.SIRDPCL_TERM_CODE_EFF = (SELECT MAX(SIRDPCL_TERM_CODE_EFF)
                                          FROM SIRDPCL SIRDPCLX
                                          WHERE SIRDPCLX.SIRDPCL_PIDM = SIRDPCL.SIRDPCL_PIDM)

--AND SIRDPCL.SIRDPCL_PIDM = :main_EB_id
and ('-All-' = :MultiColumn1.SUBJ
  or ('-All-' <> :MultiColumn1.SUBJ
    and SSBSECT.SSBSECT_SUBJ_CODE = :MultiColumn1.SUBJ))
and ('-All-' = :MultiColumn1.CRSE
  or ('-All-' <> :MultiColumn1.CRSE
    and SSBSECT.SSBSECT_CRSE_NUMB = :MultiColumn1.CRSE))
and SFRSTCR.sfrstcr_rsts_code = 'RE'

--$addfilter

--$beginorder

ORDER BY
SSBSECT.SSBSECT_SICAS_CAMP_COURSE_ID,
SPRIDEN.SPRIDEN_SEARCH_LAST_NAME,
SPRIDEN.SPRIDEN_SEARCH_FIRST_NAME

--$endorder
