EXISTS (SELECT * FROM SFAREGS WHERE SFRSTCR_PIDM = SPRIDEN_PIDM AND SFRSTCR_TERM_CODE = :select_term_code.STVTERM_CODE AND SFRSTCR_RSTS_CODE IN (SELECT STVRSTS_CODE FROM STVRSTS))
AND EXISTS (SELECT * FROM SGASTDN WHERE SGBSTDN_PIDM = SPRIDEN_PIDM AND SGBSTDN_TERM_CODE_EFF = FY_SGBSTDN_EFF_TERM(SPRIDEN_PIDM, :select_term_code.STVTERM_CODE) AND SFRTHST_TMST_CODE = 'PT' AND SGBSTDN_STYP_CODE <> 'X')

ORDER BY
    SPRIDEN_LAST_NAME,
    SPRIDEN_FIRST_NAME,
    SPRIDEN_MI