SARAPPD.SARAPPD_APDC_CODE = :select_apdc_code.SAAADMS_APDC_CODE
and SGBSTDN.SGBSTDN_STYP_CODE = :select_styp_code.SGASTDN_STYP_CODE
and SGBSTDN.SGBSTDN_MAJR_CODE_1 = :select_majr_code.SGASTDN_MAJR_CODE