-- DATABASE ACCESS
select DBA_USERS.USERNAME "USERNAME",
       SPRIDEN.SPRIDEN_ID "BANNER_ID",
       DECODE (NVL (SPBPERS.SPBPERS_PREF_FIRST_NAME, SPRIDEN.SPRIDEN_FIRST_NAME),
              NULL, NULL,
                    NVL (SPBPERS.SPBPERS_PREF_FIRST_NAME, SPRIDEN.SPRIDEN_FIRST_NAME) || ' ')
       || SPRIDEN.SPRIDEN_LAST_NAME "NAME",
       DBA_USERS.ACCOUNT_STATUS "ACCOUNT_STATUS",
       DBA_USERS.LOCK_DATE "LOCK_DATE",
       DBA_USERS.EXPIRY_DATE "EXPIRY_DATE",
       to_date (to_char (DBA_USERS.CREATED, 'MM/DD/YYYY'), 'MM/DD/YYYY') "CREATED",
       DBA_USERS.PASSWORD_VERSIONS "PWD_TYPE",
       GURLOGN.GURLOGN_INB_LAST_LOGON_DATE "LAST_LOGIN"
  from SYS.DBA_USERS DBA_USERS,
       GOBEACC,
       SPRIDEN SPRIDEN,
       GURLOGN,
       SATURN.SPBPERS SPBPERS
 where ( DBA_USERS.USERNAME = GOBEACC.GOBEACC_USERNAME (+)
         and GOBEACC.GOBEACC_PIDM = SPRIDEN.SPRIDEN_PIDM (+)
         and DBA_USERS.USERNAME = GURLOGN.GURLOGN_USER (+)
         and GOBEACC.GOBEACC_PIDM = SPBPERS.SPBPERS_PIDM (+) )
   and ( DBA_USERS.USERNAME like Upper (:frmMain_eb_UserName) || '%'
         and DBA_USERS.ACCOUNT_STATUS like :frmMain_dd_AccountStatus.AccountStatus
         and SPRIDEN.SPRIDEN_CHANGE_IND is null )
 order by DBA_USERS.USERNAME

 -- SECURITY CLASS
 select distinct GURUCLS.GURUCLS_CLASS_CODE "Class",
       '  --assigned via class--  ' "SecurityGroup"
  from BANSECR.GURUCLS GURUCLS
 where GURUCLS.GURUCLS_USERID = :frmMain_mc_UserAcctData.USERNAME
union
select distinct GURCGRP.GURCGRP_CLASS,
       GURCGRP.GURCGRP_SGRP_CODE
  from BANSECR.GURCGRP GURCGRP,
       BANSECR.GURUGRP GURUGRP
 where ( GURCGRP.GURCGRP_SGRP_CODE = GURUGRP.GURUGRP_SGRP_CODE )
   and ( GURUGRP.GURUGRP_USER = :frmMain_mc_UserAcctData.USERNAME )

 order by 1

 -- ROLE PRIVLEDGES
 select DBA_ROLE_PRIVS.GRANTED_ROLE "ROLE_NAME",
       DBA_ROLE_PRIVS.DEFAULT_ROLE "ROLE_DEFAULT_ROLE"
  from SYS.DBA_ROLE_PRIVS DBA_ROLE_PRIVS
 where DBA_ROLE_PRIVS.GRANTEE = :frmMain_mc_UserAcctData.USERNAME
 order by DBA_ROLE_PRIVS.GRANTED_ROLE