(SELECT SHRLGPA.SHRLGPA_GPA
   FROM SHRLGPA
  WHERE SHRLGPA.SHRLGPA_PIDM = SFBETRM.SFBETRM_PIDM
    AND SHRLGPA.SHRLGPA_GPA_TYPE_IND = 'O'
    AND SHRLGPA.SHRLGPA_LEVL_CODE = SGBSTDN.SGBSTDN_LEVL_CODE) >=2.5