Select
    SPRIDEN.SPRIDEN_ID BannerID,
    SPRIDEN.SPRIDEN_LAST_NAME LastName,
    SPRIDEN.SPRIDEN_FIRST_NAME FirstName,
    SPBPERS.SPBPERS_PREF_FIRST_NAME PrefFirstName,
    SPBPERS.SPBPERS_SEX Sex,
    STVCLAS.STVCLAS_DESC StudentClass,
    STVMAJR.STVMAJR_DESC Major,
    STVDEGC.STVDEGC_CODE DegreeProgram,
    SGBSTDN.SGBSTDN_STYP_CODE RegType,
    SGBSTDN.SGBSTDN_STST_CODE STST_CODE,
    GOREMAL.GOREMAL_EMAIL_ADDRESS Email_Address

from

-- IDENTIFICATION
    SPRIDEN SPRIDEN

    join SPBPERS SPBPERS on SPBPERS.SPBPERS_PIDM = SPRIDEN.SPRIDEN_PIDM

-- EMAIL
    left outer join GOREMAL GOREMAL on GOREMAL.GOREMAL_PIDM = SPRIDEN.SPRIDEN_PIDM
        and GOREMAL.GOREMAL_EMAL_CODE = 'SU'

-- TERM SELECTION
    join STVTERM STVTERM on STVTERM.STVTERM_CODE = :select_term_code.STVTERM_CODE

-- STUDENT DATA
    left outer join SGBSTDN SGBSTDN on SGBSTDN.SGBSTDN_PIDM = SPRIDEN.SPRIDEN_PIDM
         and SGBSTDN.SGBSTDN_TERM_CODE_EFF = fy_sgbstdn_eff_term(SGBSTDN.SGBSTDN_PIDM, STVTERM.STVTERM_CODE)
         and SGBSTDN.SGBSTDN_MAJR_CODE_1 not in ('0000', 'EHS', 'SUS', 'VIS')
         and SGBSTDN.SGBSTDN_STST_CODE = 'AS'

-- ADDITIONAL DETAILS
    left outer join STVDEGC STVDEGC on STVDEGC.STVDEGC_CODE = SGBSTDN.SGBSTDN_DEGC_CODE_1

    left outer join STVMAJR STVMAJR on STVMAJR.STVMAJR_CODE = SGBSTDN.SGBSTDN_MAJR_CODE_1

    left outer join STVCLAS STVCLAS on STVCLAS.STVCLAS_CODE = f_class_calc_fnc(SGBSTDN.SGBSTDN_PIDM,SGBSTDN.SGBSTDN_LEVL_CODE, STVTERM.STVTERM_CODE)

-- CONDITIONS
where
    SPRIDEN.SPRIDEN_NTYP_CODE is null
    and SPRIDEN.SPRIDEN_CHANGE_IND is null
    and exists(
        select *
        from SFRSTCR SFRSTCR
        where SFRSTCR.SFRSTCR_PIDM = SPRIDEN.SPRIDEN_PIDM
        and SFRSTCR.SFRSTCR_TERM_CODE = STVTERM.STVTERM_CODE
        --and SFRSTCR.SFRSTCR_RSTS_CODE in ('RE','RW')
        and SFRSTCR.SFRSTCR_RSTS_CODE like 'R%'
    )

-- GROUPING / SORTING
order by
    STVCLAS.STVCLAS_SURROGATE_ID, SPRIDEN.SPRIDEN_SEARCH_LAST_NAME