-- display I

--select * from incoming students

/*
STUDENT COURSE REGISTRATION
v.1 ENROLLED STUDENTS
v.2a MAIN CAMPUS STUDENTS
v.2a RANGER SCHOOL STUDENTS
V3.a GRADUATE SCHOOL STUDENTS
v.3 VISITING STUDENTS
v.4 SU STUDENTS
v.5 EHS STUDENTS
*/

with SPAIDEN as
(
    SELECT
        SPRIDEN.SPRIDEN_ID,
        SPRIDEN.SPRIDEN_PIDM,
        SPRIDEN.SPRIDEN_LAST_NAME,
        SPRIDEN.SPRIDEN_FIRST_NAME,
        SPRIDEN.SPRIDEN_MI,
        f_format_name(SPRIDEN.SPRIDEN_PIDM, 'LFMI') as SPRIDEN_LEGAL_NAME,
        SPRIDEN.SPRIDEN_SEARCH_LAST_NAME,
        SPRIDEN.SPRIDEN_SEARCH_FIRST_NAME,
        SPRIDEN.SPRIDEN_SEARCH_MI

    FROM
        SPRIDEN SPRIDEN

    WHERE
        SPRIDEN.SPRIDEN_NTYP_CODE IS NULL
        AND SPRIDEN.SPRIDEN_CHANGE_IND IS NULL
    ),

SPAPERS as
(
    SELECT
        SPBPERS.SPBPERS_PIDM,
        SPBPERS.SPBPERS_SSN,
        SPBPERS.SPBPERS_BIRTH_DATE,
        ROUND(((SYSDATE - SPBPERS_BIRTH_DATE)/365), 0) as SPBPERS_AGE,
        SPBPERS.SPBPERS_SEX,
        SPBPERS.SPBPERS_PREF_FIRST_NAME,
        SPBPERS.SPBPERS_CITZ_CODE,
        SPBPERS.SPBPERS_ETHN_CDE,
        f_get_desc_fnc('STVETHN', SPBPERS_ETHN_CDE, 30) as SPBPERS_ETHN_DESC,
        case
          when SPBPERS_ETHN_CDE in (2,3,4,5,6,7,9,10) then 'Y'
            else 'N'
              end as SPBPERS_SICAS_HISP_ORIGIN,
        CASE
            WHEN SPBPERS.SPBPERS_CITZ_CODE = 'Y' THEN 'United States'
            ELSE (SELECT STVNATN_NATION
                 FROM STVNATN
                 WHERE STVNATN_CODE = NVL(GOBINTL.GOBINTL_NATN_CODE_LEGAL, GOBINTL.GOBINTL_NATN_CODE_BIRTH))
            END as SPBPERS_CITZ_COUNTRY,
        SPBPERS.SPBPERS_GNDR_CODE,
        GOBINTL_NATN_CODE_BIRTH,
        f_get_desc_fnc('STVNATN', GOBINTL_NATN_CODE_BIRTH, 30) as GOBINTL_BIRTH_NATN

   FROM
        SPBPERS SPBPERS
        LEFT OUTER JOIN GOBINTL GOBINTL ON GOBINTL.GOBINTL_PIDM = SPBPERS.SPBPERS_PIDM
   ),

GOARACE as
(
    SELECT
        GORPRAC.GORPRAC_PIDM as GORPRAC_PIDM,
        (listagg(GORPRAC.GORPRAC_RACE_CDE,', ') within group (order by GORPRAC.GORPRAC_RACE_CDE)) as GORRACE_RACE_CDE,
        (listagg(GORRACE.GORRACE_DESC,', ') within group (order by GORRACE.GORRACE_DESC)) as GORRACE_DESC

    FROM
        GORPRAC GORPRAC

    LEFT OUTER JOIN GORRACE GORRACE ON GORRACE.GORRACE_RACE_CDE = GORPRAC.GORPRAC_RACE_CDE

    GROUP BY
        GORPRAC.GORPRAC_PIDM
    ),

SOREMAL as
(
    SELECT
        GOREMAL.GOREMAL_PIDM,
        GOREMAL.GOREMAL_EMAL_CODE,
        GOREMAL.GOREMAL_EMAIL_ADDRESS,
        GOREMAL.GOREMAL_STATUS_IND,
        GOREMAL.GOREMAL_PREFERRED_IND,
        GORADID.GORADID_PIDM,
        GORADID.GORADID_ADDITIONAL_ID,
        GORADID.GORADID_ADID_CODE,
        GOBTPAC.GOBTPAC_EXTERNAL_USER --esfid

    FROM
        GOREMAL GOREMAL
        LEFT OUTER JOIN GORADID GORADID ON GORADID.GORADID_PIDM = GOREMAL.GOREMAL_PIDM
             AND GORADID.GORADID_ADID_CODE = 'SUID'
        LEFT OUTER JOIN GOBUMAP GOBUMAP ON GOBUMAP.GOBUMAP_PIDM = GOREMAL.GOREMAL_PIDM
        LEFT OUTER JOIN GOBTPAC GOBTPAC ON GOBTPAC.GOBTPAC_PIDM = GOREMAL.GOREMAL_PIDM

    WHERE
        GOREMAL.GOREMAL_EMAL_CODE = 'SU'
        AND GOREMAL.GOREMAL_STATUS_IND = 'A'
        AND GOREMAL.GOREMAL_PREFERRED_IND = 'Y'
        AND GORADID.GORADID_ADID_CODE = 'SUID'
    ),

SAAADMS as
(
    select
        SARAPPD_PIDM,
        SARAPPD_TERM_CODE_ENTRY,
        SARAPPD_APPL_NO,
        SARAPPD_SEQ_NO,
        SARAPPD_APDC_DATE,
        SARAPPD_APDC_CODE,
        SARAPPD_MAINT_IND,
        SARAPPD_ACTIVITY_DATE,
        SARAPPD_USER,
        SARAPPD_DATA_ORIGIN,
        SARAPPD_SURROGATE_ID,
        SARAPPD_VERSION,
        SARAPPD_USER_ID,
        SARAPPD_VPDI_CODE,
        SARAPPD_GUID,
        SARAPPD_DFE_ADMN_DECN_GUID

    from
        SARAPPD SARAPPD

    where
        SARAPPD.SARAPPD_SEQ_NO = (select max(SARAPPD_SEQ_NO)
                                 from SARAPPD SARAPPDX
                                 where SARAPPDX.SARAPPD_PIDM = SARAPPD.SARAPPD_PIDM)
        and SARAPPD.SARAPPD_APPL_NO = (select max(SARAPPD_APPL_NO)
                                 from SARAPPD SARAPPDX
                                 where SARAPPDX.SARAPPD_PIDM = SARAPPD.SARAPPD_PIDM)
     ),

RCAAPPL  as
(
    select
        --*
         RCVAPPL_AIDY_CODE,
         RCVAPPL_PIDM,
         RCVAPPL_INFC_CODE,
         RCVAPPL_SEQ_NO,
         RCVAPPL_CURR_REC_IND,
         RCVAPPL_PGI,
         RCVAPPL_TFC,
         SUM(RCVAPPL_PGI) as RCVAPPL_EFC_SUM

    from
         RCVAPPL RCVAPPL

    where
         --RCVAPPL_INFC_CODE = 'ISIR'
         RCVAPPL_AIDY_CODE = :select_term_code.STVTERM_FA_PROC_YR
         and RCVAPPL_SEQ_NO = (select max(RCVAPPL_SEQ_NO)
                             from RCVAPPL RCVAPPL1
                             where RCVAPPL1.RCVAPPL_PIDM = RCVAPPL.RCVAPPL_PIDM
                             and RCVAPPL1.RCVAPPL_INFC_CODE = RCVAPPL.RCVAPPL_INFC_CODE
                             and RCVAPPL1.RCVAPPL_AIDY_CODE = RCVAPPL.RCVAPPL_AIDY_CODE)

    group by
            RCVAPPL_AIDY_CODE,
            RCVAPPL_PIDM,
            RCVAPPL_INFC_CODE,
            RCVAPPL_SEQ_NO,
            RCVAPPL_CURR_REC_IND,
            RCVAPPL_PGI,
            RCVAPPL_TFC
    ),
    -- you know how much you hate when things lose their integrity

RPAAWRD  as
(
    select
         SUM(RPRAWRD_ACCEPT_AMT) as RPRAWRD_OFFER_SUM ,
         RPRAWRD_pidm,
         RPRAWRD_AIDY_CODE

    from
         RPRAWRD RPRAWRD
    where
         --RCVAPPL_INFC_CODE = 'ISIR'
         RPRAWRD_AIDY_CODE = :select_term_code.STVTERM_FA_PROC_YR
    group by
         RPRAWRD_PIDM,
         RPRAWRD_AIDY_CODE
    ),

RPRACMP as
(
    select
         SUM(RBRACMP_AMT) as RBRACMP_SUM ,
         RBRACMP_AIDY_CODE,
         RBRACMP_PIDM

    from
         RBRACMP RBRACMP

    where
         RBRACMP_BTYP_CODE = 'PELL'
         AND RBRACMP_AIDY_CODE = :select_term_code.STVTERM_FA_PROC_YR
    group by
         RBRACMP_PIDM,
         RBRACMP_AIDY_CODE
    ),

FA_APPLIED_STUDENTS as(

    select
        SARAPPD_PIDM,
        SPRIDEN_ID as BANNER_ID,
        SPRIDEN_LEGAL_NAME as APPLICANT_NAME,
        SARAPPD_TERM_CODE_ENTRY as TERM_CODE_ENTRY,
        SARAPPD_APPL_NO as APPL_NO,
        SARAPPD_APDC_DATE as DECISION_DATE,
        SARAPPD_APDC_CODE as DECISION_CODE,
        SARAPPD_ACTIVITY_DATE as ACTIVITY_DATE,
        SARAPPD_SURROGATE_ID,
        SARAPPD_VERSION,
        SARAPPD_APDC_CODE,
        /*
        RCVAPPL.RCVAPPL_PIDM,
        RCVAPPL_AIDY_CODE,
        RPRAWRD_AIDY_CODE
        RCVAPPL_INFC_CODE,
        RCVAPPL_CURR_REC_IND,
        RCVAPPL_PGI,
        RCVAPPL_TFC,
        RCVAPPL_EFC_SUM,
        /*
        RPRAWRD.RPRAWRD_PIDM,
        RPRAWRD_AIDY_CODE,
        RPRAWRD_OFFER_SUM,
        */
        RBRACMP.RBRACMP_PIDM,
        RBRACMP_AIDY_CODE,
        RBRACMP_SUM
        --UCID BLACKBOARD - HOORAY

        SPRIDEN_SEARCH_LAST_NAME,
        SPRIDEN_SEARCH_FIRST_NAME

    from
        SARAPPD SARAPPD
        LEFT OUTER JOIN SPAIDEN SPRIDEN ON SPRIDEN.SPRIDEN_PIDM = SARAPPD.SARAPPD_PIDM
        --LEFT OUTER JOIN RCAAPPL RCVAPPL ON RCVAPPL.RCVAPPL_PIDM = SARAPPD.SARAPPD_PIDM
        --LEFT OUTER JOIN RPAAWRD RPRAWRD ON RPRAWRD.RPRAWRD_PIDM = SARAPPD.SARAPPD_PIDM
        LEFT OUTER JOIN RPRACMP RBRACMP ON RBRACMP.RBRACMP_PIDM = SARAPPD.SARAPPD_PIDM

    where
        SARAPPD_TERM_CODE_ENTRY = '&t'
        and SARAPPD.SARAPPD_SEQ_NO = (select max(SARAPPD_SEQ_NO)
                                 from SARAPPD SARAPPDX
                                 where SARAPPDX.SARAPPD_PIDM = SARAPPD.SARAPPD_PIDM)
        and SARAPPD.SARAPPD_APPL_NO = (select max(SARAPPD_APPL_NO)
                                 from SARAPPD SARAPPDX
                                 where SARAPPDX.SARAPPD_PIDM = SARAPPD.SARAPPD_PIDM)
     ),

FA_GROSS_NEED as(

    select
        SPRIDEN_ID as BANNER_ID,
        SPRIDEN_LEGAL_NAME as APPLICANT_NAME,
        RCVAPPL.RCVAPPL_PIDM,
        RCVAPPL_AIDY_CODE,
        RCVAPPL_INFC_CODE,
        RCVAPPL_CURR_REC_IND,
        RCVAPPL_PGI,
        RCVAPPL_TFC,
        RCVAPPL_EFC_SUM,
        RPRAWRD.RPRAWRD_PIDM,
        RPRAWRD_AIDY_CODE,
        RPRAWRD_OFFER_SUM,

        RBRACMP.RBRACMP_PIDM,
        RBRACMP_AIDY_CODE,
        RBRACMP_SUM
        --UCID BLACKBOARD - HOORAY

        SPRIDEN_SEARCH_LAST_NAME,
        SPRIDEN_SEARCH_FIRST_NAME

    from
        SPAIDEN SPRIDEN
        LEFT OUTER JOIN RCAAPPL RCVAPPL ON RCVAPPL.RCVAPPL_PIDM = SPRIDEN.SPRIDEN_PIDM
        LEFT OUTER JOIN RPAAWRD RPRAWRD ON RPRAWRD.RPRAWRD_PIDM = SPRIDEN.SPRIDEN_PIDM
        LEFT OUTER JOIN RPRACMP RBRACMP ON RBRACMP.RBRACMP_PIDM = SPRIDEN.SPRIDEN_PIDM

    where
        RCVAPPL_AIDY_CODE = :select_term_code.STVTERM_FA_PROC_YR
     ),

FA_GROSS_NEED_DISPLAY as(

    select
        SPRIDEN_ID as BANNER_ID,
        SPRIDEN_LEGAL_NAME as APPLICANT_NAME,
        RCVAPPL_AIDY_CODE as AIDY_CODE,
        RCVAPPL_INFC_CODE,
        SPRIDEN_SEARCH_LAST_NAME,
        SPRIDEN_SEARCH_FIRST_NAME

    from
        SPAIDEN SPRIDEN
        LEFT OUTER JOIN RCAAPPL RCVAPPL ON RCVAPPL.RCVAPPL_PIDM = SPRIDEN.SPRIDEN_PIDM
        LEFT OUTER JOIN RPAAWRD RPRAWRD ON RPRAWRD.RPRAWRD_PIDM = SPRIDEN.SPRIDEN_PIDM
        LEFT OUTER JOIN RPRACMP RBRACMP ON RBRACMP.RBRACMP_PIDM = SPRIDEN.SPRIDEN_PIDM

    where
        RCVAPPL_AIDY_CODE = :select_term_code.STVTERM_FA_PROC_YR
     ),

SGASTDN as
(
    select
        SGBSTDN.SGBSTDN_PIDM,
        SGBSTDN.SGBSTDN_TERM_CODE_EFF,
        SGBSTDN.SGBSTDN_STST_CODE,
        SGBSTDN.SGBSTDN_LEVL_CODE,
        SGBSTDN.SGBSTDN_STYP_CODE,
        SGBSTDN.SGBSTDN_TERM_CODE_MATRIC,
        SGBSTDN.SGBSTDN_TERM_CODE_ADMIT,
        SGBSTDN.SGBSTDN_EXP_GRAD_DATE,
        SGBSTDN.SGBSTDN_CAMP_CODE,
        SGBSTDN.SGBSTDN_COLL_CODE_1,
        SGBSTDN.SGBSTDN_DEGC_CODE_1,
        SGBSTDN.SGBSTDN_MAJR_CODE_1,
        SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1,
        SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1_2,
        SGBSTDN.SGBSTDN_MAJR_CODE_CONC_1,
        SGBSTDN.SGBSTDN_RESD_CODE,
        SGBSTDN.SGBSTDN_ADMT_CODE,
        SGBSTDN.SGBSTDN_DEPT_CODE,
        SGBSTDN.SGBSTDN_PROGRAM_1,
        SGBSTDN.SGBSTDN_TERM_CODE_GRAD,
        SGBSTDN.SGBSTDN_ACTIVITY_DATE,
        f_class_calc_fnc(SGBSTDN.SGBSTDN_PIDM, SGBSTDN.SGBSTDN_LEVL_CODE, SGBSTDN.SGBSTDN_TERM_CODE_EFF) as SGBSTDN_CLAS_CODE,
        f_Get_desc_fnc('STVSTST',SGBSTDN.SGBSTDN_STST_CODE, 30) as SGBSTDN_STST_DESC,
        f_Get_desc_fnc('STVLEVL', SGBSTDN.SGBSTDN_LEVL_CODE, 30) as SGBSTDN_LEVL_DESC,
        f_Get_desc_fnc('STVSTYP', SGBSTDN.SGBSTDN_STYP_CODE, 30) as SGBSTDN_STYP_DESC,
        f_Get_desc_fnc('STVDEGC', SGBSTDN.SGBSTDN_DEGC_CODE_1, 30) as SGBSTDN_DEGC_DESC,
        f_Get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_1, 30) as SGBSTDN_MAJR_DESC,
        f_Get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1, 30) as SGBSTDN_MINR_1_DESC,
        f_Get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1_2, 30) as SGBSTDN_MINR_1_2_DESC,
        f_Get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_CONC_1, 30) as SGBSTDN_CONC_DESC,
        f_Get_desc_fnc('STVRESD', SGBSTDN.SGBSTDN_RESD_CODE, 30) as SGBSTDN_RESD_DESC,
        f_Get_desc_fnc('STVADMT', SGBSTDN.SGBSTDN_ADMT_CODE, 30) as SGBSTDN_ADMT_DESC,
        f_Get_desc_fnc('STVDEPT', SGBSTDN.SGBSTDN_DEPT_CODE, 30) as SGBSTDN_DEPT_DESC,
        f_Get_desc_fnc('STVTERM', SGBSTDN.SGBSTDN_TERM_CODE_MATRIC, 30) as SGBSTDN_MATRIC_TERM_DESC,
        f_Get_desc_fnc('STVTERM', SGBSTDN.SGBSTDN_TERM_CODE_GRAD, 30) as SGBSTDN_GRAD_TERM_DESC,
        f_Get_desc_fnc('STVCLAS', f_class_calc_fnc(SGBSTDN.SGBSTDN_PIDM,SGBSTDN.SGBSTDN_LEVL_CODE, SGBSTDN.SGBSTDN_TERM_CODE_EFF), 30) as SGBSTDN_CLAS_DESC

   from
        SGBSTDN SGBSTDN
   ),

SFAREGS as
(
 select
        f_format_name(SFRSTCR_PIDM, 'LF30') as SFRSTCR_NAME,
        SFRSTCR_TERM_CODE,
        SFRSTCR_PIDM,
        SFRSTCR_CRN,
        SFRSTCR_CLASS_SORT_KEY,
        SFRSTCR_REG_SEQ,
        SFRSTCR_PTRM_CODE,
        SFRSTCR_RSTS_CODE,
        SFRSTCR_BILL_HR,
        SFRSTCR_WAIV_HR,
        SFRSTCR_CREDIT_HR,
        SFRSTCR_BILL_HR_HOLD,
        SFRSTCR_CREDIT_HR_HOLD,
        SFRSTCR_GMOD_CODE,
        SFRSTCR_GRDE_CODE,
        SFRSTCR_GRDE_DATE,
        SFRSTCR_ADD_DATE,
        SFRSTCR_LEVL_CODE,
        SFRSTCR_CAMP_CODE,
        SHRTCKG_PIDM,
        SHRTCKG_TERM_CODE,
        SHRTCKG_TCKN_SEQ_NO,
        SHRTCKG_SEQ_NO,
        SHRTCKG_FINAL_GRDE_SEQ_NO,
        SHRTCKG_GRDE_CODE_FINAL,
        SHRTCKG_GMOD_CODE,
        SHRTCKG_CREDIT_HOURS,
        SHRTCKG_GCHG_CODE,
        SHRTCKG_FINAL_GRDE_CHG_DATE,
        SHRTCKG_HOURS_ATTEMPTED,
        SHRTCKG_GRDE_CODE_INCMP_FINAL,
        SHRTCKG_SURROGATE_ID,
        SHRTCKG_VERSION,
        case
          WHEN SHRTCKG_GCHG_CODE IS NULL THEN NULL
            ELSE F_GET_DESC_FNC('STVGCHG', SHRTCKG_GCHG_CODE, 30)
              END as SHRTCKG_GCHG_DESC

    FROM
        SFRSTCR SFRSTCR

        LEFT OUTER JOIN SHRTCKG SHRTCKG ON SHRTCKG_PIDM = SFRSTCR_PIDM
             AND SHRTCKG.SHRTCKG_TERM_CODE = SFRSTCR.SFRSTCR_TERM_CODE
             AND SHRTCKG.SHRTCKG_TCKN_SEQ_NO = SFRSTCR.SFRSTCR_REG_SEQ

    WHERE
        SFRSTCR.SFRSTCR_RSTS_CODE IN ('RE', 'RW')
        AND SFRSTCR_TERM_CODE = '&t'

    ORDER BY
        SFRSTCR_NAME, SFRSTCR_CRN
    ),

--CLASS LIST
CLASS_LIST as
(
    select
        SGBSTDN_TERM_CODE_EFF,
        SPRIDEN_ID,
        SPRIDEN_PIDM,
        SPRIDEN_LEGAL_NAME,
        SPRIDEN_SEARCH_LAST_NAME,
        SPRIDEN_SEARCH_FIRST_NAME,
        SPBPERS_PREF_FIRST_NAME,
        SPRIDEN_LAST_NAME,
        SPRIDEN_FIRST_NAME,
        SPRIDEN_MI,
        GORADID_ADDITIONAL_ID,
        GOREMAL_EMAIL_ADDRESS,
        SGBSTDN_STYP_CODE,
        SGBSTDN_LEVL_CODE,
        SGBSTDN_CLAS_CODE,
        SGBSTDN_MAJR_CODE_1,
        SGBSTDN_MAJR_CODE_MINR_1,
        SGBSTDN_MAJR_CODE_MINR_1_2,
        SGBSTDN_MAJR_CODE_CONC_1,
        SGBSTDN_DEGC_CODE_1,
        SGBSTDN_STYP_DESC,
        SGBSTDN_LEVL_DESC,
        SGBSTDN_CLAS_DESC,
        SGBSTDN_MAJR_DESC,
        SGBSTDN_MINR_1_DESC,
        SGBSTDN_MINR_1_2_DESC,
        SGBSTDN_CONC_DESC,
        SGBSTDN_DEGC_DESC,
        SGBSTDN_EXP_GRAD_DATE,
        SPBPERS_AGE,
        SPBPERS_SEX,
        GORRACE_RACE_CDE,
        GORRACE_DESC,
        SPBPERS.SPBPERS_ETHN_CDE,
        SPBPERS_ETHN_DESC,
        SPBPERS_SICAS_HISP_ORIGIN,
        SPBPERS.SPBPERS_CITZ_CODE,
        SPBPERS_CITZ_COUNTRY,
        GOBINTL_NATN_CODE_BIRTH,
        GOBINTL_BIRTH_NATN

    FROM
        SPAIDEN SPRIDEN
        LEFT OUTER JOIN SPAPERS SPBPERS ON SPBPERS.SPBPERS_PIDM = SPRIDEN.SPRIDEN_PIDM
        LEFT OUTER JOIN GOARACE GORPRAC ON GORPRAC.GORPRAC_PIDM = SPRIDEN.SPRIDEN_PIDM
        LEFT OUTER JOIN SOREMAL GOREMAL ON GOREMAL.GOREMAL_PIDM = SPRIDEN.SPRIDEN_PIDM
        LEFT OUTER JOIN SGASTDN SGBSTDN ON SGBSTDN.SGBSTDN_PIDM = SPRIDEN.SPRIDEN_PIDM

    WHERE
        SGBSTDN_STST_CODE = 'AS'
        AND SGBSTDN_TERM_CODE_EFF = FY_SGBSTDN_EFF_TERM(SGBSTDN_PIDM, '&t')
    )

SELECT *

FROM
      --FA_APPLIED_STUDENTS SAP
      FA_GROSS_NEED_DISPLAY GN1_D
      --FA_GROSS_NEED GN1
      --CLASS_LIST CL1
      --COURE_ENROLLED_1 CE1
      --SCHEDULE_VIEW_1 SV1
WHERE
--DECISIONED APPLICANTS
--      SARAPPD_APDC_CODE IN ('&APDC')
      RCVAPPL_INFC_CODE = 'EDE'
         --$addfilter

         --$beginorder

ORDER BY
        --ALL STUDENT-FACING QUERIES

        SPRIDEN_SEARCH_LAST_NAME,
        SPRIDEN_SEARCH_FIRST_NAME

        --SV1 ONLY
        --SSBSECT_SICAS_CAMP_SECTION_ID
         --$endorder

-- display II

--select * from incoming students

/*
STUDENT COURSE REGISTRATION
v.1 ENROLLED STUDENTS
v.2a MAIN CAMPUS STUDENTS
v.2a RANGER SCHOOL STUDENTS
V3.a GRADUATE SCHOOL STUDENTS
v.3 VISITING STUDENTS
v.4 SU STUDENTS
v.5 EHS STUDENTS
*/

with SPAIDEN as
(
    SELECT
        SPRIDEN.SPRIDEN_ID,
        SPRIDEN.SPRIDEN_PIDM,
        SPRIDEN.SPRIDEN_LAST_NAME,
        SPRIDEN.SPRIDEN_FIRST_NAME,
        SPRIDEN.SPRIDEN_MI,
        f_format_name(SPRIDEN.SPRIDEN_PIDM, 'LFMI') as SPRIDEN_LEGAL_NAME,
        SPRIDEN.SPRIDEN_SEARCH_LAST_NAME,
        SPRIDEN.SPRIDEN_SEARCH_FIRST_NAME,
        SPRIDEN.SPRIDEN_SEARCH_MI

    FROM
        SPRIDEN SPRIDEN

    WHERE
        SPRIDEN.SPRIDEN_NTYP_CODE IS NULL
        AND SPRIDEN.SPRIDEN_CHANGE_IND IS NULL
    ),

SPAPERS as
(
    SELECT
        SPBPERS.SPBPERS_PIDM,
        SPBPERS.SPBPERS_SSN,
        SPBPERS.SPBPERS_BIRTH_DATE,
        ROUND(((SYSDATE - SPBPERS_BIRTH_DATE)/365), 0) as SPBPERS_AGE,
        SPBPERS.SPBPERS_SEX,
        SPBPERS.SPBPERS_PREF_FIRST_NAME,
        SPBPERS.SPBPERS_CITZ_CODE,
        SPBPERS.SPBPERS_ETHN_CDE,
        f_get_desc_fnc('STVETHN', SPBPERS_ETHN_CDE, 30) as SPBPERS_ETHN_DESC,
        case
          when SPBPERS_ETHN_CDE in (2,3,4,5,6,7,9,10) then 'Y'
            else 'N'
              end as SPBPERS_SICAS_HISP_ORIGIN,
        CASE
            WHEN SPBPERS.SPBPERS_CITZ_CODE = 'Y' THEN 'United States'
            ELSE (SELECT STVNATN_NATION
                 FROM STVNATN
                 WHERE STVNATN_CODE = NVL(GOBINTL.GOBINTL_NATN_CODE_LEGAL, GOBINTL.GOBINTL_NATN_CODE_BIRTH))
            END as SPBPERS_CITZ_COUNTRY,
        SPBPERS.SPBPERS_GNDR_CODE,
        GOBINTL_NATN_CODE_BIRTH,
        f_get_desc_fnc('STVNATN', GOBINTL_NATN_CODE_BIRTH, 30) as GOBINTL_BIRTH_NATN

   FROM
        SPBPERS SPBPERS
        LEFT OUTER JOIN GOBINTL GOBINTL ON GOBINTL.GOBINTL_PIDM = SPBPERS.SPBPERS_PIDM
   ),

GOARACE as
(
    SELECT
        GORPRAC.GORPRAC_PIDM as GORPRAC_PIDM,
        (listagg(GORPRAC.GORPRAC_RACE_CDE,', ') within group (order by GORPRAC.GORPRAC_RACE_CDE)) as GORRACE_RACE_CDE,
        (listagg(GORRACE.GORRACE_DESC,', ') within group (order by GORRACE.GORRACE_DESC)) as GORRACE_DESC

    FROM
        GORPRAC GORPRAC

    LEFT OUTER JOIN GORRACE GORRACE ON GORRACE.GORRACE_RACE_CDE = GORPRAC.GORPRAC_RACE_CDE

    GROUP BY
        GORPRAC.GORPRAC_PIDM
    ),

SOREMAL as
(
    SELECT
        GOREMAL.GOREMAL_PIDM,
        GOREMAL.GOREMAL_EMAL_CODE,
        GOREMAL.GOREMAL_EMAIL_ADDRESS,
        GOREMAL.GOREMAL_STATUS_IND,
        GOREMAL.GOREMAL_PREFERRED_IND,
        GORADID.GORADID_PIDM,
        GORADID.GORADID_ADDITIONAL_ID,
        GORADID.GORADID_ADID_CODE,
        GOBTPAC.GOBTPAC_EXTERNAL_USER --esfid

    FROM
        GOREMAL GOREMAL
        LEFT OUTER JOIN GORADID GORADID ON GORADID.GORADID_PIDM = GOREMAL.GOREMAL_PIDM
             AND GORADID.GORADID_ADID_CODE = 'SUID'
        LEFT OUTER JOIN GOBUMAP GOBUMAP ON GOBUMAP.GOBUMAP_PIDM = GOREMAL.GOREMAL_PIDM
        LEFT OUTER JOIN GOBTPAC GOBTPAC ON GOBTPAC.GOBTPAC_PIDM = GOREMAL.GOREMAL_PIDM

    WHERE
        GOREMAL.GOREMAL_EMAL_CODE = 'SU'
        AND GOREMAL.GOREMAL_STATUS_IND = 'A'
        AND GOREMAL.GOREMAL_PREFERRED_IND = 'Y'
        AND GORADID.GORADID_ADID_CODE = 'SUID'
    ),

SAAADMS as
(
    select
        SARAPPD_PIDM,
        SARAPPD_TERM_CODE_ENTRY,
        SARAPPD_APPL_NO,
        SARAPPD_SEQ_NO,
        SARAPPD_APDC_DATE,
        SARAPPD_APDC_CODE,
        SARAPPD_MAINT_IND,
        SARAPPD_ACTIVITY_DATE,
        SARAPPD_USER,
        SARAPPD_DATA_ORIGIN,
        SARAPPD_SURROGATE_ID,
        SARAPPD_VERSION,
        SARAPPD_USER_ID,
        SARAPPD_VPDI_CODE,
        SARAPPD_GUID,
        SARAPPD_DFE_ADMN_DECN_GUID

    from
        SARAPPD SARAPPD

    where
        SARAPPD.SARAPPD_SEQ_NO = (select max(SARAPPD_SEQ_NO)
                                 from SARAPPD SARAPPDX
                                 where SARAPPDX.SARAPPD_PIDM = SARAPPD.SARAPPD_PIDM)
        and SARAPPD.SARAPPD_APPL_NO = (select max(SARAPPD_APPL_NO)
                                 from SARAPPD SARAPPDX
                                 where SARAPPDX.SARAPPD_PIDM = SARAPPD.SARAPPD_PIDM)
     ),

RCAAPPL  as
(
    select
        --*
         RCVAPPL_AIDY_CODE,
         RCVAPPL_PIDM,
         RCVAPPL_INFC_CODE,
         RCVAPPL_SEQ_NO,
         RCVAPPL_CURR_REC_IND,
         RCVAPPL_PGI,
         RCVAPPL_TFC,
         SUM(RCVAPPL_PGI) as RCVAPPL_EFC_SUM

    from
         RCVAPPL RCVAPPL

    where
         --RCVAPPL_INFC_CODE = 'ISIR'
         RCVAPPL_AIDY_CODE = :select_term_code.STVTERM_FA_PROC_YR
         and RCVAPPL_SEQ_NO = (select max(RCVAPPL_SEQ_NO)
                             from RCVAPPL RCVAPPL1
                             where RCVAPPL1.RCVAPPL_PIDM = RCVAPPL.RCVAPPL_PIDM
                             and RCVAPPL1.RCVAPPL_INFC_CODE = RCVAPPL.RCVAPPL_INFC_CODE
                             and RCVAPPL1.RCVAPPL_AIDY_CODE = RCVAPPL.RCVAPPL_AIDY_CODE)

    group by
            RCVAPPL_AIDY_CODE,
            RCVAPPL_PIDM,
            RCVAPPL_INFC_CODE,
            RCVAPPL_SEQ_NO,
            RCVAPPL_CURR_REC_IND,
            RCVAPPL_PGI,
            RCVAPPL_TFC
    ),
    -- you know how much you hate when things lose their integrity

RPAAWRD  as
(
    select
         SUM(RPRAWRD_ACCEPT_AMT) as RPRAWRD_OFFER_SUM ,
         RPRAWRD_pidm,
         RPRAWRD_AIDY_CODE

    from
         RPRAWRD RPRAWRD
    where
         --RCVAPPL_INFC_CODE = 'ISIR'
         RPRAWRD_AIDY_CODE = :select_term_code.STVTERM_FA_PROC_YR
    group by
         RPRAWRD_PIDM,
         RPRAWRD_AIDY_CODE
    ),

RPRACMP as
(
    select
         SUM(RBRACMP_AMT) as RBRACMP_SUM ,
         RBRACMP_AIDY_CODE,
         RBRACMP_PIDM

    from
         RBRACMP RBRACMP

    where
         RBRACMP_BTYP_CODE = 'PELL'
         AND RBRACMP_AIDY_CODE = :select_term_code.STVTERM_FA_PROC_YR
    group by
         RBRACMP_PIDM,
         RBRACMP_AIDY_CODE
    ),

FA_APPLIED_STUDENTS as(

    select
        SARAPPD_PIDM,
        SPRIDEN_ID as BANNER_ID,
        SPRIDEN_LEGAL_NAME as APPLICANT_NAME,
        SARAPPD_TERM_CODE_ENTRY as TERM_CODE_ENTRY,
        SARAPPD_APPL_NO as APPL_NO,
        SARAPPD_APDC_DATE as DECISION_DATE,
        SARAPPD_APDC_CODE as DECISION_CODE,
        SARAPPD_ACTIVITY_DATE as ACTIVITY_DATE,
        SARAPPD_SURROGATE_ID,
        SARAPPD_VERSION,
        SARAPPD_APDC_CODE,
        /*
        RCVAPPL.RCVAPPL_PIDM,
        RCVAPPL_AIDY_CODE,
        RPRAWRD_AIDY_CODE
        RCVAPPL_INFC_CODE,
        RCVAPPL_CURR_REC_IND,
        RCVAPPL_PGI,
        RCVAPPL_TFC,
        RCVAPPL_EFC_SUM,
        /*
        RPRAWRD.RPRAWRD_PIDM,
        RPRAWRD_AIDY_CODE,
        RPRAWRD_OFFER_SUM,
        */
        RBRACMP.RBRACMP_PIDM,
        RBRACMP_AIDY_CODE,
        RBRACMP_SUM
        --UCID BLACKBOARD - HOORAY

        SPRIDEN_SEARCH_LAST_NAME,
        SPRIDEN_SEARCH_FIRST_NAME

    from
        SARAPPD SARAPPD
        LEFT OUTER JOIN SPAIDEN SPRIDEN ON SPRIDEN.SPRIDEN_PIDM = SARAPPD.SARAPPD_PIDM
        --LEFT OUTER JOIN RCAAPPL RCVAPPL ON RCVAPPL.RCVAPPL_PIDM = SARAPPD.SARAPPD_PIDM
        --LEFT OUTER JOIN RPAAWRD RPRAWRD ON RPRAWRD.RPRAWRD_PIDM = SARAPPD.SARAPPD_PIDM
        LEFT OUTER JOIN RPRACMP RBRACMP ON RBRACMP.RBRACMP_PIDM = SARAPPD.SARAPPD_PIDM

    where
        SARAPPD_TERM_CODE_ENTRY = '&t'
        and SARAPPD.SARAPPD_SEQ_NO = (select max(SARAPPD_SEQ_NO)
                                 from SARAPPD SARAPPDX
                                 where SARAPPDX.SARAPPD_PIDM = SARAPPD.SARAPPD_PIDM)
        and SARAPPD.SARAPPD_APPL_NO = (select max(SARAPPD_APPL_NO)
                                 from SARAPPD SARAPPDX
                                 where SARAPPDX.SARAPPD_PIDM = SARAPPD.SARAPPD_PIDM)
     ),

FA_GROSS_NEED as(

    select
        SPRIDEN_ID as BANNER_ID,
        SPRIDEN_LEGAL_NAME as APPLICANT_NAME,
        RCVAPPL.RCVAPPL_PIDM,
        RCVAPPL_AIDY_CODE,
        RCVAPPL_INFC_CODE,
        RCVAPPL_CURR_REC_IND,
        RCVAPPL_PGI,
        RCVAPPL_TFC,
        RCVAPPL_EFC_SUM,
        RPRAWRD.RPRAWRD_PIDM,
        RPRAWRD_AIDY_CODE,
        RPRAWRD_OFFER_SUM,

        RBRACMP.RBRACMP_PIDM,
        RBRACMP_AIDY_CODE,
        RBRACMP_SUM
        --UCID BLACKBOARD - HOORAY

        SPRIDEN_SEARCH_LAST_NAME,
        SPRIDEN_SEARCH_FIRST_NAME

    from
        SPAIDEN SPRIDEN
        LEFT OUTER JOIN RCAAPPL RCVAPPL ON RCVAPPL.RCVAPPL_PIDM = SPRIDEN.SPRIDEN_PIDM
        LEFT OUTER JOIN RPAAWRD RPRAWRD ON RPRAWRD.RPRAWRD_PIDM = SPRIDEN.SPRIDEN_PIDM
        LEFT OUTER JOIN RPRACMP RBRACMP ON RBRACMP.RBRACMP_PIDM = SPRIDEN.SPRIDEN_PIDM

    where
        RCVAPPL_AIDY_CODE = :select_term_code.STVTERM_FA_PROC_YR
     ),

FA_GROSS_NEED_DISPLAY as(

    select
        SPRIDEN_ID as BANNER_ID,
        SPRIDEN_LEGAL_NAME as APPLICANT_NAME,
        RCVAPPL_AIDY_CODE as AIDY_CODE,
        RCVAPPL_INFC_CODE,
        SPRIDEN_SEARCH_LAST_NAME,
        SPRIDEN_SEARCH_FIRST_NAME

    from
        SPAIDEN SPRIDEN
        LEFT OUTER JOIN RCAAPPL RCVAPPL ON RCVAPPL.RCVAPPL_PIDM = SPRIDEN.SPRIDEN_PIDM
        LEFT OUTER JOIN RPAAWRD RPRAWRD ON RPRAWRD.RPRAWRD_PIDM = SPRIDEN.SPRIDEN_PIDM
        LEFT OUTER JOIN RPRACMP RBRACMP ON RBRACMP.RBRACMP_PIDM = SPRIDEN.SPRIDEN_PIDM

    where
        RCVAPPL_AIDY_CODE = :select_term_code.STVTERM_FA_PROC_YR
     ),

SGASTDN as
(
    select
        SGBSTDN.SGBSTDN_PIDM,
        SGBSTDN.SGBSTDN_TERM_CODE_EFF,
        SGBSTDN.SGBSTDN_STST_CODE,
        SGBSTDN.SGBSTDN_LEVL_CODE,
        SGBSTDN.SGBSTDN_STYP_CODE,
        SGBSTDN.SGBSTDN_TERM_CODE_MATRIC,
        SGBSTDN.SGBSTDN_TERM_CODE_ADMIT,
        SGBSTDN.SGBSTDN_EXP_GRAD_DATE,
        SGBSTDN.SGBSTDN_CAMP_CODE,
        SGBSTDN.SGBSTDN_COLL_CODE_1,
        SGBSTDN.SGBSTDN_DEGC_CODE_1,
        SGBSTDN.SGBSTDN_MAJR_CODE_1,
        SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1,
        SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1_2,
        SGBSTDN.SGBSTDN_MAJR_CODE_CONC_1,
        SGBSTDN.SGBSTDN_RESD_CODE,
        SGBSTDN.SGBSTDN_ADMT_CODE,
        SGBSTDN.SGBSTDN_DEPT_CODE,
        SGBSTDN.SGBSTDN_PROGRAM_1,
        SGBSTDN.SGBSTDN_TERM_CODE_GRAD,
        SGBSTDN.SGBSTDN_ACTIVITY_DATE,
        f_class_calc_fnc(SGBSTDN.SGBSTDN_PIDM, SGBSTDN.SGBSTDN_LEVL_CODE, SGBSTDN.SGBSTDN_TERM_CODE_EFF) as SGBSTDN_CLAS_CODE,
        f_Get_desc_fnc('STVSTST',SGBSTDN.SGBSTDN_STST_CODE, 30) as SGBSTDN_STST_DESC,
        f_Get_desc_fnc('STVLEVL', SGBSTDN.SGBSTDN_LEVL_CODE, 30) as SGBSTDN_LEVL_DESC,
        f_Get_desc_fnc('STVSTYP', SGBSTDN.SGBSTDN_STYP_CODE, 30) as SGBSTDN_STYP_DESC,
        f_Get_desc_fnc('STVDEGC', SGBSTDN.SGBSTDN_DEGC_CODE_1, 30) as SGBSTDN_DEGC_DESC,
        f_Get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_1, 30) as SGBSTDN_MAJR_DESC,
        f_Get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1, 30) as SGBSTDN_MINR_1_DESC,
        f_Get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1_2, 30) as SGBSTDN_MINR_1_2_DESC,
        f_Get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_CONC_1, 30) as SGBSTDN_CONC_DESC,
        f_Get_desc_fnc('STVRESD', SGBSTDN.SGBSTDN_RESD_CODE, 30) as SGBSTDN_RESD_DESC,
        f_Get_desc_fnc('STVADMT', SGBSTDN.SGBSTDN_ADMT_CODE, 30) as SGBSTDN_ADMT_DESC,
        f_Get_desc_fnc('STVDEPT', SGBSTDN.SGBSTDN_DEPT_CODE, 30) as SGBSTDN_DEPT_DESC,
        f_Get_desc_fnc('STVTERM', SGBSTDN.SGBSTDN_TERM_CODE_MATRIC, 30) as SGBSTDN_MATRIC_TERM_DESC,
        f_Get_desc_fnc('STVTERM', SGBSTDN.SGBSTDN_TERM_CODE_GRAD, 30) as SGBSTDN_GRAD_TERM_DESC,
        f_Get_desc_fnc('STVCLAS', f_class_calc_fnc(SGBSTDN.SGBSTDN_PIDM,SGBSTDN.SGBSTDN_LEVL_CODE, SGBSTDN.SGBSTDN_TERM_CODE_EFF), 30) as SGBSTDN_CLAS_DESC

   from
        SGBSTDN SGBSTDN
   ),

SFAREGS as
(
 select
        f_format_name(SFRSTCR_PIDM, 'LF30') as SFRSTCR_NAME,
        SFRSTCR_TERM_CODE,
        SFRSTCR_PIDM,
        SFRSTCR_CRN,
        SFRSTCR_CLASS_SORT_KEY,
        SFRSTCR_REG_SEQ,
        SFRSTCR_PTRM_CODE,
        SFRSTCR_RSTS_CODE,
        SFRSTCR_BILL_HR,
        SFRSTCR_WAIV_HR,
        SFRSTCR_CREDIT_HR,
        SFRSTCR_BILL_HR_HOLD,
        SFRSTCR_CREDIT_HR_HOLD,
        SFRSTCR_GMOD_CODE,
        SFRSTCR_GRDE_CODE,
        SFRSTCR_GRDE_DATE,
        SFRSTCR_ADD_DATE,
        SFRSTCR_LEVL_CODE,
        SFRSTCR_CAMP_CODE,
        SHRTCKG_PIDM,
        SHRTCKG_TERM_CODE,
        SHRTCKG_TCKN_SEQ_NO,
        SHRTCKG_SEQ_NO,
        SHRTCKG_FINAL_GRDE_SEQ_NO,
        SHRTCKG_GRDE_CODE_FINAL,
        SHRTCKG_GMOD_CODE,
        SHRTCKG_CREDIT_HOURS,
        SHRTCKG_GCHG_CODE,
        SHRTCKG_FINAL_GRDE_CHG_DATE,
        SHRTCKG_HOURS_ATTEMPTED,
        SHRTCKG_GRDE_CODE_INCMP_FINAL,
        SHRTCKG_SURROGATE_ID,
        SHRTCKG_VERSION,
        case
          WHEN SHRTCKG_GCHG_CODE IS NULL THEN NULL
            ELSE F_GET_DESC_FNC('STVGCHG', SHRTCKG_GCHG_CODE, 30)
              END as SHRTCKG_GCHG_DESC

    FROM
        SFRSTCR SFRSTCR

        LEFT OUTER JOIN SHRTCKG SHRTCKG ON SHRTCKG_PIDM = SFRSTCR_PIDM
             AND SHRTCKG.SHRTCKG_TERM_CODE = SFRSTCR.SFRSTCR_TERM_CODE
             AND SHRTCKG.SHRTCKG_TCKN_SEQ_NO = SFRSTCR.SFRSTCR_REG_SEQ

    WHERE
        SFRSTCR.SFRSTCR_RSTS_CODE IN ('RE', 'RW')
        AND SFRSTCR_TERM_CODE = '&t'

    ORDER BY
        SFRSTCR_NAME, SFRSTCR_CRN
    ),

--CLASS LIST
CLASS_LIST as
(
    select
        SGBSTDN_TERM_CODE_EFF,
        SPRIDEN_ID,
        SPRIDEN_PIDM,
        SPRIDEN_LEGAL_NAME,
        SPRIDEN_SEARCH_LAST_NAME,
        SPRIDEN_SEARCH_FIRST_NAME,
        SPBPERS_PREF_FIRST_NAME,
        SPRIDEN_LAST_NAME,
        SPRIDEN_FIRST_NAME,
        SPRIDEN_MI,
        GORADID_ADDITIONAL_ID,
        GOREMAL_EMAIL_ADDRESS,
        SGBSTDN_STYP_CODE,
        SGBSTDN_LEVL_CODE,
        SGBSTDN_CLAS_CODE,
        SGBSTDN_MAJR_CODE_1,
        SGBSTDN_MAJR_CODE_MINR_1,
        SGBSTDN_MAJR_CODE_MINR_1_2,
        SGBSTDN_MAJR_CODE_CONC_1,
        SGBSTDN_DEGC_CODE_1,
        SGBSTDN_STYP_DESC,
        SGBSTDN_LEVL_DESC,
        SGBSTDN_CLAS_DESC,
        SGBSTDN_MAJR_DESC,
        SGBSTDN_MINR_1_DESC,
        SGBSTDN_MINR_1_2_DESC,
        SGBSTDN_CONC_DESC,
        SGBSTDN_DEGC_DESC,
        SGBSTDN_EXP_GRAD_DATE,
        SPBPERS_AGE,
        SPBPERS_SEX,
        GORRACE_RACE_CDE,
        GORRACE_DESC,
        SPBPERS.SPBPERS_ETHN_CDE,
        SPBPERS_ETHN_DESC,
        SPBPERS_SICAS_HISP_ORIGIN,
        SPBPERS.SPBPERS_CITZ_CODE,
        SPBPERS_CITZ_COUNTRY,
        GOBINTL_NATN_CODE_BIRTH,
        GOBINTL_BIRTH_NATN

    FROM
        SPAIDEN SPRIDEN
        LEFT OUTER JOIN SPAPERS SPBPERS ON SPBPERS.SPBPERS_PIDM = SPRIDEN.SPRIDEN_PIDM
        LEFT OUTER JOIN GOARACE GORPRAC ON GORPRAC.GORPRAC_PIDM = SPRIDEN.SPRIDEN_PIDM
        LEFT OUTER JOIN SOREMAL GOREMAL ON GOREMAL.GOREMAL_PIDM = SPRIDEN.SPRIDEN_PIDM
        LEFT OUTER JOIN SGASTDN SGBSTDN ON SGBSTDN.SGBSTDN_PIDM = SPRIDEN.SPRIDEN_PIDM

    WHERE
        SGBSTDN_STST_CODE = 'AS'
        AND SGBSTDN_TERM_CODE_EFF = FY_SGBSTDN_EFF_TERM(SGBSTDN_PIDM, '&t')
    )

SELECT *

FROM
      --FA_APPLIED_STUDENTS SAP
      FA_GROSS_NEED_DISPLAY GN1_D
      --FA_GROSS_NEED GN1
      --CLASS_LIST CL1
      --COURE_ENROLLED_1 CE1
      --SCHEDULE_VIEW_1 SV1
WHERE
--DECISIONED APPLICANTS
--      SARAPPD_APDC_CODE IN ('&APDC')
      RCVAPPL_INFC_CODE = 'ISIR'
         --$addfilter

         --$beginorder

ORDER BY
        --ALL STUDENT-FACING QUERIES

        SPRIDEN_SEARCH_LAST_NAME,
        SPRIDEN_SEARCH_FIRST_NAME

        --SV1 ONLY
        --SSBSECT_SICAS_CAMP_SECTION_ID
         --$endorder