EXISTS(
SELECT *
FROM SHRDGMR
WHERE SHRDGMR_PIDM = SPRIDEN_PIDM
AND SHRDGMR_ACYR_CODE = :select_term_code.STVTERM_ACYR_CODE
AND SHRDGMR_DEGS_CODE IN (SELECT STVDEGS_CODE FROM STVDEGS))

ORDER BY
    SSBSECT_SUBJ_CODE,
    SSBSECT_CRSE_NUMB,
    SSBSECT_SEQ_NUMB,
    SPRIDEN_LAST_NAME,
    SPRIDEN_FIRST_NAME,
    SPRIDEN_MI