INFC_CODE = 'EDE'
AND EXISTS (SELECT * FROM SAAADMS SARAPPD WHERE SARAPPD_PIDM = SPRIDEN_PIDM AND SARAPPD_APDC_CODE IN ('AP','AC') AND SARAPPD_TERM_CODE_ENTRY <= (:select_term_code.STVTERM_CODE)
AND SARAPPD_TERM_CODE_ENTRY >= (:select_term_code.STVTERM_CODE - 50))

ORDER BY
    SPRIDEN_SEARCH_LAST_NAME,
    SPRIDEN_SEARCH_FIRST_NAME