EXISTS (SELECT * FROM SHATCKN WHERE SFRSTCR_PIDM = SPRIDEN_PIDM AND SFRSTCR_TERM_CODE = :select_term_code.STVTERM_CODE AND SFRSTCR_RSTS_CODE IN (SELECT STVRSTS_CODE FROM STVRSTS) AND SGBSTDN_LEVL_CODE = 'GR' AND SFRSTCR_GRDE_CODE = 'U')

-- HAVING COUNT(*)>2)

ORDER BY
    SPRIDEN_LAST_NAME,
    SPRIDEN_FIRST_NAME,
    SPRIDEN_MI