-- REPORT FORMAT
Select

     -- ESF/SU ID DETAILS
     SPRIDEN.SPRIDEN_ID Banner_ID,
     f_format_name(SPRIDEN.SPRIDEN_PIDM, 'LF30') Student_Name,
     SPRIDEN.SPRIDEN_LAST_NAME Last_Name,
     SPRIDEN.SPRIDEN_FIRST_NAME First_Name,
     GORADID.GORADID_ADDITIONAL_ID SUID,

     -- ADVISEMENT DETAILS
     f_get_desc_fnc('STVCLAS', f_class_calc_fnc(SGBSTDN.SGBSTDN_PIDM,SGBSTDN.SGBSTDN_LEVL_CODE, STVTERM.STVTERM_CODE), 30) Student_Class,
     f_get_desc_fnc('STVDEPT', SGBSTDN.SGBSTDN_DEPT_CODE, 30) Department,
     f_get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_1, 30) Major_Program,
     f_get_desc_fnc('STVDEGC', SGBSTDN.SGBSTDN_DEGC_CODE_1, 30) Degree_Program,
     SGBSTDN.SGBSTDN_PROGRAM_1 as Stdn_Program,
     SGBSTDN.SGBSTDN_STYP_CODE Reg_Type,
     SGBSTDN.SGBSTDN_STST_CODE STST_CODE,
     SGBSTDN.SGBSTDN_EXP_GRAD_DATE Exp_Grad_Date,
     f_get_desc_fnc('STVLEVL', SGBSTDN.SGBSTDN_LEVL_CODE, 30) Class_Level,

     -- EMAIL
     GOREMAL.GOREMAL_EMAIL_ADDRESS Email,

     -- COURSE INFORMATION
     SSBSECT.SSBSECT_SICAS_CAMP_COURSE_ID Course_ID,
     SSBSECT.SSBSECT_SEQ_NUMB AS Section,
     STVTERMX.STVTERM_DESC AS Semester,
     SCBCRSE.SCBCRSE_TITLE AS Title,

     -- GPA DETAILS
     trunc(SHRTGPA.SHRTGPA_GPA, 3) Semester_GPA,
     trunc(SHRLGPA.SHRLGPA_GPA, 3) Cumulative_GPA,
     SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1 Minor_1,
     SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1_2 Minor_2,
     SRVYSTU.SRVYSTU_RESIDENCY_DESC Residental_Desc,
     SPRADDR.SPRADDR_STREET_LINE1 Street_1,
     SPRADDR.SPRADDR_STREET_LINE2 Street_2,
     SPRADDR.SPRADDR_CITY City,
     SPRADDR.SPRADDR_STAT_CODE State,
     substr(SPRADDR.SPRADDR_ZIP,1,5) Zip_Code,
     SPRTELE.SPRTELE_PHONE_AREA Phone_Area,
     SPRTELE.SPRTELE_PHONE_NUMBER Phone_Number,
     substr(((sysdate - SPBPERS.SPBPERS_BIRTH_DATE)/365), 1, 2) as Age,
     --SORTING FIELDS
     STVCLAS.STVCLAS_SURROGATE_ID

-- SOURCES

FROM

-- PERSONAL IDENTIFICATION
    SPRIDEN SPRIDEN

    LEFT OUTER JOIN SPBPERS SPBPERS on SPBPERS.SPBPERS_PIDM = SPRIDEN.SPRIDEN_PIDM

    LEFT OUTER JOIN GORADID GORADID ON GORADID.GORADID_PIDM = SPRIDEN.SPRIDEN_PIDM
         AND GORADID.GORADID_ADID_CODE = 'SUID'

    -- ADDRESSING
    LEFT OUTER JOIN SPRADDR SPRADDR ON SPRADDR.SPRADDR_PIDM = SPRIDEN.SPRIDEN_PIDM
         AND SPRADDR.SPRADDR_ATYP_CODE = 'PR'
         AND SPRADDR.SPRADDR_STATUS_IND IS NULL
         AND SPRADDR.SPRADDR_VERSION = (SELECT MAX(SPRADDR_VERSION)
                                       FROM SPRADDR SPRADDRX
                                       WHERE SPRADDRX.SPRADDR_PIDM = SPRADDR.SPRADDR_PIDM
                                       AND SPRADDRX.SPRADDR_STATUS_IND IS NULL)
         AND SPRADDR.SPRADDR_SURROGATE_ID = (SELECT MAX(SPRADDR_SURROGATE_ID)
                                            FROM SPRADDR SPRADDRX
                                            WHERE SPRADDRX.SPRADDR_PIDM = SPRADDR.SPRADDR_PIDM
                                            AND SPRADDRX.SPRADDR_STATUS_IND IS NULL)

    -- EMAIL/PHONE
    LEFT OUTER JOIN GOREMAL GOREMAL ON GOREMAL.GOREMAL_PIDM = SPRIDEN.SPRIDEN_PIDM
         AND GOREMAL.GOREMAL_EMAL_CODE = 'SU'

    LEFT OUTER JOIN SPRTELE SPRTELE ON SPRTELE.SPRTELE_PIDM = SPRIDEN.SPRIDEN_PIDM
         AND SPRTELE.SPRTELE_TELE_CODE IN ('PC','PR')
         AND SPRTELE.SPRTELE_SURROGATE_ID = (SELECT MAX(SPRTELE_SURROGATE_ID)
                                            FROM SPRTELE SPRTELEX
                                            WHERE SPRTELEX.SPRTELE_PIDM = SPRTELE.SPRTELE_PIDM
                                            AND SPRTELE.SPRTELE_STATUS_IND IS NULL)

    -- TERM SELECTION
    JOIN STVTERM STVTERM ON STVTERM.STVTERM_CODE = :PARM_TERM_CODE_SELECT.STVTERM_CODE

    -- STUDENT DATA
    LEFT OUTER JOIN SGBSTDN SGBSTDN ON SGBSTDN.SGBSTDN_PIDM = SPRIDEN.SPRIDEN_PIDM
         AND SGBSTDN.SGBSTDN_TERM_CODE_EFF = FY_SGBSTDN_EFF_TERM(SGBSTDN.SGBSTDN_PIDM, STVTERM.STVTERM_CODE)
         AND SGBSTDN.SGBSTDN_MAJR_CODE_1 NOT IN ('0000', 'EHS', 'SUS', 'VIS', 'UNDC')
         AND SGBSTDN.SGBSTDN_STST_CODE = 'AS'

    -- SECOND ORDER STUDENT DATA
    LEFT OUTER JOIN SGBSTDN SGBSTDNX ON SGBSTDNX.SGBSTDN_PIDM = SPRIDEN.SPRIDEN_PIDM
         AND SGBSTDNX.SGBSTDN_TERM_CODE_EFF < FY_SGBSTDN_EFF_TERM(SGBSTDN.SGBSTDN_PIDM, STVTERM.STVTERM_CODE)
         AND SGBSTDNX.SGBSTDN_MAJR_CODE_1 IN ('EHS')
         AND SGBSTDNX.SGBSTDN_STST_CODE = 'AS'

    -- CUMULATIVE GPA DATA
    LEFT OUTER JOIN SHRLGPA SHRLGPA ON SHRLGPA.SHRLGPA_PIDM = SPRIDEN.SPRIDEN_PIDM
         AND SHRLGPA.SHRLGPA_LEVL_CODE = SGBSTDN.SGBSTDN_LEVL_CODE
         AND SHRLGPA.SHRLGPA_GPA_TYPE_IND = 'I'

    -- TERM GPA DATA
    LEFT OUTER JOIN SHRTGPA SHRTGPA ON SHRTGPA.SHRTGPA_PIDM = SPRIDEN.SPRIDEN_PIDM
         AND SHRTGPA.SHRTGPA_TERM_CODE = STVTERM.STVTERM_CODE
         AND SHRTGPA.SHRTGPA_LEVL_CODE = SGBSTDN.SGBSTDN_LEVL_CODE
         AND SHRTGPA.SHRTGPA_GPA_TYPE_IND = 'I'

    -- STUDENT COURSE REGISTATIONS
    LEFT OUTER JOIN SFRSTCR SFRSTCR ON SFRSTCR.SFRSTCR_PIDM = SGBSTDNX.SGBSTDN_PIDM
         AND SFRSTCR.SFRSTCR_TERM_CODE = SGBSTDNX.SGBSTDN_TERM_CODE_EFF

    LEFT OUTER JOIN SSBSECT SSBSECT ON SSBSECT.SSBSECT_TERM_CODE = SFRSTCR.SFRSTCR_TERM_CODE
         AND SSBSECT.SSBSECT_CRN = SFRSTCR.SFRSTCR_CRN

    -- COURSE DETAILS
    LEFT OUTER JOIN SCBCRSE SCBCRSE ON SCBCRSE.SCBCRSE_SUBJ_CODE = SSBSECT.SSBSECT_SUBJ_CODE
         AND SCBCRSE.SCBCRSE_CRSE_NUMB = SSBSECT.SSBSECT_CRSE_NUMB
         AND SCBCRSE.SCBCRSE_EFF_TERM <= (SELECT MAX(SCBCRSE.SCBCRSE_EFF_TERM)
                                         FROM SCBCRSE SCBCRSEX
                                         WHERE SCBCRSEX.SCBCRSE_SUBJ_CODE = SSBSECT.SSBSECT_SUBJ_CODE
                                         AND SCBCRSEX.SCBCRSE_CRSE_NUMB = SSBSECT.SSBSECT_CRSE_NUMB
                                         AND SCBCRSEX.SCBCRSE_EFF_TERM <= SSBSECT.SSBSECT_TERM_CODE
                                    )

    -- SURVERY CONFIRMATION
    LEFT OUTER JOIN SRVYSTU SRVYSTU ON SRVYSTU.SRVYSTU_PIDM = SPRIDEN.SPRIDEN_PIDM
         AND SRVYSTU_TERM_CODE = STVTERM.STVTERM_CODE
         AND SRVYSTU_STATUS_CODE = 'AS'
         AND SRVYSTU_TYPE_CODE NOT IN ('X')
         AND SRVYSTU_PRETERM_CLASS_YR_CODE NOT IN ('BG')
         AND SRVYSTU_POSTERM_CLASS_YR_CODE NOT IN ('BG')
         AND SRVYSTU_CURRIC_1_MAJOR_CODE NOT IN ('UNDC','SUS','VIS', '0000', 'EHS')

    -- ADDITIONAL DETAILS
    LEFT OUTER JOIN STVTERM STVTERMX ON STVTERMX.STVTERM_CODE = SFRSTCR.SFRSTCR_TERM_CODE

    LEFT OUTER JOIN STVCLAS STVCLAS ON STVCLAS.STVCLAS_CODE = F_CLASS_CALC_FNC(SGBSTDN.SGBSTDN_PIDM,SGBSTDN.SGBSTDN_LEVL_CODE, STVTERM.STVTERM_CODE)

-- CONDITIONS
WHERE
     SPRIDEN.SPRIDEN_NTYP_CODE IS NULL
     AND SPRIDEN.SPRIDEN_CHANGE_IND IS NULL

--$ADDFILTER

--$BEGINORDER

-- GROUPING/SORTING
ORDER BY
     SPRIDEN.SPRIDEN_SEARCH_LAST_NAME

--$ENDORDER
