SFRSTCR.PREV_TERM_CODE != SFRSTCR.SFRSTCR_TERM_CODE
and SFRSTCR.SUBJ_CODE = SFRSTCR.SSBSECT_SUBJ_CODE
and SFRSTCR.CRSE_NUMB = SFRSTCR.SSBSECT_CRSE_NUMB
and SFRSTCR.PREV_GRDE_CODE not in ( 'F', 'I', 'IF', 'IU', 'NR', 'U', 'UAU', 'V', 'W', 'WF')

ORDER BY
    SPRIDEN_LAST_NAME,
    SPRIDEN_FIRST_NAME,
    SPRIDEN_MI