SFRSTCR_TERM_CODE = :select_term_code.STVTERM_CODE
AND SFRSTCR_RSTS_CODE = 'RE'
AND SFRSTCR_GRDE_CODE IN ('WF','F')
--AND SFRSTCR_GRDE_CODE_MID IN ('WF','F')
--AND SHRTCKG_GRDE_CODE_FINAL IN ('WF','F')

ORDER BY
    SPRIDEN_LAST_NAME,
    SPRIDEN_FIRST_NAME,
    SPRIDEN_MI