SFRSTCR.SFRSTCR_TERM_CODE <= STVTERM.STVTERM_CODE
AND SFRSTCR.SFRSTCR_RSTS_CODE = 'RE'
AND :search_UID is not null
AND SPRIDEN_ID = :search_UID

ORDER BY
    SPRIDEN_LAST_NAME,
    SPRIDEN_FIRST_NAME
