EXISTS(SELECT *
      FROM   SHAGPAR
      WHERE  SHRTGPA_PIDM = SPRIDEN_PIDM
      AND    SGBSTDN_STYP_CODE NOT IN ('G','T','F','N')
      AND    SGBSTDN_LEVL_CODE NOT IN ('GR')
      AND    (SHRLGPA_GPA > 3.1750000))

AND 'Y' = F_REGISTERED_THIS_TERM(SPRIDEN_PIDM, :select_term_code.STVTERM_CODE)

ORDER BY
    SPRIDEN_LAST_NAME,
    SPRIDEN_FIRST_NAME,
    SPRIDEN_MI
