EXISTS(
    SELECT *
    FROM SHRTTRM
    WHERE SHRTTRM_PIDM = SPRIDEN_PIDM
    AND (SHRTTRM_ASTD_CODE_END_OF_TERM LIKE 'P%'
    AND SHRTTRM_TERM_CODE = (SELECT MAX(SHRTTRM_TERM_CODE)
                            FROM    SHRTTRM TTRM
                            WHERE   TTRM.SHRTTRM_PIDM = SHRTTRM.SHRTTRM_PIDM
                            AND     TTRM.SHRTTRM_TERM_CODE < :select_term_code.STVTERM_CODE)))
AND SGBSTDN_LEVL_CODE = 'UG'
AND SGBSTDN_STYP_CODE <> 'X'
AND SGBSTDN_MAJR_CODE_1 NOT IN ('0000', 'UNDC', 'EHS', 'SUS', 'VIS')
AND SPRADDR_ATYP_CODE IN ('PR')