with SPAIDEN as
(
    SELECT
        SPRIDEN.SPRIDEN_ID,
        SPRIDEN.SPRIDEN_PIDM,
        SPRIDEN.SPRIDEN_LAST_NAME,
        SPRIDEN.SPRIDEN_FIRST_NAME,
        SPRIDEN.SPRIDEN_MI,
        f_format_name(SPRIDEN.SPRIDEN_PIDM, 'LFMI') as SPRIDEN_LEGAL_NAME,
        SPRIDEN.SPRIDEN_SEARCH_LAST_NAME,
        SPRIDEN.SPRIDEN_SEARCH_FIRST_NAME,
        SPRIDEN.SPRIDEN_SEARCH_MI

    FROM
        SPRIDEN SPRIDEN

    WHERE
        SPRIDEN.SPRIDEN_NTYP_CODE IS NULL
        AND SPRIDEN.SPRIDEN_CHANGE_IND IS NULL
    ),

SPAPERS as
(
    SELECT
        SPBPERS.SPBPERS_PIDM,
        SPBPERS.SPBPERS_SSN,
        SPBPERS.SPBPERS_BIRTH_DATE,
        ROUND(((SYSDATE - SPBPERS_BIRTH_DATE)/365), 0) as SPBPERS_AGE,
        SPBPERS.SPBPERS_SEX,
        SPBPERS.SPBPERS_PREF_FIRST_NAME,
        SPBPERS.SPBPERS_CITZ_CODE,
        SPBPERS.SPBPERS_ETHN_CDE,
        f_get_desc_fnc('STVETHN', SPBPERS_ETHN_CDE, 30) as SPBPERS_ETHN_DESC,
        case
          when SPBPERS_ETHN_CDE in (2,3,4,5,6,7,9,10) then 'Y'
            else 'N'
              end as SPBPERS_SICAS_HISP_ORIGIN,
        CASE
            WHEN SPBPERS.SPBPERS_CITZ_CODE = 'Y' THEN 'United States'
            ELSE (SELECT STVNATN_NATION
                 FROM STVNATN
                 WHERE STVNATN_CODE = NVL(GOBINTL.GOBINTL_NATN_CODE_LEGAL, GOBINTL.GOBINTL_NATN_CODE_BIRTH))
            END as SPBPERS_CITZ_COUNTRY,
        SPBPERS.SPBPERS_GNDR_CODE,
        GOBINTL_NATN_CODE_BIRTH,
        f_get_desc_fnc('STVNATN', GOBINTL_NATN_CODE_BIRTH, 30) as GOBINTL_BIRTH_NATN

   FROM
        SPBPERS SPBPERS
        LEFT OUTER JOIN GOBINTL GOBINTL ON GOBINTL.GOBINTL_PIDM = SPBPERS.SPBPERS_PIDM
   ),

GOARACE as
(
    SELECT
        GORPRAC.GORPRAC_PIDM as GORPRAC_PIDM,
        (listagg(GORPRAC.GORPRAC_RACE_CDE,', ') within group (order by GORPRAC.GORPRAC_RACE_CDE)) as GORRACE_RACE_CDE,
        (listagg(GORRACE.GORRACE_DESC,', ') within group (order by GORRACE.GORRACE_DESC)) as GORRACE_DESC

    FROM
        GORPRAC GORPRAC

    LEFT OUTER JOIN GORRACE GORRACE ON GORRACE.GORRACE_RACE_CDE = GORPRAC.GORPRAC_RACE_CDE

    GROUP BY
        GORPRAC.GORPRAC_PIDM
    ),

SOREMAL as
(
    SELECT
        GOREMAL.GOREMAL_PIDM,
        GOREMAL.GOREMAL_EMAL_CODE,
        GOREMAL.GOREMAL_EMAIL_ADDRESS,
        GOREMAL.GOREMAL_STATUS_IND,
        GOREMAL.GOREMAL_PREFERRED_IND,
        GORADID.GORADID_PIDM,
        GORADID.GORADID_ADDITIONAL_ID,
        GORADID.GORADID_ADID_CODE,
        GOBTPAC.GOBTPAC_EXTERNAL_USER --esfid

    FROM
        GOREMAL GOREMAL
        LEFT OUTER JOIN GORADID GORADID ON GORADID.GORADID_PIDM = GOREMAL.GOREMAL_PIDM
             AND GORADID.GORADID_ADID_CODE = 'SUID'
        LEFT OUTER JOIN GOBUMAP GOBUMAP ON GOBUMAP.GOBUMAP_PIDM = GOREMAL.GOREMAL_PIDM
        LEFT OUTER JOIN GOBTPAC GOBTPAC ON GOBTPAC.GOBTPAC_PIDM = GOREMAL.GOREMAL_PIDM

    WHERE
        GOREMAL.GOREMAL_EMAL_CODE = 'SU'
        AND GOREMAL.GOREMAL_STATUS_IND = 'A'
        AND GOREMAL.GOREMAL_PREFERRED_IND = 'Y'
        AND GORADID.GORADID_ADID_CODE = 'SUID'
    ),

SGASTDN as
(
    select
        SGBSTDN.SGBSTDN_PIDM,
        SGBSTDN.SGBSTDN_TERM_CODE_EFF,
        SGBSTDN.SGBSTDN_STST_CODE,
        SGBSTDN.SGBSTDN_LEVL_CODE,
        SGBSTDN.SGBSTDN_STYP_CODE,
        SGBSTDN.SGBSTDN_TERM_CODE_MATRIC,
        SGBSTDN.SGBSTDN_TERM_CODE_ADMIT,
        SGBSTDN.SGBSTDN_EXP_GRAD_DATE,
        SGBSTDN.SGBSTDN_CAMP_CODE,
        SGBSTDN.SGBSTDN_COLL_CODE_1,
        SGBSTDN.SGBSTDN_DEGC_CODE_1,
        SGBSTDN.SGBSTDN_MAJR_CODE_1,
        SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1,
        SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1_2,
        SGBSTDN.SGBSTDN_MAJR_CODE_CONC_1,
        SGBSTDN.SGBSTDN_RESD_CODE,
        SGBSTDN.SGBSTDN_ADMT_CODE,
        SGBSTDN.SGBSTDN_DEPT_CODE,
        SGBSTDN.SGBSTDN_PROGRAM_1,
        SGBSTDN.SGBSTDN_TERM_CODE_GRAD,
        SGBSTDN.SGBSTDN_ACTIVITY_DATE,
        f_class_calc_fnc(SGBSTDN.SGBSTDN_PIDM, SGBSTDN.SGBSTDN_LEVL_CODE, :select_term_code.STVTERM_CODE) as SGBSTDN_CLAS_CODE,
        f_Get_desc_fnc('STVSTST',SGBSTDN.SGBSTDN_STST_CODE, 30) as SGBSTDN_STST_DESC,
        f_Get_desc_fnc('STVLEVL', SGBSTDN.SGBSTDN_LEVL_CODE, 30) as SGBSTDN_LEVL_DESC,
        f_Get_desc_fnc('STVSTYP', SGBSTDN.SGBSTDN_STYP_CODE, 30) as SGBSTDN_STYP_DESC,
        f_Get_desc_fnc('STVDEGC', SGBSTDN.SGBSTDN_DEGC_CODE_1, 30) as SGBSTDN_DEGC_DESC,
        f_Get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_1, 30) as SGBSTDN_MAJR_DESC,
        f_Get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1, 30) as SGBSTDN_MINR_1_DESC,
        f_Get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1_2, 30) as SGBSTDN_MINR_1_2_DESC,
        f_Get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_CONC_1, 30) as SGBSTDN_CONC_DESC,
        f_Get_desc_fnc('STVRESD', SGBSTDN.SGBSTDN_RESD_CODE, 30) as SGBSTDN_RESD_DESC,
        f_Get_desc_fnc('STVADMT', SGBSTDN.SGBSTDN_ADMT_CODE, 30) as SGBSTDN_ADMT_DESC,
        f_Get_desc_fnc('STVDEPT', SGBSTDN.SGBSTDN_DEPT_CODE, 30) as SGBSTDN_DEPT_DESC,
        f_Get_desc_fnc('STVTERM', SGBSTDN.SGBSTDN_TERM_CODE_MATRIC, 30) as SGBSTDN_MATRIC_TERM_DESC,
        f_Get_desc_fnc('STVTERM', SGBSTDN.SGBSTDN_TERM_CODE_GRAD, 30) as SGBSTDN_GRAD_TERM_DESC,
        f_Get_desc_fnc('STVCLAS', f_class_calc_fnc(SGBSTDN.SGBSTDN_PIDM,SGBSTDN.SGBSTDN_LEVL_CODE, :select_term_code.STVTERM_CODE), 30) as SGBSTDN_CLAS_DESC

   from
        SGBSTDN SGBSTDN
   ),

SFAREGS as
(
 select
        f_format_name(SFRSTCR_PIDM, 'LF30') as SFRSTCR_NAME,
        SFRSTCR_TERM_CODE,
        SFRSTCR_PIDM,
        SFRSTCR_CRN,
        SFRSTCR_CLASS_SORT_KEY,
        SFRSTCR_REG_SEQ,
        SFRSTCR_PTRM_CODE,
        SFRSTCR_RSTS_CODE,
        SFRSTCR_BILL_HR,
        SFRSTCR_WAIV_HR,
        SFRSTCR_CREDIT_HR,
        SFRSTCR_BILL_HR_HOLD,
        SFRSTCR_CREDIT_HR_HOLD,
        SFRSTCR_GMOD_CODE,
        SFRSTCR_GRDE_CODE,
        SFRSTCR_GRDE_DATE,
        SFRSTCR_ADD_DATE,
        SFRSTCR_LEVL_CODE,
        SFRSTCR_CAMP_CODE,
        SHRTCKG_PIDM,
        SHRTCKG_TERM_CODE,
        SHRTCKG_TCKN_SEQ_NO,
        SHRTCKG_SEQ_NO,
        SHRTCKG_FINAL_GRDE_SEQ_NO,
        SHRTCKG_GRDE_CODE_FINAL,
        SHRTCKG_GMOD_CODE,
        SHRTCKG_CREDIT_HOURS,
        SHRTCKG_GCHG_CODE,
        SHRTCKG_FINAL_GRDE_CHG_DATE,
        SHRTCKG_HOURS_ATTEMPTED,
        SHRTCKG_GRDE_CODE_INCMP_FINAL,
        SHRTCKG_SURROGATE_ID,
        SHRTCKG_VERSION,
        case
          WHEN SHRTCKG_GCHG_CODE IS NULL THEN NULL
            ELSE F_GET_DESC_FNC('STVGCHG', SHRTCKG_GCHG_CODE, 30)
              END as SHRTCKG_GCHG_DESC

    FROM
        SFRSTCR SFRSTCR

        LEFT OUTER JOIN SHRTCKG SHRTCKG ON SHRTCKG_PIDM = SFRSTCR_PIDM
             AND SHRTCKG.SHRTCKG_TERM_CODE = SFRSTCR.SFRSTCR_TERM_CODE
             AND SHRTCKG.SHRTCKG_TCKN_SEQ_NO = SFRSTCR.SFRSTCR_REG_SEQ

    WHERE
        SFRSTCR.SFRSTCR_RSTS_CODE IN ('RE', 'RW')
        AND SFRSTCR_TERM_CODE = :select_term_code.STVTERM_CODE

    ORDER BY
        SFRSTCR_NAME, SFRSTCR_CRN
    ),

SSASECT as
(
 SELECT
        SSBSECT_TERM_CODE,
        SSBSECT_CRN,
        SSBSECT_PTRM_CODE,
        SSBSECT_SUBJ_CODE,
        SSBSECT_CRSE_NUMB,
        SSBSECT_SEQ_NUMB,
        SSBSECT_SSTS_CODE,
        SSBSECT_SCHD_CODE,
        SSBSECT_CAMP_CODE,
        SSBSECT_CREDIT_HRS,
        SSBSECT_BILL_HRS,
        SSBSECT_GMOD_CODE,
        SSBSECT_REG_ONEUP,
        SSBSECT_PRIOR_ENRL,
        SSBSECT_PROJ_ENRL,
        SSBSECT_MAX_ENRL,
        SSBSECT_ENRL,
        SSBSECT_SEATS_AVAIL,
        SSBSECT_TOT_CREDIT_HRS,
        SSBSECT_CENSUS_ENRL,
        SSBSECT_CENSUS_ENRL_DATE,
        SSBSECT_ACTIVITY_DATE,
        SSBSECT_PTRM_START_DATE,
        SSBSECT_PTRM_END_DATE,
        SSBSECT_PTRM_WEEKS,
        SSBSECT_WAIT_CAPACITY,
        SSBSECT_WAIT_COUNT,
        SSBSECT_WAIT_AVAIL,
        SSBSECT_INSM_CODE,
        SSBSECT_SURROGATE_ID,
        SSBSECT_VERSION,
        SSBSECT_SICAS_CAMP_COURSE_ID,
        SSBSECT_SICAS_CAMP_SECTION_ID,
        SCBCRSE_SUBJ_CODE,
        SCBCRSE_CRSE_NUMB,
        SCBCRSE_EFF_TERM,
        SCBCRSE_COLL_CODE,
        SCBCRSE_DIVS_CODE,
        SCBCRSE_DEPT_CODE,
        SCBCRSE_CSTA_CODE,
        SCBCRSE_TITLE,
        SCBCRSE_CIPC_CODE,
        SCBCRSE_CREDIT_HR_IND,
        SCBCRSE_CREDIT_HR_LOW,
        SCBCRSE_CREDIT_HR_HIGH,
        SCBCRSE_LEC_HR_IND,
        SCBCRSE_LEC_HR_LOW,
        SCBCRSE_LEC_HR_HIGH,
        SCBCRSE_BILL_HR_IND,
        SCBCRSE_BILL_HR_LOW,
        SCBCRSE_BILL_HR_HIGH,
        SCBCRSE_ACTIVITY_DATE,
        SCBCRSE_CONT_HR_LOW,
        SCBCRSE_CONT_HR_IND,
        SCBCRSE_CONT_HR_HIGH,
        SCBCRSE_REPS_CODE,
        SCBCRSE_MAX_RPT_UNITS,
        SCBCRSE_SURROGATE_ID,
        SCBCRSE_VERSION,
        SCBCRSE_VPDI_CODE,
        SCBCRSE_SICAS_SUNY_ID,
        SSRMEET_TERM_CODE,
        SSRMEET_CRN,
        SSRMEET_DAYS_CODE,
        SSRMEET_DAY_NUMBER,
        SSRMEET_BEGIN_TIME,
        SSRMEET_END_TIME,
        SSRMEET_BLDG_CODE,
        SSRMEET_ROOM_CODE,
        SSRMEET_ACTIVITY_DATE,
        SSRMEET_START_DATE,
        SSRMEET_END_DATE,
        SSRMEET_SUN_DAY,
        SSRMEET_MON_DAY,
        SSRMEET_TUE_DAY,
        SSRMEET_WED_DAY,
        SSRMEET_THU_DAY,
        SSRMEET_FRI_DAY,
        SSRMEET_SAT_DAY,
        SSRMEET_SCHD_CODE,
        SSRMEET_CREDIT_HR_SESS,
        SSRMEET_MEET_NO,
        SSRMEET_HRS_WEEK,
        SSRMEET_MTYP_CODE,
        SSRMEET_SURROGATE_ID,
        SSRMEET_VERSION,
        F_GET_DESC_FNC('STVSSTS', SSBSECT_SSTS_CODE, 30) as SSBSECT_SSTS_DESC,
        F_GET_DESC_FNC('STVCSTA', SCBCRSE_CSTA_CODE, 30) as SCBCRSE_CSTA_DESC,
        F_GET_DESC_FNC('STVREPS', SCBCRSE_REPS_CODE, 30) as SCBCRSE_REPS_DESC,
        F_GET_DESC_FNC('STVREPS', SSRMEET_MTYP_CODE, 30) as SSRMEET_MTYP_DESC

    FROM
        SSBSECT SSBSECT

        LEFT OUTER JOIN SCBCRSE SCBCRSE ON SSBSECT_SUBJ_CODE = SCBCRSE.SCBCRSE_SUBJ_CODE
             AND SCBCRSE.SCBCRSE_CRSE_NUMB = SSBSECT_CRSE_NUMB
        LEFT OUTER JOIN SSRMEET SSRMEET ON SSRMEET.SSRMEET_TERM_CODE = SSBSECT.SSBSECT_TERM_CODE
             AND SSRMEET.SSRMEET_CRN = SSBSECT.SSBSECT_CRN

    WHERE
        SCBCRSE_EFF_TERM = (SELECT MAX(SCBCRSE_EFF_TERM)
                           FROM   SCBCRSE SCBCRSEX
                           WHERE  SCBCRSEX.SCBCRSE_SUBJ_CODE = SSBSECT_SUBJ_CODE
                           AND    SCBCRSEX.SCBCRSE_CRSE_NUMB = SSBSECT_CRSE_NUMB
                           AND    SCBCRSEX.SCBCRSE_EFF_TERM <= SSBSECT.SSBSECT_TERM_CODE)
    ORDER BY
        --SSBSECT_SICAS_CAMP_COURSE_ID
        SSBSECT_SICAS_CAMP_SECTION_ID
    ),

--SCHEDULE OF CLASSES
SCHEDULE_VIEW_1 as
(
    SELECT
        SSBSECT_TERM_CODE,
        SSBSECT_CRN,
        SSBSECT_PTRM_CODE,
        SSBSECT_SUBJ_CODE,
        SSBSECT_CRSE_NUMB,
        SSBSECT_SEQ_NUMB,
        SCBCRSE_TITLE,
        SSBSECT_SICAS_CAMP_COURSE_ID,
        SSBSECT_SCHD_CODE,
        SSBSECT_CAMP_CODE,
        SSBSECT_CREDIT_HRS,
        SSBSECT_BILL_HRS,
        SSBSECT_GMOD_CODE,
        SSBSECT_REG_ONEUP,
        SSBSECT_PRIOR_ENRL,
        SSBSECT_PROJ_ENRL,
        SSBSECT_MAX_ENRL,
        SSBSECT_ENRL,
        SSBSECT_SEATS_AVAIL,
        SSBSECT_TOT_CREDIT_HRS,
        SSBSECT_CENSUS_ENRL,
        SSBSECT_CENSUS_ENRL_DATE,
        SSBSECT_ACTIVITY_DATE,
        SSBSECT_PTRM_START_DATE,
        SSBSECT_PTRM_END_DATE,
        SSBSECT_PTRM_WEEKS,
        SSBSECT_WAIT_CAPACITY,
        SSBSECT_WAIT_COUNT,
        SSBSECT_WAIT_AVAIL,
        SSBSECT_SICAS_CAMP_SECTION_ID,
        SSRMEET_TERM_CODE,
        SSRMEET_CRN,
        SSRMEET_BEGIN_TIME,
        SSRMEET_END_TIME,
        SSRMEET_BLDG_CODE,
        SSRMEET_ROOM_CODE,
        SSRMEET_START_DATE,
        SSRMEET_END_DATE,
        SSRMEET_MON_DAY,
        SSRMEET_TUE_DAY,
        SSRMEET_WED_DAY,
        SSRMEET_THU_DAY,
        SSRMEET_FRI_DAY,
        SSRMEET_SAT_DAY,
        SSRMEET_CREDIT_HR_SESS,
        SSRMEET_MEET_NO,
        SSRMEET_HRS_WEEK

    FROM
        SSASECT SSBSECT

    WHERE
       SSBSECT_TERM_CODE = :select_term_code.STVTERM_CODE

    ORDER BY
        --SSBSECT_SICAS_CAMP_COURSE_ID
        SSBSECT_SICAS_CAMP_SECTION_ID
    ),

--CLASS LIST
CLASS_LIST as (
    select
        SGBSTDN_TERM_CODE_EFF,
        SPRIDEN_ID,
        SPRIDEN_PIDM,
        SPRIDEN_LEGAL_NAME,
        SPRIDEN_SEARCH_LAST_NAME,
        SPRIDEN_SEARCH_FIRST_NAME,
        SPBPERS_PREF_FIRST_NAME,
        SPRIDEN_LAST_NAME,
        SPRIDEN_FIRST_NAME,
        SPRIDEN_MI,
        GORADID_ADDITIONAL_ID,
        GOREMAL_EMAIL_ADDRESS,
        SGBSTDN_STYP_CODE,
        SGBSTDN_LEVL_CODE,
        SGBSTDN_CLAS_CODE,
        SGBSTDN_MAJR_CODE_1,
        SGBSTDN_MAJR_CODE_MINR_1,
        SGBSTDN_MAJR_CODE_MINR_1_2,
        SGBSTDN_MAJR_CODE_CONC_1,
        SGBSTDN_DEGC_CODE_1,
        SGBSTDN_STYP_DESC,
        SGBSTDN_LEVL_DESC,
        SGBSTDN_CLAS_DESC,
        SGBSTDN_MAJR_DESC,
        SGBSTDN_MINR_1_DESC,
        SGBSTDN_MINR_1_2_DESC,
        SGBSTDN_CONC_DESC,
        SGBSTDN_DEGC_DESC,
        SGBSTDN_EXP_GRAD_DATE,
        SPBPERS_AGE,
        SPBPERS_SEX,
        GORRACE_RACE_CDE,
        GORRACE_DESC,
        SPBPERS.SPBPERS_ETHN_CDE,
        SPBPERS_ETHN_DESC,
        SPBPERS_SICAS_HISP_ORIGIN,
        SPBPERS.SPBPERS_CITZ_CODE,
        SPBPERS_CITZ_COUNTRY,
        GOBINTL_NATN_CODE_BIRTH,
        GOBINTL_BIRTH_NATN

    FROM
        SPAIDEN SPRIDEN
        LEFT OUTER JOIN SPAPERS SPBPERS ON SPBPERS.SPBPERS_PIDM = SPRIDEN.SPRIDEN_PIDM
        LEFT OUTER JOIN GOARACE GORPRAC ON GORPRAC.GORPRAC_PIDM = SPRIDEN.SPRIDEN_PIDM
        LEFT OUTER JOIN SOREMAL GOREMAL ON GOREMAL.GOREMAL_PIDM = SPRIDEN.SPRIDEN_PIDM
        LEFT OUTER JOIN SGASTDN SGBSTDN ON SGBSTDN.SGBSTDN_PIDM = SPRIDEN.SPRIDEN_PIDM

    WHERE
        SGBSTDN_STST_CODE = 'AS'
        AND SGBSTDN_TERM_CODE_EFF = FY_SGBSTDN_EFF_TERM(SGBSTDN_PIDM, :select_term_code.STVTERM_CODE)
    /*
    ORDER BY
        --SSBSECT_SICAS_CAMP_COURSE_ID
        SPRIDEN.SPRIDEN_SEARCH_LAST_NAME,
        SPRIDEN.SPRIDEN_SEARCH_FIRST_NAME
        */
    ),

--CLASS LIST
CLASS_LIST_PANEL as (
    select
        SGBSTDN_TERM_CODE_EFF,
        F_GET_DESC_FNC('STVTERM', SGBSTDN_TERM_CODE_EFF, 30) as EFF_SEMESTER,
        SPRIDEN_PIDM,
        SPRIDEN_ID as IDN,
        SPRIDEN_LEGAL_NAME as NAME,
        SPRIDEN_SEARCH_LAST_NAME as LAST,
        SPRIDEN_SEARCH_FIRST_NAME as FIRST,
        SPRIDEN_MI as MIDDLE,
        GORADID_ADDITIONAL_ID as SUID,
        GOREMAL_EMAIL_ADDRESS as EMAIL,
        SPBPERS_AGE as AGE,
        SPBPERS_SEX as SEX,
        GORRACE_DESC as RACE,
        SPBPERS_ETHN_DESC as ETHNICITY,
        SPBPERS_SICAS_HISP_ORIGIN AS HSIP_ORIGIN

    FROM
        SPAIDEN SPRIDEN
        LEFT OUTER JOIN SPAPERS SPBPERS ON SPBPERS.SPBPERS_PIDM = SPRIDEN.SPRIDEN_PIDM
        LEFT OUTER JOIN GOARACE GORPRAC ON GORPRAC.GORPRAC_PIDM = SPRIDEN.SPRIDEN_PIDM
        LEFT OUTER JOIN SOREMAL GOREMAL ON GOREMAL.GOREMAL_PIDM = SPRIDEN.SPRIDEN_PIDM
        LEFT OUTER JOIN SGASTDN SGBSTDN ON SGBSTDN.SGBSTDN_PIDM = SPRIDEN.SPRIDEN_PIDM

    WHERE
        SGBSTDN_STST_CODE = 'AS'
        AND SGBSTDN_TERM_CODE_EFF = FY_SGBSTDN_EFF_TERM(SGBSTDN_PIDM, :select_term_code.STVTERM_CODE)
    /*
    ORDER BY
        --SSBSECT_SICAS_CAMP_COURSE_ID
        SPRIDEN.SPRIDEN_SEARCH_LAST_NAME,
        SPRIDEN.SPRIDEN_SEARCH_FIRST_NAME
        */
    ),

--CLASS LIST AND GRADES
GRADES_VIEW_1 as
(
select
        SSBSECT_TERM_CODE,
        SSBSECT_CRN,
        SSBSECT_PTRM_CODE,
        SSBSECT_SUBJ_CODE,
        SSBSECT_CRSE_NUMB,
        SSBSECT_SEQ_NUMB,
        SCBCRSE_TITLE,
        SSBSECT_SICAS_CAMP_COURSE_ID,
        SSBSECT_SICAS_CAMP_SECTION_ID,
        SPRIDEN_PIDM,
        SPRIDEN_ID,
        SPRIDEN_SEARCH_LAST_NAME,
        SPRIDEN_SEARCH_FIRST_NAME,
        GORADID_ADDITIONAL_ID,
        GOREMAL_EMAIL_ADDRESS,
        SGBSTDN_STST_CODE,
        SGBSTDN_LEVL_CODE,
        SGBSTDN_STYP_CODE,
        SGBSTDN_TERM_CODE_MATRIC,
        SGBSTDN_DEGC_CODE_1,
        SGBSTDN_MAJR_CODE_1,
        SFRSTCR_TERM_CODE,
        SFRSTCR_PIDM,
        f_format_name(SFRSTCR_PIDM, 'LF30') as SFRSTCR_NAME,
        SFRSTCR_CRN,
        SFRSTCR_REG_SEQ,
        SFRSTCR_PTRM_CODE,
        SFRSTCR_RSTS_CODE,
        SFRSTCR_GMOD_CODE,
        SFRSTCR_GRDE_CODE,
        SFRSTCR_GRDE_DATE,
        SFRSTCR_ADD_DATE,
        SFRSTCR_LEVL_CODE,
        SFRSTCR_CAMP_CODE,
        SHRTCKG_PIDM,
        SHRTCKG_TERM_CODE,
        SHRTCKG_TCKN_SEQ_NO,
        SHRTCKG_SEQ_NO,
        SHRTCKG_FINAL_GRDE_SEQ_NO,
        SHRTCKG_GRDE_CODE_FINAL,
        SHRTCKG_GMOD_CODE,
        SHRTCKG_CREDIT_HOURS,
        SHRTCKG_GCHG_CODE,
        SHRTCKG_GCHG_DESC,
        SHRTCKG_FINAL_GRDE_CHG_DATE,
        SHRTCKG_HOURS_ATTEMPTED,
        SHRTCKG_GRDE_CODE_INCMP_FINAL,
        SHRTCKG_SURROGATE_ID,
        SHRTCKG_VERSION
    from
        SSASECT SSBSECT
        LEFT OUTER JOIN SFAREGS SFRSTCR on SSBSECT.SSBSECT_TERM_CODE = SFRSTCR.SFRSTCR_TERM_CODE
             AND SSBSECT.SSBSECT_CRN = SFRSTCR_CRN

        LEFT OUTER JOIN SPAIDEN SPRIDEN ON SPRIDEN.SPRIDEN_PIDM = SFRSTCR.SFRSTCR_PIDM
        LEFT OUTER JOIN SOREMAL GOREMAL ON GOREMAL.GOREMAL_PIDM = SFRSTCR.SFRSTCR_PIDM
        LEFT OUTER JOIN SGASTDN SGBSTDN ON SGBSTDN.SGBSTDN_PIDM = SFRSTCR.SFRSTCR_PIDM

    WHERE
       SSBSECT_TERM_CODE = :select_term_code.STVTERM_CODE
       AND SGBSTDN_STST_CODE = 'AS'
       AND SGBSTDN_TERM_CODE_EFF = FY_SGBSTDN_EFF_TERM(SGBSTDN_PIDM, :select_term_code.STVTERM_CODE)
       /*
       AND SGBSTDN_TERM_CODE_EFF = (SELECT MAX(SGBSTDN_TERM_CODE_EFF)
                                   FROM SGBSTDN S
                                   WHERE S.SGBSTDN_PIDM = SGBSTDN.SGBSTDN_PIDM
                                   AND S.SGBSTDN_STST_CODE = 'AS'
                                   AND S.SGBSTDN_TERM_CODE_EFF <= :select_term_code.STVTERM_CODE)
                                   */
    ORDER BY
        SSBSECT_SICAS_CAMP_SECTION_ID
       )

SELECT
        EFF_SEMESTER,
        IDN,
        NAME,
        LAST,
        FIRST,
        MIDDLE,
        SUID,
        EMAIL,
        AGE,
        SEX,
        RACE,
        ETHNICITY,
        HSIP_ORIGIN

FROM
      --CLASS_LIST CL1
      CLASS_LIST_PANEL CL2
      --COURE_ENROLLED_1 CE1
      --SCHEDULE_VIEW_1 SV1
WHERE
--ENROLLED STUDENT
      EXISTS (SELECT * FROM SFAREGS WHERE SFRSTCR_PIDM = SPRIDEN_PIDM AND SFRSTCR_TERM_CODE = :select_term_code.STVTERM_CODE AND SFRSTCR_RSTS_CODE IN ('RE', 'RW'))
-- MAIN CAMPUS STUDENT (+/-) ENROLLED STUDENTS
      -- AND SGBSTDN_DEGC_CODE_1 <> 'AAS'
-- RANGER SCHOOL STUDENTS (+/-) ENROLLED STUDENTS
      -- AND SGBSTDN_DEGC_CODE_1 = 'AAS'
-- ND STUDENT (+/-) ENROLLED STUDENTS
      -- AND SGBSTDN_DEGC_CODE_1 = 'ND'
--GRADUATE SCHOOL STUDENTS (+/-) ENROLLED STUDENTS
      -- AND SGBSTDN_LEVL_CODE = 'GR'
--UNDERGRADUATE SCHOOL STUDENTS (+/-) ENROLLED STUDENTS
      -- AND SGBSTDN_LEVL_CODE = 'UG'
-- VISITING STUDENT (+/-) ENROLLED STUDENTS
      -- AND SGBSTDN_MAJR_CODE_1 = 'VIS'
-- SU STUDENT (+/-) ENROLLED STUDENTS
      -- AND SGBSTDN_MAJR_CODE_1 = 'SUS'
-- EHS STUDENT (+/-) ENROLLED STUDENTS
      -- AND SGBSTDN_MAJR_CODE_1 = 'EHS'
         --$addfilter

         --$beginorder
ORDER BY
        --ALL STUDENT-FACING QUERIES

        LAST, FIRST

        --SV1 ONLY
        --SSBSECT_SICAS_CAMP_SECTION_ID
         --$endorder