-- Department Selection
select
      distinct SGBSTDN.SGBSTDN_DEPT_CODE,
      STVDEPT.STVDEPT_CODE,
      STVDEPT.STVDEPT_DESC,
      STVDEPT.STVDEPT_CODE || ' - ' || STVDEPT.STVDEPT_DESC as DEPT_DESC
from
    SGBSTDN SGBSTDN
    join STVDEPT STVDEPT on STVDEPT.STVDEPT_CODE = SGBSTDN.SGBSTDN_DEPT_CODE

where
     SGBSTDN.SGBSTDN_DEPT_CODE is not null
     --and STVDEPT.STVDEPT_CODE in ('CHEM', 'EFB', 'ERE', 'ESC', 'EST', 'FRM', 'LA', 'PBE', 'OA', 'OSUS')

order by
      SGBSTDN.SGBSTDN_DEPT_CODE